extends SceneTree

const Content = preload("res://foundation/content.gd")
const Simulation = preload("res://foundation/run.gd")
const AuthoringSession = preload("res://foundation/authoring_session.gd")
const Journal = preload("res://foundation/journal.gd")
const AuthoringDocument = preload("res://foundation/authoring_document.gd")
const ProjectAssets = preload("res://foundation/project_assets.gd")
const RoomGeometry = preload("res://foundation/room_geometry.gd")
const AuthoringStore = preload("res://foundation/authoring_store.gd")
const Harness = preload("res://foundation/harness.gd")
var failures: Array[String] = []

func _initialize() -> void:
	call_deferred("run")

func expect(condition: bool, name: String) -> void:
	if not condition:
		failures.append(name)
		printerr("FOUNDATION_FAIL ", name)

func expect_joy_button(action: String, button: int) -> void:
	var mapped := false
	for event in InputMap.action_get_events(action):
		if event is InputEventJoypadButton and event.button_index == button:
			mapped = true
	expect(mapped, "controller_mapping_" + action)

func run() -> void:
	expect_joy_button("wheel_confirm", JOY_BUTTON_RIGHT_SHOULDER)
	expect_joy_button("pause_game", JOY_BUTTON_BACK)
	expect_joy_button("cancel_action", JOY_BUTTON_B)
	expect_joy_button("reset_loop", JOY_BUTTON_START)
	var scenario := Content.scenario()
	expect(Content.validate(scenario).is_empty(), "valid_scenario")
	var image_bytes := FileAccess.get_file_as_bytes("res://assets/props/valve_states.png")
	var imported: Dictionary = ProjectAssets.import_image("test.png", image_bytes)
	expect(imported.ok and ProjectAssets.validate(imported.asset).is_empty(), "portable_image_manifest_entry")
	var illustrated := scenario.duplicate(true)
	illustrated.assets[imported.id] = imported.asset
	illustrated.rooms[0].background_asset = imported.id
	expect(Content.validate(illustrated).is_empty(), "room_background_asset_reference")
	illustrated.assets.erase(imported.id)
	expect(not Content.validate(illustrated).is_empty(), "missing_background_asset_rejected")
	var bad_geometry := scenario.duplicate(true)
	bad_geometry.rooms[0].walkable = [[0, 0, 200, 280]]
	expect(not Content.validate(bad_geometry).is_empty(), "unreachable_geometry_reference_rejected")
	expect(RoomGeometry.contains(scenario.rooms[0], Vector2(80, 160)) and not RoomGeometry.contains(scenario.rooms[0], Vector2(450, 160)), "walkable_coordinate_mapping")
	var shaped_room := {"id": "shaped", "bounds": [0, 0, 100, 100], "walkable": [[0, 0, 40, 100], [40, 60, 60, 40]]}
	expect(RoomGeometry.validate(shaped_room).is_empty(), "shaped_room_valid")
	expect(RoomGeometry.move(shaped_room, Vector2(35, 20), Vector2(10, 0)) == Vector2(35, 20), "movement_stops_at_authored_boundary")
	var narrow_gap := {"bounds": [0, 0, 100, 100], "walkable": [[0, 0, 40, 100], [41, 0, 59, 100]]}
	expect(RoomGeometry.move(narrow_gap, Vector2(40, 50), Vector2(2, 0)) == Vector2(40, 50), "movement_cannot_jump_narrow_gap")
	expect(RoomGeometry.path(shaped_room, Vector2(20, 20), Vector2(80, 80)).size() == 2, "npc_route_uses_overlapping_regions")
	var path_position := Vector2(20, 20)
	for i in range(100): path_position = RoomGeometry.step_toward(shaped_room, path_position, Vector2(80, 80), 4.0)
	expect(path_position.distance_to(Vector2(80, 80)) < 0.01, "npc_step_reaches_target_through_authored_geometry")
	var authored_layout := scenario.duplicate(true)
	authored_layout.rooms[0].walkable = [[0, 0, 220, 280], [220, 190, 220, 90], [300, 0, 140, 190]]
	authored_layout.commitments[1].at_tick = 200
	expect(Content.validate(authored_layout).is_empty(), "authored_navigation_layout_valid")
	var constrained_run := Simulation.new(authored_layout)
	for i in range(70): constrained_run.tick({"x": 1.0})
	expect(float(constrained_run.state.actors.amelia.x) <= 220.01 and constrained_run.state.actors.amelia.room == "service", "player_cannot_cross_unwalkable_gap")
	for i in range(110): constrained_run.tick()
	expect(constrained_run.state.actors.chatterbox.room == "corridor", "npc_routes_around_authored_gap")
	var occupied_run := Simulation.new(scenario)
	for i in range(30): occupied_run.tick({"x": 1.0})
	var removed_ground := scenario.duplicate(true)
	removed_ground.version = "removed-ground"
	removed_ground.rooms[0].walkable = [[0, 0, 180, 280], [180, 220, 260, 60], [300, 0, 140, 220]]
	expect(Content.validate(removed_ground).is_empty(), "removed_ground_statically_valid")
	var occupied_history := occupied_run.history.duplicate(true)
	var occupied_result := occupied_run.continue_with_content(removed_ground)
	expect(not occupied_result.ok and occupied_result.restart and str(occupied_result.reason).contains("amelia") and occupied_run.history == occupied_history, "resume_rejects_ground_removed_under_actor")
	var inaccessible_valve := scenario.duplicate(true)
	inaccessible_valve.rooms[0].walkable = [[0, 0, 180, 280], [300, 0, 140, 280]]
	expect("Interaction valve is unreachable from Amelia through authored walkable regions and room connections" in Content.validate(inaccessible_valve), "unreachable_interaction_blocks_resume")
	var display := Harness.new()
	display.simulation = Simulation.new(scenario)
	display.session = AuthoringSession.new(display.simulation)
	display.document = display.session.document
	display.session.pause()
	var changed_display := display.document.content.duplicate(true)
	changed_display.rooms[0].bounds = [10, 20, 220, 140]
	display.document.replace_content(changed_display, "Resize room")
	expect(display._canvas_point(Vector2(460, 160)) == Vector2(120, 90) and display._world_to_canvas(changed_display.rooms[0], Vector2(120, 90)) == Vector2(460, 160), "authored_room_coordinate_mapping")
	display.session.view_tick(0)
	expect(display._shown_content(display.session.inspect()) == scenario, "historical_view_uses_recorded_content")
	display.session.return_live()
	expect(display._shown_content(display.session.inspect()) == changed_display, "paused_live_view_previews_draft")
	display.free()
	var placement := Harness.new()
	placement.simulation = Simulation.new(scenario)
	placement.session = AuthoringSession.new(placement.simulation)
	placement.document = placement.session.document
	placement.session.pause()
	placement.status_label = Label.new()
	placement.interaction_label_edit = LineEdit.new()
	placement.interaction_label_edit.text = "Close test valve"
	placement.interaction_duration_edit = SpinBox.new()
	placement.interaction_duration_edit.min_value = 1
	placement.interaction_duration_edit.value = 5
	placement.interaction_effect_edit = OptionButton.new()
	placement.interaction_effect_edit.add_item("Close valve")
	placement.interaction_effect_edit.add_item("Delay guest")
	placement.interaction_effect_edit.select(0)
	placement.interaction_effect_ticks_edit = SpinBox.new()
	placement.interaction_effect_ticks_edit.value = 60
	placement.geometry_mode = "door_start"
	var place_click := InputEventMouseButton.new()
	place_click.button_index = MOUSE_BUTTON_LEFT
	place_click.pressed = true
	place_click.position = Vector2(780, 180)
	placement._on_canvas_input(place_click)
	placement.inspected_room = "corridor"
	place_click.position = Vector2(100, 180)
	placement._on_canvas_input(place_click)
	expect(placement.document.content.connections.size() == 2 and placement.document.content.connections[1].from_x == 380.0, "door_endpoints_created_visually")
	placement._move_nearest_door(Vector2(60, 160))
	expect(placement.document.content.connections[1].to_x == 60.0 and placement.document.undo() == "Move service_corridor_2 door in corridor" and placement.document.redo() == "Move service_corridor_2 door in corridor", "door_endpoint_move_transaction")
	placement._place_interaction(Vector2(240, 160))
	expect(placement.document.content.interactions[0].room == "corridor" and placement.document.content.interactions[0].duration_ticks == 5, "timed_interaction_placed_visually")
	expect(placement.document.undo() == "Place valve interaction in corridor" and placement.document.undo() == "Move service_corridor_2 door in corridor" and placement.document.undo() == "Connect service to corridor", "door_and_prop_undo_chronological")
	expect(placement.document.redo() == "Connect service to corridor" and placement.document.redo() == "Move service_corridor_2 door in corridor" and placement.document.redo() == "Place valve interaction in corridor", "door_and_prop_redo_chronological")
	placement._remove_nearest_door(Vector2(20, 160))
	expect(placement.document.content.connections.size() == 1 and placement.document.content.connections[0].id == "service_corridor_2" and placement.document.undo() == "Remove door service_corridor" and placement.document.redo() == "Remove door service_corridor", "visual_door_removal_replaces_old_route")
	var placed_run := Simulation.new(scenario)
	expect(placement.document.apply_to(placed_run).ok, "placed_door_and_interaction_apply")
	var start_x: float = float(placed_run.state.actors.amelia.x)
	placed_run.tick({"start_interaction": "valve"})
	expect(placed_run.state.actors.amelia.x == start_x and placed_run.state.action.is_empty(), "distant_choice_does_not_auto_walk")
	for i in range(75): placed_run.tick({"x": 1.0})
	expect(placed_run.state.actors.amelia.room == "corridor", "amelia_uses_authored_door")
	expect(placed_run.state.actors.chatterbox.room == "corridor", "npc_uses_authored_door")
	for i in range(45): placed_run.tick({"x": 1.0})
	placed_run.tick({"start_interaction": "valve"})
	for i in range(5): placed_run.tick()
	expect(placed_run.state.flags.get("close_valve", false), "authored_timed_interaction_completes")
	placement.inspected_room = "service"
	placement.interaction_effect_edit.select(1)
	placement.interaction_effect_ticks_edit.value = 70
	placement.interaction_duration_edit.value = 3
	placement.interaction_label_edit.text = "Signal the guest"
	placement._place_interaction(Vector2(80, 160))
	var signal_run := Simulation.new(scenario)
	expect(placement.document.apply_to(signal_run).ok, "configured_guest_delay_interaction_applies")
	signal_run.tick({"start_interaction": "guest_signal"})
	for i in range(3): signal_run.tick()
	expect(signal_run.state.flags.get("guest_delay_ticks", 0) == 70 and signal_run.state.completed_interactions.has("guest_signal"), "configured_interaction_effect_executes_once")
	var signal_path := "res://build/signal-interaction-%d.jsonl" % OS.get_process_id()
	signal_run.attach_journal(signal_path)
	expect(signal_run.persist().ok, "configured_interaction_effect_saved")
	var signal_reloaded := Simulation.new(scenario)
	signal_reloaded.attach_journal(signal_path)
	expect(signal_reloaded.load_saved().ok and signal_reloaded.state.completed_interactions.has("guest_signal") and signal_reloaded.state.flags.guest_delay_ticks == 70, "configured_interaction_effect_reloaded")
	var left_door := scenario.duplicate(true)
	left_door.connections[0].from_x = 50.0
	var left_run := Simulation.new(left_door)
	left_run.tick({"x": 1.0})
	expect(left_run.state.actors.amelia.room == "service", "door_does_not_trigger_away_from_endpoint")
	for i in range(9): left_run.tick({"x": -1.0})
	expect(left_run.state.actors.amelia.room == "corridor", "leftward_authored_door_crossing")
	var top_door := scenario.duplicate(true)
	top_door.connections[0].from_x = 80.0
	top_door.connections[0].from_y = 0.0
	var top_run := Simulation.new(top_door)
	for i in range(40): top_run.tick({"y": -1.0})
	expect(top_run.state.actors.amelia.room == "corridor", "vertical_authored_door_crossing")
	var off_grid_door := scenario.duplicate(true)
	off_grid_door.connections[0].from_x = 381.0
	off_grid_door.connections[0].from_y = 161.0
	var off_grid_run := Simulation.new(off_grid_door)
	for i in range(76): off_grid_run.tick({"x": 1.0})
	expect(off_grid_run.state.actors.amelia.room == "corridor", "off_grid_door_has_usable_visual_radius")
	var conditional_door := scenario.duplicate(true)
	conditional_door.connections[0].requires_flag = "close_valve"
	expect(Content.validate(conditional_door).is_empty(), "intentional_conditional_access_validates")
	var conditional_run := Simulation.new(conditional_door)
	for i in range(90): conditional_run.tick({"x": 1.0})
	expect(conditional_run.state.actors.amelia.room == "service", "conditional_door_blocks_without_flag")
	conditional_run.state.flags.close_valve = true
	for i in range(5): conditional_run.tick({"x": -1.0})
	expect(conditional_run.state.actors.amelia.room == "corridor", "conditional_door_opens_after_flag")
	var separated_choice := scenario.duplicate(true)
	separated_choice.rooms[0].walkable = [[0, 0, 100, 280], [110, 0, 330, 280], [100, 220, 10, 60]]
	separated_choice.interactions[0].x = 120.0
	expect(Content.validate(separated_choice).is_empty() and Simulation.new(separated_choice).available_interactions().is_empty(), "interaction_not_local_through_unwalkable_wall")
	placement.free()
	var room_document := AuthoringDocument.new(scenario)
	room_document.set_source("~ start\ndo broken(\n=> END")
	var room_change := room_document.content.duplicate(true)
	room_change.rooms.append({"id": "gallery", "name": "Gallery", "bounds": [0, 0, 100, 100], "walkable": [[0, 0, 100, 100]]})
	room_document.replace_content(room_change, "Create gallery")
	expect(room_document.source_draft.contains("broken("), "geometry_edit_preserves_invalid_source_draft")
	expect(room_document.undo() == "Create gallery" and room_document.content.rooms.size() == 2, "shared_undo_reverses_room_edit")
	expect(room_document.undo() == "Edit scene source" and room_document.source_draft == scenario.dialogue, "shared_undo_reverses_prior_source_edit")
	expect(room_document.redo() == "Edit scene source" and room_document.redo() == "Create gallery", "shared_redo_chronological_order")
	room_document.set_source(scenario.dialogue)
	expect(room_document.apply_to(Simulation.new(scenario)).ok and room_document.content.version != scenario.version, "geometry_document_applies_new_version")
	var authoring_snapshot := room_document.serialize()
	var reopened_document := AuthoringDocument.new(scenario)
	expect(reopened_document.restore(authoring_snapshot) and reopened_document.content == room_document.content and reopened_document.undo_stack.size() == room_document.undo_stack.size(), "authoring_document_restores_transactions")
	var draft_before_head := reopened_document.source_draft
	var undo_before_same_head := reopened_document.undo_stack.size()
	reopened_document.change_head("local")
	expect(reopened_document.undo_stack.size() == undo_before_same_head, "unchanged_head_retains_authoring_history")
	reopened_document.change_head("remote-main-2")
	expect(reopened_document.undo_stack.is_empty() and reopened_document.redo_stack.is_empty() and reopened_document.source_draft == draft_before_head, "head_change_clears_history_preserves_draft")
	var broken := scenario.duplicate(true)
	broken.connections[0].to = "missing"
	expect(not Content.validate(broken).is_empty(), "broken_connection_rejected")
	expect(not Content.validate({"schema": 1, "version": "bad", "rooms": "oops"}).is_empty(), "malformed_content_rejected")
	var missing_coordinate := scenario.duplicate(true)
	missing_coordinate.actors[0].erase("x")
	expect(not Content.validate(missing_coordinate).is_empty(), "missing_actor_coordinate_rejected")
	var missing_amelia := scenario.duplicate(true)
	missing_amelia.actors.remove_at(0)
	expect(not Content.validate(missing_amelia).is_empty(), "required_actor_rejected")
	var first := Simulation.new(scenario)
	var second := Simulation.new(scenario)
	for index in range(150):
		var input := {"x": 1.0 if index < 90 else 0.0, "y": 0.0}
		var a := first.tick(input)
		var b := second.tick(input)
		expect(a == b, "deterministic_tick_%d" % index)
	expect(first.state.actors.amelia.room == "corridor", "direct_room_crossing")
	expect(first.state.actors.chatterbox.room == "service", "npc_returns_offscreen")
	expect(first.state.events is Array, "ordered_events_public")
	var action_run := Simulation.new(scenario)
	for i in range(48): action_run.tick({"x": 1.0})
	expect(action_run.available_interactions().size() == 1, "interaction_local")
	action_run.tick({"start_interaction": "valve"})
	expect(action_run.state.action.progress == 0, "action_start_serializable")
	for i in range(30): action_run.tick()
	expect(action_run.state.flags.get("close_valve", false), "action_effect_completed")
	expect(action_run.state.action.is_empty(), "action_finished")
	var unaltered := Simulation.new(scenario)
	for i in range(111): unaltered.tick()
	while action_run.state.tick < 111: action_run.tick()
	expect(unaltered.state.actors.guest.activity == "travel" and action_run.state.actors.guest.activity == "idle", "timed_effect_changes_npc_commitment")
	var completed_events := 0
	for i in range(35):
		action_run.tick()
		for event in action_run.events:
			if event.category == "action_completed": completed_events += 1
	expect(completed_events == 0, "effect_not_repeated")
	var cancelled := Simulation.new(scenario)
	for i in range(48): cancelled.tick({"x": 1.0})
	cancelled.tick({"start_interaction": "valve"})
	for i in range(10): cancelled.tick()
	cancelled.tick({"cancel_action": true})
	expect(cancelled.state.action.is_empty() and not cancelled.state.flags.get("close_valve", false), "interrupt_loses_progress")
	var moved_away := Simulation.new(scenario)
	for i in range(48): moved_away.tick({"x": 1.0})
	moved_away.tick({"start_interaction": "valve"})
	moved_away.tick({"x": -1.0})
	expect(moved_away.state.action.is_empty() and moved_away.events[0].category == "action_cancelled", "range_invalidation_cancels_immediately")
	var invalidated := Simulation.new(scenario)
	for i in range(48): invalidated.tick({"x": 1.0})
	invalidated.tick({"start_interaction": "valve"})
	for i in range(29): invalidated.tick()
	invalidated.tick({"x": -1.0, "cancel_action": true})
	expect(not invalidated.state.flags.get("close_valve", false), "simultaneous_cancel_before_complete")
	var boundary := Simulation.new(scenario)
	for i in range(48): boundary.tick({"x": 1.0})
	for i in range(Simulation.TICKS_PER_HOUR - 5 - 48): boundary.tick()
	boundary.tick({"start_interaction": "valve"})
	for i in range(30): boundary.tick()
	expect(boundary.state.flags.get("close_valve", false), "action_crosses_hour")
	var talk := Simulation.new(scenario)
	for i in range(10): talk.tick({"x": 1.0})
	expect(talk.dialogue_available(), "dialogue_local")
	talk.tick({"start_dialogue": true})
	expect(str(talk.state.dialogue.line).begins_with("Chatterbox:"), "first_speaker")
	expect(talk.state.diary_observations.size() == 1 and talk.state.current_knowledge.is_empty(), "observation_not_eligibility")
	talk.tick({"advance_dialogue": true})
	expect(talk.state.dialogue.remaining == Simulation.DIALOGUE_TICKS, "fixed_step_cost")
	for i in range(Simulation.DIALOGUE_TICKS): talk.tick()
	expect(str(talk.state.dialogue.line).begins_with("Amelia:"), "second_speaker")
	expect(talk.state.flags.guest_delay_ticks == 40 and talk.state.current_knowledge.has("guest_will_wait"), "world_command_once")
	var guest_before_visit: Dictionary = talk.state.actors.guest.duplicate(true)
	for i in range(110 - talk.state.tick): talk.tick()
	expect(talk.state.actors.guest == guest_before_visit, "dialogue_changes_later_schedule")
	var repeat_scenario := scenario.duplicate(true)
	repeat_scenario.commitments[0].at_tick = 1000
	var repeated := Simulation.new(repeat_scenario)
	for i in range(10): repeated.tick({"x": 1.0})
	for turn in range(2):
		repeated.tick({"start_dialogue": true})
		repeated.tick({"advance_dialogue": true})
		for i in range(Simulation.DIALOGUE_TICKS): repeated.tick()
		repeated.tick({"advance_dialogue": true})
		for i in range(Simulation.DIALOGUE_TICKS): repeated.tick()
	expect(repeated.state.flags.guest_delay_ticks == 40, "repeated_conversation_does_not_repeat_effect")
	var bad_dialogue := scenario.duplicate(true)
	bad_dialogue.dialogue = bad_dialogue.dialogue.replace("delay_guest(40)", "unknown_command(40)")
	expect(not Content.validate(bad_dialogue).is_empty(), "unknown_command_rejected")
	var bad_speaker := scenario.duplicate(true)
	bad_speaker.dialogue = bad_speaker.dialogue.replace("Amelia:", "UnknownActor:")
	expect(not Content.validate(bad_speaker).is_empty(), "missing_dialogue_actor_rejected")
	var history_run := Simulation.new(scenario)
	var observed: Array[Dictionary] = [history_run.inspect()]
	for i in range(130): observed.append(history_run.tick({"x": 1.0 if i < 90 else 0.0}))
	for i in [0, 1, 19, 20, 80, 90, 129, 130]:
		expect(history_run.inspect_at(i) == observed[i], "recorded_tick_%d" % i)
	var live_before := history_run.inspect()
	var old_snapshot := history_run.inspect_at(20)
	old_snapshot.actors.amelia.x = -1000.0
	expect(history_run.inspect() == live_before and history_run.inspect_at(20).actors.amelia.x != -1000.0, "scrub_is_read_only")
	expect(history_run.inspect_at(19).diagnostics.content_version == scenario.version, "recorded_provenance")
	var knowledge_before: Array = history_run.state.current_knowledge.duplicate(true)
	var remote_room_state := history_run.inspect_at(80)
	expect(remote_room_state.actors.guest.room == "corridor" and history_run.state.current_knowledge == knowledge_before, "offscreen_inspection_grants_no_knowledge")
	var event_run := Simulation.new(scenario)
	var event_state := event_run.step_next_event()
	expect(event_state.tick == 20 and event_state.events[0].category == "commitment", "next_event_stops_at_commitment")
	var branch_run := Simulation.new(scenario)
	for i in range(120): branch_run.tick()
	var old_past := branch_run.inspect_at(10)
	var old_future := branch_run.inspect_at(115)
	var invalid_edit := scenario.duplicate(true)
	invalid_edit.dialogue = "~ start\ndo missing_command()\n=> END"
	var invalid_result := branch_run.continue_with_content(invalid_edit, 10)
	expect(not invalid_result.ok and branch_run.state.tick == 120 and branch_run.inspect_at(115) == old_future, "invalid_edit_keeps_future")
	var compatible := scenario.duplicate(true)
	compatible.version = "two-room-2"
	compatible.dialogue = compatible.dialogue.replace("delay_guest(40)", "delay_guest(80)")
	var branch_result := branch_run.continue_with_content(compatible, 10)
	expect(branch_result.ok and branch_run.state.tick == 10 and branch_run.history.size() == 11, "historical_resume_truncates_future")
	expect(branch_run.inspect_at(10) == old_past, "historical_record_unchanged")
	var authoring_run := Simulation.new(scenario)
	for i in range(35): authoring_run.tick()
	var authoring := AuthoringSession.new(authoring_run)
	authoring.pause()
	authoring.view_tick(10)
	var authoring_future := authoring_run.inspect_at(30)
	authoring.set_draft("~ start\ndo missing_command()\n=> END")
	expect(not authoring.resume(true).ok and authoring.paused and authoring_run.state.tick == 35 and authoring_run.inspect_at(30) == authoring_future, "session_rejects_edit_without_losing_future")
	authoring.set_draft(str(scenario.dialogue).replace("delay_guest(40)", "delay_guest(80)"))
	expect(authoring.resume(true).ok and not authoring.paused and authoring_run.state.tick == 10 and authoring_run.history.size() == 11, "session_branches_after_validation")
	expect(authoring_run.inspect_at(10).diagnostics.content_version == scenario.version, "session_preserves_recorded_diagnostics")
	authoring.pause()
	authoring.set_draft("~ start\ndo missing_command()\n=> END")
	expect(not authoring.step_tick().ok and authoring_run.state.tick == 10, "session_blocks_step_on_invalid_draft")
	authoring.set_draft(str(authoring_run.content.dialogue))
	expect(authoring.step_tick().ok and authoring.paused and authoring_run.state.tick == 11, "session_steps_valid_draft")
	var authoring_save := "res://build/foundation-session-%d.jsonl" % OS.get_process_id()
	authoring_run.attach_journal(authoring_save)
	expect(authoring_run.persist().ok, "session_branch_persisted")
	var authoring_reloaded := Simulation.new(scenario)
	authoring_reloaded.attach_journal(authoring_save)
	expect(authoring_reloaded.load_saved().ok and authoring_reloaded.inspect() == authoring_run.inspect() and authoring_reloaded.history == authoring_run.history, "session_branch_reloaded")
	branch_run.tick()
	expect(branch_run.state.content_version == "two-room-2" and branch_run.inspect_at(11).content_version == "two-room-2", "new_future_provenance")
	var reused_version := compatible.duplicate(true)
	reused_version.dialogue = reused_version.dialogue.replace("delay_guest(80)", "delay_guest(90)")
	expect(not branch_run.continue_with_content(reused_version).ok, "version_reuse_rejected")
	var active_dialogue := Simulation.new(scenario)
	for i in range(10): active_dialogue.tick({"x": 1.0})
	active_dialogue.tick({"start_dialogue": true})
	var incompatible_result := active_dialogue.continue_with_content(compatible)
	expect(not incompatible_result.ok and incompatible_result.restart and active_dialogue.state.dialogue.cursor == 0, "active_dialogue_requires_restart")
	var authored := AuthoringDocument.new(scenario)
	var edited_source: String = scenario.dialogue.replace("delay_guest(40)", "delay_guest(80)")
	authored.set_source(edited_source)
	expect(authored.undo() == "Edit scene source" and authored.source_draft == scenario.dialogue, "authoring_undo_source")
	expect(authored.redo() == "Edit scene source" and authored.source_draft == edited_source, "authoring_redo_source")
	authored.undo()
	authored.set_source(edited_source.replace("delay_guest(80)", "delay_guest(90)"))
	expect(authored.redo().is_empty(), "new_edit_clears_stale_redo")
	authored.undo()
	authored.redo()
	authored.undo()
	authored.set_source(edited_source)
	var authored_run := Simulation.new(scenario)
	expect(authored.apply_to(authored_run).ok and authored_run.content.dialogue == edited_source, "authoring_resume_applies_valid_document")
	for i in range(10): authored_run.tick({"x": 1.0})
	authored_run.tick({"start_dialogue": true})
	authored_run.tick({"advance_dialogue": true})
	for i in range(Simulation.DIALOGUE_TICKS): authored_run.tick()
	expect(authored_run.state.flags.guest_delay_ticks == 80, "authoring_changes_future_effect")
	var unchanged_history := authored_run.history.duplicate(true)
	authored.set_source("~ start\ndo missing_command()\n=> END")
	expect(not authored.apply_to(authored_run, 5).ok and authored_run.history == unchanged_history and authored.content.dialogue == edited_source, "invalid_draft_preserves_applied_content_and_history")
	authored.set_source(edited_source.replace("delay_guest(80)", "delay_guest(90)"))
	var active_document_result := authored.apply_to(authored_run)
	expect(not active_document_result.ok and active_document_result.restart and authored_run.state.flags.guest_delay_ticks == 80, "document_rejects_active_dialogue_edit_without_replay")
	var active_action := Simulation.new(scenario)
	for i in range(48): active_action.tick({"x": 1.0})
	active_action.tick({"start_interaction": "valve"})
	var changed_action := scenario.duplicate(true)
	changed_action.version = "changed-action"
	changed_action.interactions[0].duration_ticks = 50
	expect(active_action.continue_with_content(changed_action).restart, "active_action_requires_restart")
	var compatible_action := scenario.duplicate(true)
	compatible_action.version = "compatible-action"
	compatible_action.dialogue = compatible_action.dialogue.replace("coming soon", "arriving soon")
	var mid_action_tick: int = active_action.state.tick
	for i in range(8): active_action.tick()
	expect(active_action.continue_with_content(compatible_action, mid_action_tick).ok, "compatible_mid_action_resume")
	for i in range(30): active_action.tick()
	expect(active_action.state.flags.get("close_valve", false), "mid_action_resume_completes_once")
	var compatible_dialogue := scenario.duplicate(true)
	compatible_dialogue.version = "compatible-dialogue"
	compatible_dialogue.interactions[0].label = "Close valve"
	expect(active_dialogue.continue_with_content(compatible_dialogue).ok, "compatible_mid_dialogue_resume")
	active_dialogue.tick({"advance_dialogue": true})
	for i in range(Simulation.DIALOGUE_TICKS): active_dialogue.tick()
	expect(active_dialogue.state.flags.guest_delay_ticks == 40, "mid_dialogue_resume_command_once")
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path("res://build"))
	var authoring_path := "res://build/authoring-test-%d.json" % OS.get_process_id()
	var store := AuthoringStore.new(authoring_path)
	var persistent_document := AuthoringDocument.new(scenario)
	persistent_document.set_source("~ start\ndo incomplete(")
	expect(store.save(persistent_document).ok, "invalid_source_draft_autosave_allowed")
	var loaded_authoring := AuthoringStore.load(authoring_path)
	var restored_document := AuthoringDocument.new(scenario)
	expect(loaded_authoring.ok and restored_document.restore(loaded_authoring.data) and restored_document.source_draft.contains("incomplete(") and restored_document.undo_stack.size() == 1, "invalid_source_draft_and_undo_reopen")
	persistent_document.set_source("~ start\nAmelia: valid\n=> END")
	persistent_document.finish_source_group()
	expect(store.save(persistent_document).ok, "authoring_second_revision_saved")
	var torn_authoring := FileAccess.open(authoring_path, FileAccess.WRITE)
	torn_authoring.store_string("{bad")
	torn_authoring.close()
	var recovered_authoring := AuthoringStore.load(authoring_path)
	expect(recovered_authoring.ok and str(recovered_authoring.source).ends_with(".bak"), "corrupt_primary_recovers_prior_authoring_backup")
	var staged_authoring := FileAccess.open(authoring_path + ".next", FileAccess.WRITE)
	staged_authoring.store_string(AuthoringStore._encode(persistent_document.serialize()))
	staged_authoring.close()
	var recovered_stage := AuthoringStore.load(authoring_path)
	expect(recovered_stage.ok and str(recovered_stage.source).ends_with(".next") and recovered_stage.data.revision == persistent_document.revision, "interrupted_authoring_promotion_recovers_newer_stage")
	var unavailable_authoring := AuthoringStore.new("res://missing-authoring-parent-%d/draft.json" % OS.get_process_id())
	expect(not unavailable_authoring.save(persistent_document).ok, "authoring_storage_failure_reported")
	var save_path := "res://build/foundation-test-%d.jsonl" % OS.get_process_id()
	var journal := Journal.new(save_path)
	var branch_save := Journal.new(save_path + ".branch")
	expect(branch_save.save(branch_run).ok, "save_branched_history")
	var branch_loaded := Journal.load(branch_save.path)
	expect(branch_loaded.ok and branch_loaded.content_versions.has("two-room-1") and branch_loaded.content_versions.has("two-room-2"), "historical_content_provenance_persisted")
	var saved_run := Simulation.new(scenario)
	for i in range(10): saved_run.tick({"x": 1.0})
	saved_run.tick({"start_dialogue": true})
	saved_run.tick({"advance_dialogue": true})
	expect(journal.save(saved_run).ok, "save_pending_dialogue")
	var loaded := Journal.load(save_path)
	var restored := Simulation.new(scenario)
	expect(loaded.ok and restored.restore_record(loaded), "reload_pending_dialogue")
	expect(restored.inspect() == saved_run.inspect() and restored.history == saved_run.history, "reload_exact_state_and_history")
	for i in range(Simulation.DIALOGUE_TICKS):
		saved_run.tick()
		restored.tick()
	expect(restored.inspect() == saved_run.inspect() and restored.state.flags.guest_delay_ticks == 40, "reload_command_once")
	var saved_action := Simulation.new(scenario)
	for i in range(48): saved_action.tick({"x": 1.0})
	saved_action.tick({"start_interaction": "valve"})
	for i in range(7): saved_action.tick()
	var action_journal := Journal.new(save_path + ".action")
	expect(action_journal.save(saved_action).ok, "save_mid_action")
	var reloaded_action := Simulation.new(scenario)
	expect(reloaded_action.restore_record(Journal.load(action_journal.path)), "reload_mid_action")
	for i in range(23):
		saved_action.tick()
		reloaded_action.tick()
	expect(reloaded_action.inspect() == saved_action.inspect() and reloaded_action.state.flags.get("close_valve", false), "reloaded_action_completes_once")
	expect(journal.save(saved_run).ok, "append_new_ticks")
	var managed_path := save_path + ".managed"
	var managed := Simulation.new(scenario)
	managed.attach_journal(managed_path)
	expect(managed.persist().ok, "run_persists_initial_state")
	managed.tick({"x": 1.0})
	expect(managed.persist().ok, "run_persists_completed_tick")
	var reopened := Simulation.new(scenario)
	reopened.attach_journal(managed_path)
	expect(reopened.load_saved().ok and reopened.inspect() == managed.inspect() and reopened.history == managed.history, "run_reopens_history")
	var torn := FileAccess.open(save_path, FileAccess.READ_WRITE)
	torn.seek_end()
	torn.store_string("{bad tail")
	torn.close()
	var recovered := Journal.load(save_path)
	expect(recovered.ok and recovered.history.size() == saved_run.history.size(), "torn_tail_recovers_last_tick")
	var continued := Simulation.new(scenario)
	expect(continued.restore_record(recovered), "recover_into_simulation")
	var repair_journal := Journal.new(save_path)
	repair_journal.saved_count = 0
	continued.tick()
	expect(repair_journal.save(continued).ok, "repair_before_append")
	expect(Journal.load(save_path).history.size() == continued.history.size(), "reopen_after_repair")
	var unsupported_path := save_path + ".unsupported"
	var unsupported := FileAccess.open(unsupported_path, FileAccess.WRITE)
	unsupported.store_line(Journal._encode({"schema": 999, "kind": "content", "content": scenario}))
	unsupported.close()
	expect(not Journal.load(unsupported_path).ok, "unsupported_save_rejected")
	var malformed_path := save_path + ".malformed"
	var malformed := FileAccess.open(malformed_path, FileAccess.WRITE)
	malformed.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "content", "content": {"schema": 1, "version": "bad", "rooms": "oops"}}))
	malformed.close()
	expect(not Journal.load(malformed_path).ok, "malformed_save_rejected")
	var malformed_state_path := save_path + ".malformed-state"
	var malformed_state := FileAccess.open(malformed_state_path, FileAccess.WRITE)
	malformed_state.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "content", "content": scenario}))
	malformed_state.store_line(Journal._encode({"schema": Journal.SCHEMA, "tick": 0, "state": {"tick": 0, "actors": {}, "flags": {}, "action": {}, "dialogue": {}, "events": [], "diary_observations": [], "current_knowledge": [], "content_version": scenario.version}}))
	malformed_state.close()
	expect(not Journal.load(malformed_state_path).ok, "malformed_state_rejected")
	var malformed_nested_path := save_path + ".malformed-nested"
	var malformed_nested := FileAccess.open(malformed_nested_path, FileAccess.WRITE)
	malformed_nested.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "content", "content": scenario}))
	var bad_snapshot := Simulation.new(scenario).inspect()
	bad_snapshot.events = ["bad"]
	malformed_nested.store_line(Journal._encode({"schema": Journal.SCHEMA, "tick": 0, "state": bad_snapshot}))
	malformed_nested.close()
	expect(not Journal.load(malformed_nested_path).ok, "malformed_event_rejected")
	var malformed_action_path := save_path + ".malformed-action"
	var malformed_action := FileAccess.open(malformed_action_path, FileAccess.WRITE)
	malformed_action.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "content", "content": scenario}))
	var bad_action := Simulation.new(scenario).inspect()
	bad_action.action = {"id": "valve"}
	malformed_action.store_line(Journal._encode({"schema": Journal.SCHEMA, "tick": 0, "state": bad_action}))
	malformed_action.close()
	expect(not Journal.load(malformed_action_path).ok, "malformed_action_rejected")
	var staged_only_path := save_path + ".staged-only"
	var staged_only := FileAccess.open(staged_only_path + ".next", FileAccess.WRITE)
	staged_only.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "content", "content": scenario}))
	staged_only.store_line(Journal._encode({"schema": Journal.SCHEMA, "tick": 0, "state": Simulation.new(scenario).inspect()}))
	staged_only.close()
	expect(Journal.load(staged_only_path).ok, "staged_save_recovered")
	var promotion_path := save_path + ".promotion"
	var old_backup := FileAccess.open(promotion_path + ".bak", FileAccess.WRITE)
	old_backup.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "content", "content": scenario}))
	old_backup.store_line(Journal._encode({"schema": Journal.SCHEMA, "tick": 0, "state": Simulation.new(scenario).inspect()}))
	old_backup.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "head", "state": Simulation.new(scenario).inspect()}))
	old_backup.close()
	var newer := Simulation.new(scenario)
	newer.tick()
	var staged_new := FileAccess.open(promotion_path + ".next", FileAccess.WRITE)
	staged_new.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "content", "content": scenario}))
	for index in newer.history.size(): staged_new.store_line(Journal._encode({"schema": Journal.SCHEMA, "tick": index, "state": newer.history[index]}))
	staged_new.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "head", "state": newer.state}))
	staged_new.close()
	var promoted_recovery := Journal.load(promotion_path)
	expect(promoted_recovery.ok and promoted_recovery.history.size() == 2 and promoted_recovery.source == promotion_path + ".next", "complete_staging_preferred_to_old_backup")
	var failed_journal := Journal.new("res://missing-parent-%d/save.jsonl" % OS.get_process_id())
	expect(not failed_journal.save(saved_run).ok, "unavailable_storage_reported")
	var reset_run := restored
	var old_code: String = reset_run.state.code
	var old_observations: Array = reset_run.state.diary_observations.duplicate(true)
	reset_run.reset_loop()
	expect(reset_run.history.size() == 1 and reset_run.state.tick == 0, "reset_clears_leg_history")
	expect(reset_run.state.diary_observations == old_observations, "reset_retains_diary")
	expect(reset_run.state.current_knowledge.is_empty() and reset_run.state.flags.is_empty(), "reset_clears_loop_state")
	expect(reset_run.state.code != old_code and reset_run.state.loop_index == 1, "reset_generates_next_code")
	var loaded_reset := Simulation.new(scenario)
	expect(loaded_reset.restore_record(recovered), "reload_before_reset")
	loaded_reset.reset_loop()
	expect(loaded_reset.inspect() == reset_run.inspect(), "reset_after_reopen_matches")
	print("FOUNDATION_RESULT ", JSON.stringify({"passed": failures.is_empty(), "failures": failures}))
	quit(0 if failures.is_empty() else 1)
