extends SceneTree

const Content = preload("res://foundation/content.gd")
const Simulation = preload("res://foundation/run.gd")
const Journal = preload("res://foundation/journal.gd")
var failures: Array[String] = []

func _initialize() -> void:
	call_deferred("run")

func expect(condition: bool, name: String) -> void:
	if not condition:
		failures.append(name)
		printerr("FOUNDATION_FAIL ", name)

func expect_joy_button(action: String, button: int) -> void:
	var mapped := false
	for event in InputMap.action_get_events(action):
		if event is InputEventJoypadButton and event.button_index == button:
			mapped = true
	expect(mapped, "controller_mapping_" + action)

func run() -> void:
	expect_joy_button("wheel_confirm", JOY_BUTTON_RIGHT_SHOULDER)
	expect_joy_button("pause_game", JOY_BUTTON_BACK)
	expect_joy_button("cancel_action", JOY_BUTTON_B)
	expect_joy_button("reset_loop", JOY_BUTTON_START)
	var scenario := Content.scenario()
	expect(Content.validate(scenario).is_empty(), "valid_scenario")
	var broken := scenario.duplicate(true)
	broken.connections[0].to = "missing"
	expect(not Content.validate(broken).is_empty(), "broken_connection_rejected")
	expect(not Content.validate({"schema": 1, "version": "bad", "rooms": "oops"}).is_empty(), "malformed_content_rejected")
	var missing_coordinate := scenario.duplicate(true)
	missing_coordinate.actors[0].erase("x")
	expect(not Content.validate(missing_coordinate).is_empty(), "missing_actor_coordinate_rejected")
	var missing_amelia := scenario.duplicate(true)
	missing_amelia.actors.remove_at(0)
	expect(not Content.validate(missing_amelia).is_empty(), "required_actor_rejected")
	var first := Simulation.new(scenario)
	var second := Simulation.new(scenario)
	for index in range(150):
		var input := {"x": 1.0 if index < 90 else 0.0, "y": 0.0}
		var a := first.tick(input)
		var b := second.tick(input)
		expect(a == b, "deterministic_tick_%d" % index)
	expect(first.state.actors.amelia.room == "corridor", "direct_room_crossing")
	expect(first.state.actors.chatterbox.room == "service", "npc_returns_offscreen")
	expect(first.state.events is Array, "ordered_events_public")
	var action_run := Simulation.new(scenario)
	for i in range(48): action_run.tick({"x": 1.0})
	expect(action_run.available_interactions().size() == 1, "interaction_local")
	action_run.tick({"start_interaction": "valve"})
	expect(action_run.state.action.progress == 0, "action_start_serializable")
	for i in range(30): action_run.tick()
	expect(action_run.state.flags.get("close_valve", false), "action_effect_completed")
	expect(action_run.state.action.is_empty(), "action_finished")
	var unaltered := Simulation.new(scenario)
	for i in range(111): unaltered.tick()
	while action_run.state.tick < 111: action_run.tick()
	expect(unaltered.state.actors.guest.activity == "travel" and action_run.state.actors.guest.activity == "idle", "timed_effect_changes_npc_commitment")
	var completed_events := 0
	for i in range(35):
		action_run.tick()
		for event in action_run.events:
			if event.category == "action_completed": completed_events += 1
	expect(completed_events == 0, "effect_not_repeated")
	var cancelled := Simulation.new(scenario)
	for i in range(48): cancelled.tick({"x": 1.0})
	cancelled.tick({"start_interaction": "valve"})
	for i in range(10): cancelled.tick()
	cancelled.tick({"cancel_action": true})
	expect(cancelled.state.action.is_empty() and not cancelled.state.flags.get("close_valve", false), "interrupt_loses_progress")
	var moved_away := Simulation.new(scenario)
	for i in range(48): moved_away.tick({"x": 1.0})
	moved_away.tick({"start_interaction": "valve"})
	moved_away.tick({"x": -1.0})
	expect(moved_away.state.action.is_empty() and moved_away.events[0].category == "action_cancelled", "range_invalidation_cancels_immediately")
	var invalidated := Simulation.new(scenario)
	for i in range(48): invalidated.tick({"x": 1.0})
	invalidated.tick({"start_interaction": "valve"})
	for i in range(29): invalidated.tick()
	invalidated.tick({"x": -1.0, "cancel_action": true})
	expect(not invalidated.state.flags.get("close_valve", false), "simultaneous_cancel_before_complete")
	var boundary := Simulation.new(scenario)
	for i in range(48): boundary.tick({"x": 1.0})
	for i in range(Simulation.TICKS_PER_HOUR - 5 - 48): boundary.tick()
	boundary.tick({"start_interaction": "valve"})
	for i in range(30): boundary.tick()
	expect(boundary.state.flags.get("close_valve", false), "action_crosses_hour")
	var talk := Simulation.new(scenario)
	for i in range(10): talk.tick({"x": 1.0})
	expect(talk.dialogue_available(), "dialogue_local")
	talk.tick({"start_dialogue": true})
	expect(str(talk.state.dialogue.line).begins_with("Chatterbox:"), "first_speaker")
	expect(talk.state.diary_observations.size() == 1 and talk.state.current_knowledge.is_empty(), "observation_not_eligibility")
	talk.tick({"advance_dialogue": true})
	expect(talk.state.dialogue.remaining == Simulation.DIALOGUE_TICKS, "fixed_step_cost")
	for i in range(Simulation.DIALOGUE_TICKS): talk.tick()
	expect(str(talk.state.dialogue.line).begins_with("Amelia:"), "second_speaker")
	expect(talk.state.flags.guest_delay_ticks == 40 and talk.state.current_knowledge.has("guest_will_wait"), "world_command_once")
	var guest_before_visit: Dictionary = talk.state.actors.guest.duplicate(true)
	for i in range(110 - talk.state.tick): talk.tick()
	expect(talk.state.actors.guest == guest_before_visit, "dialogue_changes_later_schedule")
	var repeat_scenario := scenario.duplicate(true)
	repeat_scenario.commitments[0].at_tick = 1000
	var repeated := Simulation.new(repeat_scenario)
	for i in range(10): repeated.tick({"x": 1.0})
	for turn in range(2):
		repeated.tick({"start_dialogue": true})
		repeated.tick({"advance_dialogue": true})
		for i in range(Simulation.DIALOGUE_TICKS): repeated.tick()
		repeated.tick({"advance_dialogue": true})
		for i in range(Simulation.DIALOGUE_TICKS): repeated.tick()
	expect(repeated.state.flags.guest_delay_ticks == 40, "repeated_conversation_does_not_repeat_effect")
	var bad_dialogue := scenario.duplicate(true)
	bad_dialogue.dialogue = bad_dialogue.dialogue.replace("delay_guest(40)", "unknown_command(40)")
	expect(not Content.validate(bad_dialogue).is_empty(), "unknown_command_rejected")
	var bad_speaker := scenario.duplicate(true)
	bad_speaker.dialogue = bad_speaker.dialogue.replace("Amelia:", "UnknownActor:")
	expect(not Content.validate(bad_speaker).is_empty(), "missing_dialogue_actor_rejected")
	var history_run := Simulation.new(scenario)
	var observed: Array[Dictionary] = [history_run.inspect()]
	for i in range(130): observed.append(history_run.tick({"x": 1.0 if i < 90 else 0.0}))
	for i in [0, 1, 19, 20, 80, 90, 129, 130]:
		expect(history_run.inspect_at(i) == observed[i], "recorded_tick_%d" % i)
	var live_before := history_run.inspect()
	var old_snapshot := history_run.inspect_at(20)
	old_snapshot.actors.amelia.x = -1000.0
	expect(history_run.inspect() == live_before and history_run.inspect_at(20).actors.amelia.x != -1000.0, "scrub_is_read_only")
	expect(history_run.inspect_at(19).diagnostics.content_version == scenario.version, "recorded_provenance")
	var knowledge_before: Array = history_run.state.current_knowledge.duplicate(true)
	var remote_room_state := history_run.inspect_at(80)
	expect(remote_room_state.actors.guest.room == "corridor" and history_run.state.current_knowledge == knowledge_before, "offscreen_inspection_grants_no_knowledge")
	var event_run := Simulation.new(scenario)
	var event_state := event_run.step_next_event()
	expect(event_state.tick == 20 and event_state.events[0].category == "commitment", "next_event_stops_at_commitment")
	var branch_run := Simulation.new(scenario)
	for i in range(120): branch_run.tick()
	var old_past := branch_run.inspect_at(10)
	var old_future := branch_run.inspect_at(115)
	var invalid_edit := scenario.duplicate(true)
	invalid_edit.dialogue = "~ start\ndo missing_command()\n=> END"
	var invalid_result := branch_run.continue_with_content(invalid_edit, 10)
	expect(not invalid_result.ok and branch_run.state.tick == 120 and branch_run.inspect_at(115) == old_future, "invalid_edit_keeps_future")
	var compatible := scenario.duplicate(true)
	compatible.version = "two-room-2"
	compatible.dialogue = compatible.dialogue.replace("delay_guest(40)", "delay_guest(80)")
	var branch_result := branch_run.continue_with_content(compatible, 10)
	expect(branch_result.ok and branch_run.state.tick == 10 and branch_run.history.size() == 11, "historical_resume_truncates_future")
	expect(branch_run.inspect_at(10) == old_past, "historical_record_unchanged")
	branch_run.tick()
	expect(branch_run.state.content_version == "two-room-2" and branch_run.inspect_at(11).content_version == "two-room-2", "new_future_provenance")
	var reused_version := compatible.duplicate(true)
	reused_version.dialogue = reused_version.dialogue.replace("delay_guest(80)", "delay_guest(90)")
	expect(not branch_run.continue_with_content(reused_version).ok, "version_reuse_rejected")
	var active_dialogue := Simulation.new(scenario)
	for i in range(10): active_dialogue.tick({"x": 1.0})
	active_dialogue.tick({"start_dialogue": true})
	var incompatible_result := active_dialogue.continue_with_content(compatible)
	expect(not incompatible_result.ok and incompatible_result.restart and active_dialogue.state.dialogue.cursor == 0, "active_dialogue_requires_restart")
	var active_action := Simulation.new(scenario)
	for i in range(48): active_action.tick({"x": 1.0})
	active_action.tick({"start_interaction": "valve"})
	var changed_action := scenario.duplicate(true)
	changed_action.version = "changed-action"
	changed_action.interactions[0].duration_ticks = 50
	expect(active_action.continue_with_content(changed_action).restart, "active_action_requires_restart")
	var compatible_action := scenario.duplicate(true)
	compatible_action.version = "compatible-action"
	compatible_action.dialogue = compatible_action.dialogue.replace("coming soon", "arriving soon")
	var mid_action_tick: int = active_action.state.tick
	for i in range(8): active_action.tick()
	expect(active_action.continue_with_content(compatible_action, mid_action_tick).ok, "compatible_mid_action_resume")
	for i in range(30): active_action.tick()
	expect(active_action.state.flags.get("close_valve", false), "mid_action_resume_completes_once")
	var compatible_dialogue := scenario.duplicate(true)
	compatible_dialogue.version = "compatible-dialogue"
	compatible_dialogue.interactions[0].label = "Close valve"
	expect(active_dialogue.continue_with_content(compatible_dialogue).ok, "compatible_mid_dialogue_resume")
	active_dialogue.tick({"advance_dialogue": true})
	for i in range(Simulation.DIALOGUE_TICKS): active_dialogue.tick()
	expect(active_dialogue.state.flags.guest_delay_ticks == 40, "mid_dialogue_resume_command_once")
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path("res://build"))
	var save_path := "res://build/foundation-test-%d.jsonl" % OS.get_process_id()
	var journal := Journal.new(save_path)
	var branch_save := Journal.new(save_path + ".branch")
	expect(branch_save.save(branch_run).ok, "save_branched_history")
	var branch_loaded := Journal.load(branch_save.path)
	expect(branch_loaded.ok and branch_loaded.content_versions.has("two-room-1") and branch_loaded.content_versions.has("two-room-2"), "historical_content_provenance_persisted")
	var saved_run := Simulation.new(scenario)
	for i in range(10): saved_run.tick({"x": 1.0})
	saved_run.tick({"start_dialogue": true})
	saved_run.tick({"advance_dialogue": true})
	expect(journal.save(saved_run).ok, "save_pending_dialogue")
	var loaded := Journal.load(save_path)
	var restored := Simulation.new(scenario)
	expect(loaded.ok and restored.restore_record(loaded), "reload_pending_dialogue")
	expect(restored.inspect() == saved_run.inspect() and restored.history == saved_run.history, "reload_exact_state_and_history")
	for i in range(Simulation.DIALOGUE_TICKS):
		saved_run.tick()
		restored.tick()
	expect(restored.inspect() == saved_run.inspect() and restored.state.flags.guest_delay_ticks == 40, "reload_command_once")
	var saved_action := Simulation.new(scenario)
	for i in range(48): saved_action.tick({"x": 1.0})
	saved_action.tick({"start_interaction": "valve"})
	for i in range(7): saved_action.tick()
	var action_journal := Journal.new(save_path + ".action")
	expect(action_journal.save(saved_action).ok, "save_mid_action")
	var reloaded_action := Simulation.new(scenario)
	expect(reloaded_action.restore_record(Journal.load(action_journal.path)), "reload_mid_action")
	for i in range(23):
		saved_action.tick()
		reloaded_action.tick()
	expect(reloaded_action.inspect() == saved_action.inspect() and reloaded_action.state.flags.get("close_valve", false), "reloaded_action_completes_once")
	expect(journal.save(saved_run).ok, "append_new_ticks")
	var managed_path := save_path + ".managed"
	var managed := Simulation.new(scenario)
	managed.attach_journal(managed_path)
	expect(managed.persist().ok, "run_persists_initial_state")
	managed.tick({"x": 1.0})
	expect(managed.persist().ok, "run_persists_completed_tick")
	var reopened := Simulation.new(scenario)
	reopened.attach_journal(managed_path)
	expect(reopened.load_saved().ok and reopened.inspect() == managed.inspect() and reopened.history == managed.history, "run_reopens_history")
	var torn := FileAccess.open(save_path, FileAccess.READ_WRITE)
	torn.seek_end()
	torn.store_string("{bad tail")
	torn.close()
	var recovered := Journal.load(save_path)
	expect(recovered.ok and recovered.history.size() == saved_run.history.size(), "torn_tail_recovers_last_tick")
	var continued := Simulation.new(scenario)
	expect(continued.restore_record(recovered), "recover_into_simulation")
	var repair_journal := Journal.new(save_path)
	repair_journal.saved_count = 0
	continued.tick()
	expect(repair_journal.save(continued).ok, "repair_before_append")
	expect(Journal.load(save_path).history.size() == continued.history.size(), "reopen_after_repair")
	var unsupported_path := save_path + ".unsupported"
	var unsupported := FileAccess.open(unsupported_path, FileAccess.WRITE)
	unsupported.store_line(Journal._encode({"schema": 999, "kind": "content", "content": scenario}))
	unsupported.close()
	expect(not Journal.load(unsupported_path).ok, "unsupported_save_rejected")
	var malformed_path := save_path + ".malformed"
	var malformed := FileAccess.open(malformed_path, FileAccess.WRITE)
	malformed.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "content", "content": {"schema": 1, "version": "bad", "rooms": "oops"}}))
	malformed.close()
	expect(not Journal.load(malformed_path).ok, "malformed_save_rejected")
	var malformed_state_path := save_path + ".malformed-state"
	var malformed_state := FileAccess.open(malformed_state_path, FileAccess.WRITE)
	malformed_state.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "content", "content": scenario}))
	malformed_state.store_line(Journal._encode({"schema": Journal.SCHEMA, "tick": 0, "state": {"tick": 0, "actors": {}, "flags": {}, "action": {}, "dialogue": {}, "events": [], "diary_observations": [], "current_knowledge": [], "content_version": scenario.version}}))
	malformed_state.close()
	expect(not Journal.load(malformed_state_path).ok, "malformed_state_rejected")
	var malformed_nested_path := save_path + ".malformed-nested"
	var malformed_nested := FileAccess.open(malformed_nested_path, FileAccess.WRITE)
	malformed_nested.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "content", "content": scenario}))
	var bad_snapshot := Simulation.new(scenario).inspect()
	bad_snapshot.events = ["bad"]
	malformed_nested.store_line(Journal._encode({"schema": Journal.SCHEMA, "tick": 0, "state": bad_snapshot}))
	malformed_nested.close()
	expect(not Journal.load(malformed_nested_path).ok, "malformed_event_rejected")
	var malformed_action_path := save_path + ".malformed-action"
	var malformed_action := FileAccess.open(malformed_action_path, FileAccess.WRITE)
	malformed_action.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "content", "content": scenario}))
	var bad_action := Simulation.new(scenario).inspect()
	bad_action.action = {"id": "valve"}
	malformed_action.store_line(Journal._encode({"schema": Journal.SCHEMA, "tick": 0, "state": bad_action}))
	malformed_action.close()
	expect(not Journal.load(malformed_action_path).ok, "malformed_action_rejected")
	var staged_only_path := save_path + ".staged-only"
	var staged_only := FileAccess.open(staged_only_path + ".next", FileAccess.WRITE)
	staged_only.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "content", "content": scenario}))
	staged_only.store_line(Journal._encode({"schema": Journal.SCHEMA, "tick": 0, "state": Simulation.new(scenario).inspect()}))
	staged_only.close()
	expect(Journal.load(staged_only_path).ok, "staged_save_recovered")
	var promotion_path := save_path + ".promotion"
	var old_backup := FileAccess.open(promotion_path + ".bak", FileAccess.WRITE)
	old_backup.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "content", "content": scenario}))
	old_backup.store_line(Journal._encode({"schema": Journal.SCHEMA, "tick": 0, "state": Simulation.new(scenario).inspect()}))
	old_backup.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "head", "state": Simulation.new(scenario).inspect()}))
	old_backup.close()
	var newer := Simulation.new(scenario)
	newer.tick()
	var staged_new := FileAccess.open(promotion_path + ".next", FileAccess.WRITE)
	staged_new.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "content", "content": scenario}))
	for index in newer.history.size(): staged_new.store_line(Journal._encode({"schema": Journal.SCHEMA, "tick": index, "state": newer.history[index]}))
	staged_new.store_line(Journal._encode({"schema": Journal.SCHEMA, "kind": "head", "state": newer.state}))
	staged_new.close()
	var promoted_recovery := Journal.load(promotion_path)
	expect(promoted_recovery.ok and promoted_recovery.history.size() == 2 and promoted_recovery.source == promotion_path + ".next", "complete_staging_preferred_to_old_backup")
	var failed_journal := Journal.new("res://missing-parent-%d/save.jsonl" % OS.get_process_id())
	expect(not failed_journal.save(saved_run).ok, "unavailable_storage_reported")
	var reset_run := restored
	var old_code: String = reset_run.state.code
	var old_observations: Array = reset_run.state.diary_observations.duplicate(true)
	reset_run.reset_loop()
	expect(reset_run.history.size() == 1 and reset_run.state.tick == 0, "reset_clears_leg_history")
	expect(reset_run.state.diary_observations == old_observations, "reset_retains_diary")
	expect(reset_run.state.current_knowledge.is_empty() and reset_run.state.flags.is_empty(), "reset_clears_loop_state")
	expect(reset_run.state.code != old_code and reset_run.state.loop_index == 1, "reset_generates_next_code")
	var loaded_reset := Simulation.new(scenario)
	expect(loaded_reset.restore_record(recovered), "reload_before_reset")
	loaded_reset.reset_loop()
	expect(loaded_reset.inspect() == reset_run.inspect(), "reset_after_reopen_matches")
	print("FOUNDATION_RESULT ", JSON.stringify({"passed": failures.is_empty(), "failures": failures}))
	quit(0 if failures.is_empty() else 1)
