extends SceneTree
const Messages = preload("res://foundation/message_text.gd")
const Text = preload("res://localisation/source_text.gd")
const Locales = preload("res://foundation/localisation.gd")
const Sim = preload("res://mission1/simulation.gd")
const Save = preload("res://mission1/save.gd")
const Dialogue = preload("res://foundation/dialogue.gd")

func _initialize() -> void: call_deferred("checks")

func checks() -> void:
	var service := root.get_node("Localisation")
	var prefs := root.get_node("Preferences")
	var settings_path: String = prefs.settings_path
	prefs.settings_path = "res://build/localisation-settings.cfg"
	service.set_language("en")
	assert(Locales.choose_locale(["fr-FR", "en-GB"], ["en","fr"]) == "fr")
	assert(Locales.choose_locale(["de", "fr-CA"], ["en","fr"]) == "fr")
	assert(Locales.choose_locale(["en-US"], ["en","en_US"]) == "en_US")
	assert(Locales.choose_locale(["ja"]) == "en")
	prefs.language = "automatic"
	prefs.load_settings()
	assert(prefs.language == "en")
	assert(Messages.resolve(Messages.make_ref("UI_LOADING_PROGRESS",{"percent":37})) == "Loading the diary… 37%")
	assert(Messages.resolve(Messages.make_ref("MISSING",{},"Original")) == "Original")
	assert(Messages.plural("UI_GUEST_COUNT","UI_GUEST_COUNT_MANY",1) == "1 guest")
	assert(Messages.plural("UI_GUEST_COUNT","UI_GUEST_COUNT_MANY",3) == "3 guests")
	var message := Messages.capture(Text.MISSION1_BOY_REPORT_FOR_DUTY)
	var changed := message.duplicate(true)
	changed.revision = "older-source"
	assert(Messages.resolve(changed) == Text.MISSION1_BOY_REPORT_FOR_DUTY)
	var names: Array[String] = ["captain","guest"]
	var parsed := Dialogue.parse("~ start\ncaptain: Boy! Report for duty. [ID:MISSION1_BOY_REPORT_FOR_DUTY]\ndo delay_guest(10)\nguest: Thank you.\n=> END",names)
	assert(parsed.errors.is_empty())
	assert(parsed.steps[0].text == Text.MISSION1_BOY_REPORT_FOR_DUTY)
	assert(parsed.steps[0].message_id == "MISSION1_BOY_REPORT_FOR_DUTY")
	assert(parsed.steps[1].commands_before[0].ticks == 10)
	assert(Messages.capture("A new author line.",parsed.steps[0].message_id).id == "")
	var label := Label.new()
	root.add_child(label)
	Messages.assign(label,"text",Text.MISSION1_BOY_REPORT_FOR_DUTY)
	service.set_pseudolocalisation(true)
	assert(label.text != Text.MISSION1_BOY_REPORT_FOR_DUTY)
	assert(not label.text.contains("MISSION1_"))
	var progress := Messages.resolve(Messages.make_ref("UI_LOADING_PROGRESS",{"percent":37}))
	assert(progress.contains("37") and not progress.contains("{percent}"))
	assert(Messages.resolve(changed) == Text.MISSION1_BOY_REPORT_FOR_DUTY)
	assert(Messages.field({"text":Text.MISSION1_BOY_REPORT_FOR_DUTY},"text") == Text.MISSION1_BOY_REPORT_FOR_DUTY)
	service.set_pseudolocalisation(false)
	assert(label.text == Text.MISSION1_BOY_REPORT_FOR_DUTY)
	seed(42)
	var first := Sim.new(false)
	for index in 180: first.step()
	seed(42)
	service.set_pseudolocalisation(true)
	var second := Sim.new(false)
	for index in 180: second.step()
	assert(first.s == second.s)
	assert(first.history == second.history)
	assert(first.memory == second.memory)
	assert(second.notebook_text() != "\n\n".join(second.memory.notes))
	var before := second.history.duplicate(true)
	var journal := Save.new()
	var saved := journal.save_run(second,"res://build/localisation.journal")
	assert(saved.ok)
	var loaded := Save.load_saved("res://build/localisation.journal")
	assert(loaded.ok)
	var restored := Sim.new(false)
	restored.restore_record(loaded.data)
	assert(restored.history == JSON.parse_string(JSON.stringify(before)))
	assert(restored.notebook_text() == second.notebook_text())
	# Read an actual schema-4 journal, rather than inferring IDs from its wording.
	var wrapper: Dictionary = JSON.parse_string(FileAccess.get_file_as_string("res://build/localisation.journal").get_slice("\n",0))
	var batch: Dictionary = JSON.parse_string(wrapper.body)
	batch.schema = 4
	batch.memory.erase("note_records")
	for frame in batch.history + [batch.current]:
		frame.erase("message_ref")
		frame.erase("notice_ref")
		frame.dialogue.erase("text_ref")
		frame.dialogue.erase("name_ref")
	var legacy_body := JSON.stringify(batch)
	var legacy_file := FileAccess.open("res://build/localisation-legacy.journal",FileAccess.WRITE)
	legacy_file.store_line(JSON.stringify({"body":legacy_body,"sha256":legacy_body.sha256_text()}))
	legacy_file.close()
	var legacy_saved := Save.load_saved("res://build/localisation-legacy.journal")
	assert(legacy_saved.ok)
	var legacy_run := Sim.new(false)
	legacy_run.restore_record(legacy_saved.data)
	assert(legacy_run.notebook_text() == "\n\n".join(legacy_run.memory.notes))
	legacy_run.note("new_after_restore",Text.MISSION1_BOY_REPORT_FOR_DUTY)
	var mixed := Sim.new(false)
	mixed.restore_record({"current":legacy_run.s,"memory":legacy_run.memory,"history":legacy_run.history})
	assert(mixed.memory.note_records[-1].text_ref.id == "MISSION1_BOY_REPORT_FOR_DUTY")
	assert(mixed.notebook_text().contains("01:00"))
	# Legacy literal entries stay literal: no source-text matching during display.
	restored.memory.note_records = []
	assert(restored.notebook_text() == "\n\n".join(restored.memory.notes))
	var old_frame: Dictionary = first.history[0].duplicate(true)
	old_frame.erase("message_ref")
	assert(Messages.field(old_frame,"message") == old_frame.message)
	service.set_pseudolocalisation(false)
	label.queue_free()
	# A real second catalogue tests lookup separately from pseudo rendering.
	var french := Translation.new()
	french.locale = "fr"
	french.add_message("MISSION1_BOY_REPORT_FOR_DUTY","Au rapport !")
	TranslationServer.add_translation(french)
	TranslationServer.set_locale("fr")
	assert(Messages.resolve(message) == "Au rapport !")
	assert(Messages.resolve(changed) == Text.MISSION1_BOY_REPORT_FOR_DUTY)
	TranslationServer.remove_translation(french)
	service.set_language("automatic")
	prefs.settings_path = settings_path
	prefs.load_settings()
	print("LOCALISATION PASS: locales, override, plurals, references, authored edits, legacy text, history and deterministic timing")
	await preload("res://tests/shutdown.gd").finish(self)
