extends RefCounted
## Initial authored dialogue and message catalogue.
const SCENES := {
  "bag_thanks": "~ start\nguest: My suitcase! At last. Thank you.\n=> END",
  "spill_reply": "~ start\nguest: My suit! Do watch where you are going!\n=> END",
  "spill_apology": "~ start\namelia: I wanted to apologise about your drink, sir.\nguest: You ruined my suit. I have no interest in your excuses. Now leave me alone.\n=> END",
  "shove_reply": "~ start\nchandelier_guest: How dare you! What do you think you are doing?\n=> END",
  "nephew": "~ start\nchatterbox: Before you go, you must hear about my nephew.\nguest: Could it wait? They are serving drinks.\nchatterbox: He bought a motorcar. Without asking his mother!\nguest: How very rash.\nchatterbox: That is exactly what I said. Now, listen…\n=> END",
  "steam_help": "~ start\nchatterbox: Help! The steam has cut off the passage!\n=> END",
  "bags": "~ start\nguest: Where are my bags? I will not board without them!\ndock_sailor: I'll search the luggage, sir.\nguest: Brown leather. With my initials.\ndock_sailor: Stay here. I'll bring them over.\n=> END",
  "bags_waiting": "~ start\nguest: My brown suitcase is still missing. I'm waiting here.\n=> END",
  "captain_briefing": "~ start\ncaptain: Boy! Report for duty.\namelia: Yes, Captain.\ncaptain: Explore the ship and make sure our guests are comfortable. Help with their luggage, bring refreshments, and show them to their cabins.\namelia: Very good, Captain.\ncaptain: Passengers are coming aboard. Get to it.\n=> END",
  "directions": "~ start\nchandelier_guest: Which way to the Salon?\nporter: Up the centre stair, madam.\n=> END",
  "weather": "~ start\nchandelier_guest: A lovely evening for a departure.\nchatterbox: Provided the sea remembers its manners.\n=> END",
  "cabins": "~ start\nchatterbox: Are you settling into your cabin?\nguest: At last. I thought my luggage had taken its own holiday.\n=> END"
}
const TEXTS := {
  "Boy! Report for duty.": "Boy! Report for duty.",
  "Yes, Captain.": "Yes, Captain.",
  "Explore the ship and make sure our guests are comfortable. Help with their luggage, bring refreshments, and show them to their cabins.": "Explore the ship and make sure our guests are comfortable. Help with their luggage, bring refreshments, and show them to their cabins.",
  "Very good, Captain.": "Very good, Captain.",
  "Passengers are coming aboard. Get to it.": "Passengers are coming aboard. Get to it.",
  "A new posting. An unmooring party. What could possibly go wrong?": "A new posting. An unmooring party. What could possibly go wrong?",
  "Report for duty": "Report for duty",
  "Inspect luggage": "Inspect luggage",
  "Action interrupted. Unfinished progress lost.": "Action interrupted. Unfinished progress lost.",
  "The unmooring party has ended.": "The unmooring party has ended.",
  "I opened the cabin door.": "I opened the cabin door.",
  "I closed the cabin door.": "I closed the cabin door.",
  "The same monogram. He still refuses to board without this bag.": "The same monogram. He still refuses to board without this bag.",
  "A monogrammed suitcase tucked among the trunks.": "A monogrammed suitcase tucked among the trunks.",
  "I tucked the suitcase behind the baggage screen.": "I tucked the suitcase behind the baggage screen.",
  "I brought the suitcase back to its owner.": "I brought the suitcase back to its owner.",
  "My suitcase! At last. Thank you.": "My suitcase! At last. Thank you.",
  "Porter: The centre stair is only latched. Release the brass catch at its foot.": "Porter: The centre stair is only latched. Release the brass catch at its foot.",
  "I released the latch. The centre stair leads straight to the salon.": "I released the latch. The centre stair leads straight to the salon.",
  "Steam blocks the far room's normal exit. The talkative passenger is trapped.": "Steam blocks the far room's normal exit. The talkative passenger is trapped.",
  "The passenger collapsed behind the steam.": "The passenger collapsed behind the steam.",
  "Crew: A passenger needs help in the steam passage!": "Crew: A passenger needs help in the steam passage!",
  "The chandelier creaks and trembles above the guest.": "The chandelier creaks and trembles above the guest.",
  "The chandelier fell on the guest.": "The chandelier fell on the guest.",
  "The chandelier crashed onto the place where the guest had been standing.": "The chandelier crashed onto the place where the guest had been standing.",
  "The diary shivers.": "The diary shivers.",
  "You found the bag! Thank you, Boy. Saved me a search.": "You found the bag! Thank you, Boy. Saved me a search.",
  "The stair's brass catch is still here.": "The stair's brass catch is still here.",
  "I do wish they would get on with it. Such a wait!": "I do wish they would get on with it. Such a wait!",
  "Bump into guest": "Bump into guest",
  "Inspect glass": "Inspect glass",
  "Inspect wreckage": "Inspect wreckage",
  "My elbow caught the glass. His drink soaked his suit.": "My elbow caught the glass. His drink soaked his suit.",
  "My suit! Do watch where you are going!": "My suit! Do watch where you are going!",
  "A sharp chemical residue in the glass. The drink was poisoned; nothing here identifies who did it.": "A sharp chemical residue in the glass. The drink was poisoned; nothing here identifies who did it.",
  "I wanted to apologise about your drink, sir.": "I wanted to apologise about your drink, sir.",
  "You ruined my suit. I have no interest in your excuses. Now leave me alone.": "You ruined my suit. I have no interest in your excuses. Now leave me alone.",
  "I shoved the guest out from beneath the chandelier.": "I shoved the guest out from beneath the chandelier.",
  "How dare you! What do you think you are doing?": "How dare you! What do you think you are doing?",
  "She is dead, beneath the chandelier. Broken glass everywhere, and a snapped suspension pin.": "She is dead, beneath the chandelier. Broken glass everywhere, and a snapped suspension pin.",
  "Broken glass and a snapped suspension pin. Thank goodness I got her out of the way.": "Broken glass and a snapped suspension pin. Thank goodness I got her out of the way.",
  "The luggage owner is waiting at the bar.": "The luggage owner is waiting at the bar.",
  "The luggage owner has collapsed beside his glass.": "The luggage owner has collapsed beside his glass.",
  "The passenger lies motionless beyond the steam leak.": "The passenger lies motionless beyond the steam leak.",
  "The guest lies dead beneath the fallen chandelier.": "The guest lies dead beneath the fallen chandelier.",
  "The fallen chandelier lies in pieces. The guest is safe.": "The fallen chandelier lies in pieces. The guest is safe.",
  "The passenger leaves through the cleared steam passage.": "The passenger leaves through the cleared steam passage.",
  "The passenger emerges from the steam room.": "The passenger emerges from the steam room.",
  "An obscured hand tips something into the guest's glass.": "An obscured hand tips something into the guest's glass.",
  "The guest drank, then collapsed beside the poisoned glass.": "The guest drank, then collapsed beside the poisoned glass.",
  "Pressure must be running for the controls to respond.": "Pressure must be running for the controls to respond.",
  "Enter three digits, then press Commit. Clear starts your entry again.": "Enter three digits, then press Commit. Clear starts your entry again.",
  "Today's shutoff code is %s.": "Today's shutoff code is %s.",
  "Code rejected. Clear and try again.": "Code rejected. Clear and try again.",
  "I stopped the steam.": "I stopped the steam.",
  "Found it! Brown leather, just as you said.": "Found it! Brown leather, just as you said.",
  "Loop %d · Hour ": "Loop %d · Hour ",
  "The passage is clear. The passenger starts towards the exit.": "The passage is clear. The passenger starts towards the exit.",
  "Content applied": "Content applied",
  "Before you go, you must hear about my nephew.": "Before you go, you must hear about my nephew.",
  "Could it wait? They are serving drinks.": "Could it wait? They are serving drinks.",
  "He bought a motorcar. Without asking his mother!": "He bought a motorcar. Without asking his mother!",
  "How very rash.": "How very rash.",
  "That is exactly what I said. Now, listen…": "That is exactly what I said. Now, listen…",
  "Help! The steam has cut off the passage!": "Help! The steam has cut off the passage!",
  "Where are my bags? I will not board without them!": "Where are my bags? I will not board without them!",
  "I'll search the luggage, sir.": "I'll search the luggage, sir.",
  "Brown leather. With my initials.": "Brown leather. With my initials.",
  "Stay here. I'll bring them over.": "Stay here. I'll bring them over.",
  "My brown suitcase is still missing. I'm waiting here.": "My brown suitcase is still missing. I'm waiting here.",
  "Which way to the Salon?": "Which way to the Salon?",
  "Up the centre stair, madam.": "Up the centre stair, madam.",
  "A lovely evening for a departure.": "A lovely evening for a departure.",
  "Provided the sea remembers its manners.": "Provided the sea remembers its manners.",
  "Are you settling into your cabin?": "Are you settling into your cabin?",
  "At last. I thought my luggage had taken its own holiday.": "At last. I thought my luggage had taken its own holiday.",
  "Sparkling water": "Sparkling water",
  "Mr. Felix Harcourt": "Mr. Felix Harcourt",
  "Lemonade, please, Boy.": "Lemonade, please, Boy.",
  "Excellent lemonade, Boy. Thank you.": "Excellent lemonade, Boy. Thank you.",
  "I asked for lemonade, Boy. Do try to remember.": "I asked for lemonade, Boy. Do try to remember.",
  "Miss Evelyn Vale": "Miss Evelyn Vale",
  "Sparkling water, please, Boy.": "Sparkling water, please, Boy.",
  "Just what I wanted. Thank you, Boy.": "Just what I wanted. Thank you, Boy.",
  "That isn't sparkling water. Perhaps someone else ordered it?": "That isn't sparkling water. Perhaps someone else ordered it?",
  "Mrs. Mabel Pritchard": "Mrs. Mabel Pritchard",
  "A proper cup of tea, please, Boy.": "A proper cup of tea, please, Boy.",
  "Lovely. A proper cup of tea. Thank you, Boy.": "Lovely. A proper cup of tea. Thank you, Boy.",
  "Tea, Boy. A proper cup of tea.": "Tea, Boy. A proper cup of tea.",
  "Inspect nameplate": "Inspect nameplate",
  "Ask about drinks": "Ask about drinks",
  "Give cabin directions": "Give cabin directions",
  "Cabin %d — %s": "Cabin %d — %s",
  "Cabin %d. Thank you, Boy.": "Cabin %d. Thank you, Boy.",
  "Cabin %d, you say? Very well, Boy.": "Cabin %d, you say? Very well, Boy.",
  "This is %s's cabin! You sent me to the wrong door, Boy.": "This is %s's cabin! You sent me to the wrong door, Boy.",
  "%s? How curious, Boy. I seem to have become somebody else.": "%s? How curious, Boy. I seem to have become somebody else.",
  "The plate says %s! Read the names properly next time, Boy.": "The plate says %s! Read the names properly next time, Boy.",
  "Oh, how dreadful. That poor woman.": "Oh, how dreadful. That poor woman.",
  "She was standing here a moment ago. Someone must fetch the captain.": "She was standing here a moment ago. Someone must fetch the captain.",
  "He's dead! What a terrible end to the party.": "He's dead! What a terrible end to the party.",
  "He was rather a bore. Still, nobody deserves this.": "He was rather a bore. Still, nobody deserves this.",
  "She's dead. I'll stay with her until help arrives.": "She's dead. I'll stay with her until help arrives.",
  "Why has this been switched off?": "Why has this been switched off?",
  "I wonder what I should do?": "I wonder what I should do?",
  "Hurry up and wait…": "Hurry up and wait…",
  "Something has changed in the diary. I should open it.": "Something has changed in the diary. I should open it.",
  "What a tragedy. Hmmm, my diary is shaking, I feel like I should take a look.": "What a tragedy. Hmmm, my diary is shaking, I feel like I should take a look.",
  "Tap Highlight": "Tap Highlight",
  "A — Highlight": "A — Highlight",
  "Hold B — Wait": "Hold B — Wait",
  "Y — Open diary": "Y — Open diary",
  "H — Highlight": "H — Highlight",
  "Hold F — Wait": "Hold F — Wait",
  "Tab — Open diary": "Tab — Open diary"
}
