extends RefCounted
## Generated by tools/localisation.py --generate. Edit the CSV catalogues.
const MISSION1_BOY = "Boy"
const MISSION1_MR_FELIX_HARCOURT = "Mr. Felix Harcourt"
const MISSION1_MISS_EVELYN_VALE = "Miss Evelyn Vale"
const MISSION1_MRS_MABEL_PRITCHARD = "Mrs. Mabel Pritchard"
const MISSION1_SAILOR = "Sailor"
const MISSION1_CAPTAIN = "Captain"
const MISSION1_PORTER = "Porter"
const MISSION1_GUEST = "Guest"
const MISSION1_UNSUPPORTED_MISSION_1_CONTENT_SCHEMA = "Unsupported Mission 1 content schema"
const MISSION1_S_MUST_BE_AN_OBJECT = "%s must be an object"
const MISSION1_S_MUST_BE_A_LIST = "%s must be a list"
const MISSION1_THE_PLAYER_ENTITY_AMELIA_IS_REQUIRED = "The player entity amelia is required"
const MISSION1_MISSION_1_OPERATIONS_STILL_REFERENCE_CHARACTER = "Mission 1 operations still reference character "
const MISSION1_ROOM_S_NEEDS_DIMENSIONS_AND_COLLISION_CELLS = "Room %s needs dimensions and collision cells"
const MISSION1_ROOM_S_DIMENSIONS_MUST_BE_1_10000 = "Room %s dimensions must be 1–10000"
const MISSION1_ROOM_S_COLLISION_CELLS_MUST_USE_INTEGER_X_Y_KEYS_AND_TRUE_VALUES = "Room %s collision cells must use integer x,y keys and true values"
const MISSION1_ROOM_S_BACKGROUND_ASSET_IS_MISSING = "Room %s background asset is missing"
const MISSION1_TEMPLATE_S_HAS_AN_INVALID_ENTITY_KIND = "Template %s has an invalid entity kind"
const MISSION1_TEMPLATE_S_HAS_INVALID_STATE_RULES = "Template %s has invalid state rules"
const MISSION1_TEMPLATE_S_STATES_MUST_BE_OBJECTS = "Template %s states must be objects"
const MISSION1_TEMPLATE_S_HAS_AN_INVALID_TRANSITION = "Template %s has an invalid transition"
const MISSION1_ENTITY_S_NEEDS_A_POSITION_AND_OVERRIDES = "Entity %s needs a position and overrides"
const MISSION1_ENTITY_S_TEMPLATE_IS_MISSING = "Entity %s template is missing"
const MISSION1_ENTITY_S_ROOM_IS_MISSING = "Entity %s room is missing"
const MISSION1_ENTITY_S_HAS_AN_UNKNOWN_APPEARANCE = "Entity %s has an unknown appearance"
const MISSION1_ENTITY_S_STATE_OVERRIDES_ARE_INVALID = "Entity %s state overrides are invalid"
const MISSION1_ENTITY_S_TRANSITION_TARGET_IS_MISSING = "Entity %s transition target is missing"
const MISSION1_ENTITY_S_INTERACTIONS_MUST_BE_A_LIST = "Entity %s interactions must be a list"
const MISSION1_ENTITY_S_HAS_AN_INVALID_INTERACTION_POSITION = "Entity %s has an invalid interaction position"
const MISSION1_INTERACTION_DURATION_MUST_BE_POSITIVE = "Interaction duration must be positive"
const MISSION1_ENTITY_S_INTERACTION_IS_BLOCKED_BY_AUTHORED_COLLISION = "Entity %s interaction is blocked by authored collision"
const MISSION1_A_ROOM_CONNECTION_HAS_MISSING_ENDPOINTS = "A room connection has missing endpoints"
const MISSION1_CONNECTION_ENDPOINT_IN_S_IS_BLOCKED = "Connection endpoint in %s is blocked"
const MISSION1_SCHEDULE_S_ACTOR_IS_MISSING = "Schedule %s actor is missing"
const MISSION1_SCHEDULE_S_NEEDS_COMMITMENTS = "Schedule %s needs commitments"
const MISSION1_SCHEDULE_S_HAS_AN_INVALID_COMMITMENT = "Schedule %s has an invalid commitment"
const MISSION1_SCHEDULE_S_NEEDS_AN_ORIGIN_AND_STAGES = "Schedule %s needs an origin and stages"
const MISSION1_SCHEDULE_S_HAS_AN_INVALID_STAGE = "Schedule %s has an invalid stage"
const MISSION1_STORYLET_NEEDS_AN_ID_CONDITIONS_AND_EFFECTS = "Storylet needs an ID, conditions and effects"
const MISSION1_STORYLET_S_HAS_INVALID_TIMING_OR_PARTICIPANTS = "Storylet %s has invalid timing or participants"
const MISSION1_STORYLET_S_SCENE_IS_MISSING = "Storylet %s scene is missing"
const MISSION1_STORYLET_S_ACTOR_S_IS_MISSING = "Storylet %s actor %s is missing"
const MISSION1_STORYLET_S_HAS_AN_UNSUPPORTED_COMMAND = "Storylet %s has an unsupported command"
const MISSION1_UNSUPPORTED_MISSION_1_OPERATION = "Unsupported Mission 1 operation"
const MISSION1_FLAG_COMMAND_NEEDS_A_KEY = "Flag command needs a key"
const MISSION1_PROP_COMMAND_NEEDS_AN_ENTITY_AND_STATE = "Prop command needs an entity and state"
const MISSION1_SAY_COMMAND_NEEDS_AN_ACTOR_AND_TEXT = "Say command needs an actor and text"
const MISSION1_NOTE_COMMAND_NEEDS_A_KEY_AND_TEXT = "Note command needs a key and text"
const MISSION1_STORYLET_CONDITIONS_MUST_BE_OBJECTS = "Storylet conditions must be objects"
const MISSION1_TIMING_S_MUST_BE_WITHIN_THE_LEG = "Timing %s must be within the leg"
const MISSION1_ASSET_S_S = "Asset %s: %s"
const MISSION1_SCENE_S_MUST_BE_SOURCE_TEXT = "Scene %s must be source text"
const MISSION1_ENTITY_S_INTERACTION_HAS_NO_ROUTE_FROM_THE_PLAYER_START = "Entity %s interaction has no route from the player start"
const MISSION1_SCHEDULE_S_DESTINATION_HAS_NO_CONNECTED_ROUTE = "Schedule %s destination has no connected route"
const MISSION1_CONDITIONS_MUST_BE_A_LIST = "Conditions must be a list"
const MISSION1_CONDITION_MUST_BE_AN_OBJECT = "Condition must be an object"
const MISSION1_UNKNOWN_CONDITION_USE_FLAG_HAS_FLAG_ACTOR_PROP_SAFE_DEAD_OR_DISTA = "Unknown condition; use flag, has_flag, actor, prop, safe, dead or distance"
const MISSION1_CONDITION_REFERENCES_MISSING_ENTITY = "Condition references missing entity "
const MISSION1_DISTANCE_CONDITION_NEEDS_TWO_ENTITIES_AND_A_MAXIMUM_DISTANCE = "Distance condition needs two entities and a maximum distance"
const MISSION1_EFFECTS_MUST_BE_A_LIST = "Effects must be a list"
const MISSION1_EFFECT_MUST_BE_AN_OBJECT = "Effect must be an object"
const MISSION1_FLAG_EFFECT_NEEDS_A_KEY = "Flag effect needs a key"
const MISSION1_PROP_EFFECT_NEEDS_AN_ENTITY_AND_STATE = "Prop effect needs an entity and state"
const MISSION1_PROP_EFFECT_REFERENCES_AN_UNKNOWN_STATE = "Prop effect references an unknown state"
const MISSION1_SAY_EFFECT_NEEDS_AN_ACTOR_AND_TEXT = "Say effect needs an actor and text"
const MISSION1_NOTE_EFFECT_NEEDS_A_KEY_AND_TEXT = "Note effect needs a key and text"
const MISSION1_UNKNOWN_MISSION_1_OPERATION = "Unknown Mission 1 operation"
const MISSION1_UNKNOWN_EFFECT_COMMAND = "Unknown effect command"
const MISSION1_MY_SUITCASE_AT_LAST_THANK_YOU = "My suitcase! At last. Thank you."
const MISSION1_MY_SUIT_DO_WATCH_WHERE_YOU_ARE_GOING = "My suit! Do watch where you are going!"
const MISSION1_I_WANTED_TO_APOLOGISE_ABOUT_YOUR_DRINK_SIR = "I wanted to apologise about your drink, sir."
const MISSION1_YOU_RUINED_MY_SUIT_I_HAVE_NO_INTEREST_IN_YOUR_EXCUSES_NOW_LEAVE_M = "You ruined my suit. I have no interest in your excuses. Now leave me alone."
const MISSION1_HOW_DARE_YOU_WHAT_DO_YOU_THINK_YOU_ARE_DOING = "How dare you! What do you think you are doing?"
const MISSION1_BEFORE_YOU_GO_YOU_MUST_HEAR_ABOUT_MY_NEPHEW = "Before you go, you must hear about my nephew."
const MISSION1_COULD_IT_WAIT_THEY_ARE_SERVING_DRINKS = "Could it wait? They are serving drinks."
const MISSION1_HE_BOUGHT_A_MOTORCAR_WITHOUT_ASKING_HIS_MOTHER = "He bought a motorcar. Without asking his mother!"
const MISSION1_HOW_VERY_RASH = "How very rash."
const MISSION1_THAT_IS_EXACTLY_WHAT_I_SAID_NOW_LISTEN = "That is exactly what I said. Now, listen…"
const MISSION1_HELP_THE_STEAM_HAS_CUT_OFF_THE_PASSAGE = "Help! The steam has cut off the passage!"
const MISSION1_WHERE_ARE_MY_BAGS_I_WILL_NOT_BOARD_WITHOUT_THEM = "Where are my bags? I will not board without them!"
const MISSION1_I_LL_SEARCH_THE_LUGGAGE_SIR = "I'll search the luggage, sir."
const MISSION1_BROWN_LEATHER_WITH_MY_INITIALS = "Brown leather. With my initials."
const MISSION1_STAY_HERE_I_LL_BRING_THEM_OVER = "Stay here. I'll bring them over."
const MISSION1_MY_BROWN_SUITCASE_IS_STILL_MISSING_I_M_WAITING_HERE = "My brown suitcase is still missing. I'm waiting here."
const MISSION1_BOY_REPORT_FOR_DUTY = "Boy! Report for duty."
const MISSION1_YES_CAPTAIN = "Yes, Captain."
const MISSION1_EXPLORE_THE_SHIP_AND_MAKE_SURE_OUR_GUESTS_ARE_COMFORTABLE_HELP_WI = "Explore the ship and make sure our guests are comfortable. Help with their luggage, bring refreshments, and show them to their cabins."
const MISSION1_VERY_GOOD_CAPTAIN = "Very good, Captain."
const MISSION1_PASSENGERS_ARE_COMING_ABOARD_GET_TO_IT = "Passengers are coming aboard. Get to it."
const MISSION1_WHICH_WAY_TO_THE_SALON = "Which way to the Salon?"
const MISSION1_UP_THE_CENTRE_STAIR_MADAM = "Up the centre stair, madam."
const MISSION1_A_LOVELY_EVENING_FOR_A_DEPARTURE = "A lovely evening for a departure."
const MISSION1_PROVIDED_THE_SEA_REMEMBERS_ITS_MANNERS = "Provided the sea remembers its manners."
const MISSION1_ARE_YOU_SETTLING_INTO_YOUR_CABIN = "Are you settling into your cabin?"
const MISSION1_AT_LAST_I_THOUGHT_MY_LUGGAGE_HAD_TAKEN_ITS_OWN_HOLIDAY = "At last. I thought my luggage had taken its own holiday."
const MISSION1_A_NEW_POSTING_AN_UNMOORING_PARTY_WHAT_COULD_POSSIBLY_GO_WRONG = "A new posting. An unmooring party. What could possibly go wrong?"
const MISSION1_REPORT_FOR_DUTY = "Report for duty"
const MISSION1_INSPECT_LUGGAGE = "Inspect luggage"
const MISSION1_ACTION_INTERRUPTED_UNFINISHED_PROGRESS_LOST = "Action interrupted. Unfinished progress lost."
const MISSION1_THE_UNMOORING_PARTY_HAS_ENDED = "The unmooring party has ended."
const MISSION1_I_OPENED_THE_CABIN_DOOR = "I opened the cabin door."
const MISSION1_I_CLOSED_THE_CABIN_DOOR = "I closed the cabin door."
const MISSION1_THE_SAME_MONOGRAM_HE_STILL_REFUSES_TO_BOARD_WITHOUT_THIS_BAG = "The same monogram. He still refuses to board without this bag."
const MISSION1_A_MONOGRAMMED_SUITCASE_TUCKED_AMONG_THE_TRUNKS = "A monogrammed suitcase tucked among the trunks."
const MISSION1_I_TUCKED_THE_SUITCASE_BEHIND_THE_BAGGAGE_SCREEN = "I tucked the suitcase behind the baggage screen."
const MISSION1_I_BROUGHT_THE_SUITCASE_BACK_TO_ITS_OWNER = "I brought the suitcase back to its owner."
const MISSION1_PORTER_THE_CENTRE_STAIR_IS_ONLY_LATCHED_RELEASE_THE_BRASS_CATCH_A = "Porter: The centre stair is only latched. Release the brass catch at its foot."
const MISSION1_I_RELEASED_THE_LATCH_THE_CENTRE_STAIR_LEADS_STRAIGHT_TO_THE_SALON = "I released the latch. The centre stair leads straight to the salon."
const MISSION1_STEAM_BLOCKS_THE_FAR_ROOM_S_NORMAL_EXIT_THE_TALKATIVE_PASSENGER_I = "Steam blocks the far room's normal exit. The talkative passenger is trapped."
const MISSION1_THE_PASSENGER_COLLAPSED_BEHIND_THE_STEAM = "The passenger collapsed behind the steam."
const MISSION1_CREW_A_PASSENGER_NEEDS_HELP_IN_THE_STEAM_PASSAGE = "Crew: A passenger needs help in the steam passage!"
const MISSION1_THE_CHANDELIER_CREAKS_AND_TREMBLES_ABOVE_THE_GUEST = "The chandelier creaks and trembles above the guest."
const MISSION1_THE_CHANDELIER_FELL_ON_THE_GUEST = "The chandelier fell on the guest."
const MISSION1_THE_CHANDELIER_CRASHED_ONTO_THE_PLACE_WHERE_THE_GUEST_HAD_BEEN_ST = "The chandelier crashed onto the place where the guest had been standing."
const MISSION1_THE_DIARY_SHIVERS = "The diary shivers."
const MISSION1_YOU_FOUND_THE_BAG_THANK_YOU_BOY_SAVED_ME_A_SEARCH = "You found the bag! Thank you, Boy. Saved me a search."
const MISSION1_THE_STAIR_S_BRASS_CATCH_IS_STILL_HERE = "The stair's brass catch is still here."
const MISSION1_I_DO_WISH_THEY_WOULD_GET_ON_WITH_IT_SUCH_A_WAIT = "I do wish they would get on with it. Such a wait!"
const MISSION1_BUMP_INTO_GUEST = "Bump into guest"
const MISSION1_INSPECT_GLASS = "Inspect glass"
const MISSION1_INSPECT_WRECKAGE = "Inspect wreckage"
const MISSION1_MY_ELBOW_CAUGHT_THE_GLASS_HIS_DRINK_SOAKED_HIS_SUIT = "My elbow caught the glass. His drink soaked his suit."
const MISSION1_A_SHARP_CHEMICAL_RESIDUE_IN_THE_GLASS_THE_DRINK_WAS_POISONED_NOTH = "A sharp chemical residue in the glass. The drink was poisoned; nothing here identifies who did it."
const MISSION1_I_SHOVED_THE_GUEST_OUT_FROM_BENEATH_THE_CHANDELIER = "I shoved the guest out from beneath the chandelier."
const MISSION1_SHE_IS_DEAD_BENEATH_THE_CHANDELIER_BROKEN_GLASS_EVERYWHERE_AND_A = "She is dead, beneath the chandelier. Broken glass everywhere, and a snapped suspension pin."
const MISSION1_BROKEN_GLASS_AND_A_SNAPPED_SUSPENSION_PIN_THANK_GOODNESS_I_GOT_HE = "Broken glass and a snapped suspension pin. Thank goodness I got her out of the way."
const MISSION1_THE_LUGGAGE_OWNER_IS_WAITING_AT_THE_BAR = "The luggage owner is waiting at the bar."
const MISSION1_THE_LUGGAGE_OWNER_HAS_COLLAPSED_BESIDE_HIS_GLASS = "The luggage owner has collapsed beside his glass."
const MISSION1_THE_PASSENGER_LIES_MOTIONLESS_BEYOND_THE_STEAM_LEAK = "The passenger lies motionless beyond the steam leak."
const MISSION1_THE_GUEST_LIES_DEAD_BENEATH_THE_FALLEN_CHANDELIER = "The guest lies dead beneath the fallen chandelier."
const MISSION1_THE_FALLEN_CHANDELIER_LIES_IN_PIECES_THE_GUEST_IS_SAFE = "The fallen chandelier lies in pieces. The guest is safe."
const MISSION1_THE_PASSENGER_LEAVES_THROUGH_THE_CLEARED_STEAM_PASSAGE = "The passenger leaves through the cleared steam passage."
const MISSION1_THE_PASSENGER_EMERGES_FROM_THE_STEAM_ROOM = "The passenger emerges from the steam room."
const MISSION1_AN_OBSCURED_HAND_TIPS_SOMETHING_INTO_THE_GUEST_S_GLASS = "An obscured hand tips something into the guest's glass."
const MISSION1_THE_GUEST_DRANK_THEN_COLLAPSED_BESIDE_THE_POISONED_GLASS = "The guest drank, then collapsed beside the poisoned glass."
const MISSION1_PRESSURE_MUST_BE_RUNNING_FOR_THE_CONTROLS_TO_RESPOND = "Pressure must be running for the controls to respond."
const MISSION1_ENTER_THREE_DIGITS_THEN_PRESS_COMMIT_CLEAR_STARTS_YOUR_ENTRY_AGAI = "Enter three digits, then press Commit. Clear starts your entry again."
const MISSION1_TODAY_S_SHUTOFF_CODE_IS_S = "Today's shutoff code is %s."
const MISSION1_CODE_REJECTED_CLEAR_AND_TRY_AGAIN = "Code rejected. Clear and try again."
const MISSION1_I_STOPPED_THE_STEAM = "I stopped the steam."
const MISSION1_FOUND_IT_BROWN_LEATHER_JUST_AS_YOU_SAID = "Found it! Brown leather, just as you said."
const MISSION1_LOOP_D_HOUR = "Loop %d · Hour "
const MISSION1_THE_PASSAGE_IS_CLEAR_THE_PASSENGER_STARTS_TOWARDS_THE_EXIT = "The passage is clear. The passenger starts towards the exit."
const MISSION1_CONTENT_APPLIED = "Content applied"
const MISSION1_SPARKLING_WATER = "Sparkling water"
const MISSION1_LEMONADE_PLEASE_BOY = "Lemonade, please, Boy."
const MISSION1_EXCELLENT_LEMONADE_BOY_THANK_YOU = "Excellent lemonade, Boy. Thank you."
const MISSION1_I_ASKED_FOR_LEMONADE_BOY_DO_TRY_TO_REMEMBER = "I asked for lemonade, Boy. Do try to remember."
const MISSION1_SPARKLING_WATER_PLEASE_BOY = "Sparkling water, please, Boy."
const MISSION1_JUST_WHAT_I_WANTED_THANK_YOU_BOY = "Just what I wanted. Thank you, Boy."
const MISSION1_THAT_ISN_T_SPARKLING_WATER_PERHAPS_SOMEONE_ELSE_ORDERED_IT = "That isn't sparkling water. Perhaps someone else ordered it?"
const MISSION1_A_PROPER_CUP_OF_TEA_PLEASE_BOY = "A proper cup of tea, please, Boy."
const MISSION1_LOVELY_A_PROPER_CUP_OF_TEA_THANK_YOU_BOY = "Lovely. A proper cup of tea. Thank you, Boy."
const MISSION1_TEA_BOY_A_PROPER_CUP_OF_TEA = "Tea, Boy. A proper cup of tea."
const MISSION1_INSPECT_NAMEPLATE = "Inspect nameplate"
const MISSION1_ASK_ABOUT_DRINKS = "Ask about drinks"
const MISSION1_GIVE_CABIN_DIRECTIONS = "Give cabin directions"
const MISSION1_CABIN_D_S = "Cabin %d — %s"
const MISSION1_CABIN_D_THANK_YOU_BOY = "Cabin %d. Thank you, Boy."
const MISSION1_CABIN_D_YOU_SAY_VERY_WELL_BOY = "Cabin %d, you say? Very well, Boy."
const MISSION1_THIS_IS_S_S_CABIN_YOU_SENT_ME_TO_THE_WRONG_DOOR_BOY = "This is %s's cabin! You sent me to the wrong door, Boy."
const MISSION1_S_HOW_CURIOUS_BOY_I_SEEM_TO_HAVE_BECOME_SOMEBODY_ELSE = "%s? How curious, Boy. I seem to have become somebody else."
const MISSION1_THE_PLATE_SAYS_S_READ_THE_NAMES_PROPERLY_NEXT_TIME_BOY = "The plate says %s! Read the names properly next time, Boy."
const MISSION1_OH_HOW_DREADFUL_THAT_POOR_WOMAN = "Oh, how dreadful. That poor woman."
const MISSION1_SHE_WAS_STANDING_HERE_A_MOMENT_AGO_SOMEONE_MUST_FETCH_THE_CAPTAIN = "She was standing here a moment ago. Someone must fetch the captain."
const MISSION1_HE_S_DEAD_WHAT_A_TERRIBLE_END_TO_THE_PARTY = "He's dead! What a terrible end to the party."
const MISSION1_HE_WAS_RATHER_A_BORE_STILL_NOBODY_DESERVES_THIS = "He was rather a bore. Still, nobody deserves this."
const MISSION1_SHE_S_DEAD_I_LL_STAY_WITH_HER_UNTIL_HELP_ARRIVES = "She's dead. I'll stay with her until help arrives."
const MISSION1_WHY_HAS_THIS_BEEN_SWITCHED_OFF = "Why has this been switched off?"
const MISSION1_I_WONDER_WHAT_I_SHOULD_DO = "I wonder what I should do?"
const MISSION1_HURRY_UP_AND_WAIT = "Hurry up and wait…"
const MISSION1_SOMETHING_HAS_CHANGED_IN_THE_DIARY_I_SHOULD_OPEN_IT = "Something has changed in the diary. I should open it."
const MISSION1_WHAT_A_TRAGEDY_HMMM_MY_DIARY_IS_SHAKING_I_FEEL_LIKE_I_SHOULD_TAKE = "What a tragedy. Hmmm, my diary is shaking, I feel like I should take a look."
const MISSION1_TAP_HIGHLIGHT = "Tap Highlight"
const MISSION1_A_HIGHLIGHT = "A — Highlight"
const MISSION1_HOLD_B_WAIT = "Hold B — Wait"
const MISSION1_Y_OPEN_DIARY = "Y — Open diary"
const MISSION1_H_HIGHLIGHT = "H — Highlight"
const MISSION1_HOLD_F_WAIT = "Hold F — Wait"
const MISSION1_TAB_OPEN_DIARY = "Tab — Open diary"
const MISSION1_TIME_WINDOW = "time window"
const MISSION1_NOT_ALREADY_COMPLETED = "not already completed"
const MISSION1_PARTICIPANT = "participant "
const MISSION1_RESTART_REQUIRED_ACTIVE_ENTITY_S_WAS_REMOVED = "Restart required: active entity %s was removed"
const MISSION1_RESTART_REQUIRED_S_OCCUPIES_CHANGED_COLLISION_GEOMETRY = "Restart required: %s occupies changed collision geometry"
const MISSION1_RESTART_REQUIRED_S_STARTING_PLACEMENT_CHANGED = "Restart required: %s starting placement changed"
const MISSION1_RESTART_REQUIRED_ACTIVE_SCENE_S_CHANGED = "Restart required: active scene %s changed"
const MISSION1_RESTART_REQUIRED_ACTIVE_PARTICIPANT_S_CHANGED = "Restart required: active participant %s changed"
const MISSION1_THOUGHT = "Thought"
const MISSION1_UNKNOWN_MISSION_1_SOUND_CUE_S = "Unknown Mission 1 sound cue: %s"
const MISSION1_CABIN_D = "Cabin %d"
const MISSION1_BACK = "Back"
const MISSION1_GET = "Get "
const MISSION1_RETURN_DRINK = "Return drink"
const MISSION1_PREFERS = "Prefers "
const MISSION1_OFFER = "Offer "
const MISSION1_VOYAGE_NOTEBOOK = "VOYAGE NOTEBOOK"
const MISSION1_THE_VOYAGE = "THE VOYAGE"
const MISSION1_OBSERVATIONS_FROM_THE_CURRENT_VOYAGE_RECORDED_AS_THEY_HAPPEN = "Observations from the current voyage, recorded as they happen."
const MISSION1_CLOSE_DIARY_S_S = "Close diary (%s / %s)"
const MISSION1_TURN_BACK_TO_THE_START_R = "Turn back to the start (R)"
const MISSION1_TURN_THE_PAGE = "Turn the Page"
const MISSION1_RETURN_TO_MAIN_MENU = "Return to main menu"
const MISSION1_PREVIOUS = "‹ Previous"
const MISSION1_NEXT = "Next ›"
const MISSION1_ACTION_CANCELLED = "Action cancelled."
const MISSION1_MISSION_D = "Mission %d  ·  "
const MISSION1_ALL_ABOARD = "All Aboard  ·  "
const MISSION1_THE_PAGES_TURN_BACKWARDS_R_TO_SKIP = "The pages turn backwards…  R to skip"
const MISSION1_NEARBY_ACTIONS_RIGHT_STICK_TO_CHOOSE_X_TO_REPORT_FOR_DUTY = "Nearby actions: right stick to choose, X to report for duty"
const MISSION1_NEARBY_ACTIONS_APPEAR_HERE_CLICK_THE_ACTION_OR_PRESS_1_REPORT_FOR = "Nearby actions appear here.\nClick the action or press 1: Report for duty"
const MISSION1_REPORT_TO_THE_CAPTAIN_FOR_DUTY = "Report to the captain for duty."
const MISSION1_RIGHT_STICK_X_INTERACT = "Right stick + X: interact"
const MISSION1_CLICK_AN_ACTION_OR_PRESS_ITS_NUMBER = "Click an action or press its number"
const MISSION1_CARRYING = "Carrying: "
const MISSION1_USE_THE_LEFT_STICK_TO_REACH_THE_CAPTAIN = "Use the left stick to reach the captain."
const MISSION1_TAP_AN_ACTION_TO_INTERACT = "Tap an action to interact."
const MISSION1_OPEN_DIARY_TO_READ_YOUR_NOTES_OR_TURN_BACK_THE_PAGES = "Open Diary to read your notes or turn back the pages."
const MISSION1_RETRY = "Retry"
const MISSION1_MAIN_MENU = "Main menu"
const MISSION1_5_30_THE_UNMOORING_PARTY_IS_OVER = "5:30 · The unmooring party is over.\n\n"
const MISSION1_7_00_SIX_HOURS_S_END_OF_THE_EXPLORATION_SCHEDULE = "7:00 · Six hours %s.\n\nEnd of the exploration schedule."
const MISSION1_IN_GREECE = "in Greece"
const MISSION1_VOYAGE_COMPLETE = "VOYAGE COMPLETE"
const MISSION1_VOYAGE_ENDED = "VOYAGE ENDED"
const MISSION1_THE_NEXT_PAGE = "THE NEXT PAGE"
const MISSION1_EVERYONE_SURVIVED_NOW_I_CAN_TURN_TO_THE_NEXT_PAGE = "Everyone survived. Now I can turn to the next page."
const MISSION1_SCHEDULE_COMPLETE = "SCHEDULE COMPLETE"
const MISSION1_D_D_D_LEFT_RIGHT_LB_RB = "%d–%d / %d    ·    Left / Right · LB / RB"
const MISSION1_THE_DIARY_HAS_NO_EARLIER_PAGES_TO_TURN_TO_YET = "The diary has no earlier pages to turn to yet."
const MISSION1_CLOSE_SHAVE = "Close shave"
const MISSION1_THE_DOCKS = "The docks"
const MISSION1_GRAND_FOYER = "Grand foyer"
const MISSION1_CABIN_CORRIDOR = "Cabin corridor"
const MISSION1_STEAM_ROOM = "Steam room"
const MISSION1_SERVICE_CORRIDOR = "Service corridor"
const MISSION1_SALON = "Salon"
const MISSION1_WE_RE_AT_SEA_I_DON_T_WANT_TO_GO_OVERBOARD = "We're at sea. I don't want to go overboard."
const MISSION1_MUSIC = "Music"
const MISSION1_COULD_NOT_CLEAR_MISSION_1_SAVE_D = "Could not clear Mission 1 save (%d)"
const MISSION1_COULD_NOT_WRITE_VOYAGE_JOURNAL = "Could not write voyage journal."
const MISSION1_COULD_NOT_FLUSH_VOYAGE_JOURNAL = "Could not flush voyage journal."
const MISSION1_COULD_NOT_ROTATE_VOYAGE_BACKUP = "Could not rotate voyage backup."
const MISSION1_COULD_NOT_PROTECT_PREVIOUS_VOYAGE = "Could not protect previous voyage."
const MISSION1_COULD_NOT_PROMOTE_VOYAGE_JOURNAL = "Could not promote voyage journal."
const MISSION1_NO_VALID_MISSION_1_JOURNAL = "No valid Mission 1 journal."
const MISSION1_CLOSE_DOOR = "Close door"
const MISSION1_OPEN_DOOR = "Open door"
const MISSION1_RETRIEVE_BAG = "Retrieve bag"
const MISSION1_HIDE_BAG = "Hide bag"
const MISSION1_WELCOME_TO_GREECE_EXPLORE_THE_DOCK_RESTAURANT_MARKET_AND_SHIP = "Welcome to Greece. Explore the dock, restaurant, market and ship."
const MISSION1_A_NEW_DAY_ABOARD_EXPLORE_THE_SHIP = "A new day aboard. Explore the ship."
const MISSION1_THE_DOOR_IS_LOCKED = "The door is locked."
const MISSION1_SIX_HOURS_IN_GREECE_END_OF_THE_EXPLORATION_SCHEDULE = "Six hours in Greece. End of the exploration schedule."
const MISSION1_SIX_HOURS_ABOARD_END_OF_THE_EXPLORATION_SCHEDULE = "Six hours aboard. End of the exploration schedule."
const MISSION1_I_VISITED = "I visited "
const MISSION1_IS_IN = " is in "
const MISSION1_USE_CONTROLS = "Use controls"
const MISSION1_MISSED_THE_BOAT_MISSION_FAILED_EVERYONE_SURVIVED_BUT_YOU_WERE_STI = "MISSED THE BOAT · MISSION FAILED\nEveryone survived, but you were still on the docks when the ship sailed. Turn back the pages and get aboard before 5:30."
const MISSION1_EVERYONE_SURVIVED_ALL_ABOARD_COMPLETE = "EVERYONE SURVIVED · ALL ABOARD COMPLETE\n"
const MISSION1_THE_NEXT_PAGE_REVEALS_A_NEW_GIFT_LOCATION_REWRITING = "\nThe next page reveals a new gift: location rewriting."
const MISSION1_THE_PARTY_HAS_ENDED = "THE PARTY HAS ENDED\n"
const MISSION1_YOUR_DIARY_RECORDS_WHAT_YOU_WITNESSED_ON_THIS_VOYAGE_TURN_BACK_TH = "\nYour diary records what you witnessed on this voyage. Turn back the pages to try again."
const MISSION1_HOUR = "Hour "
const MISSION1_HOLD_WAIT = "Hold Wait"
const MISSION1_TAP_DIARY = "Tap Diary"
const MISSION1_S_HIGHLIGHT = "%s — Highlight"
const MISSION1_HOLD_S_WAIT = "Hold %s — Wait"
const MISSION1_S_OPEN_DIARY = "%s — Open diary"
const MISSION2_SERVICE_CORRIDOR_CREW_CABINS = "Service corridor · crew cabins"
const MISSION2_FOREDECK = "Foredeck"
const MISSION2_CREW_CABIN_DOOR = "Crew cabin door"
const MISSION3_GREEK_DOCK = "Greek dock"
const MISSION3_RESTAURANT_DINING_ROOM_AND_KITCHEN = "Restaurant · dining room and kitchen"
const UI_GUEST_COUNT = "{count} guest"
const UI_GUEST_COUNT_MANY = "{count} guests"
const UI_LOADING_THE_VOYAGE_D = "Loading the voyage… %d%%"
const UI_A_VOYAGE_BETWEEN_THE_PAGES = "A VOYAGE BETWEEN THE PAGES"
const UI_THE_INCREDIBLE_DIARY = "THE INCREDIBLE DIARY"
const UI_UNABLE_TO_LOAD_THE_DIARY_PLEASE_RESTART = "Unable to load the diary. Please restart."
const UI_LOADING_THE_DIARY_D = "Loading the diary… %d%%"
const UI_MADE_WITH_GODOT = "MADE WITH GODOT"
const UI_JSON_STRINGIFY_WINDOW_DIARY_CONTENT_NULL = "JSON.stringify(window.DIARY_CONTENT || null)"
const UI_RESOURCE_DOWNLOADS_COULD_NOT_START_PLEASE_RELOAD_THE_PAGE = "Resource downloads could not start. Please reload the page."
const UI_A_RESOURCE_COULD_NOT_BE_PREPARED_PLEASE_TRY_AGAIN = "A resource could not be prepared. Please try again."
const UI_A_RESOURCE_COULD_NOT_BE_OPENED_PLEASE_TRY_AGAIN = "A resource could not be opened. Please try again."
const UI_THERE_IS_NOT_ENOUGH_SPACE_TO_OPEN_THIS_RESOURCE_PLEASE_TRY_AGAIN = "There is not enough space to open this resource. Please try again."
const UI_A_DOWNLOADED_RESOURCE_COULD_NOT_BE_OPENED_PLEASE_RELOAD_AND_TRY_A = "A downloaded resource could not be opened. Please reload and try again."
const UI_INSPECT = "Inspect"
const UI_TALK = "Talk"
const UI_HIDE_BAG = "Hide Bag"
const UI_STEAM_CONTROL = "STEAM CONTROL"
const UI_A_NEW_ENTRY_HAS_APPEARED_IN_THE_DIARY = "A new entry has appeared in the diary."
const UI_OBSERVATIONS_ARE_RECORDED_HERE_AS_YOU_EXPLORE = "Observations are recorded here as you explore."
const UI_A_PASSENGER_DEAD_ABOARD_MY_SHIP_I_CAN_T_SAIL_AFTER_THIS_THE_VOYAG = "A passenger dead aboard my ship... I can't sail after this. The voyage will have to be cancelled!"
const UI_5_30_ALL_ABOARD_CAST_OFF = "5:30 — All aboard. Cast off!"
const UI_5_30_THE_VOYAGE_IS_CANCELLED = "5:30 — The voyage is cancelled"
const UI_HOUR_D = "HOUR %d"
const UI_VOYAGE_SUMMARY = "VOYAGE SUMMARY"
const UI_THE_SIX_HOURS_HAVE_ENDED = "The six Hours have ended."
const UI_ONLY_WHAT_AMELIA_WITNESSED_IS_RECORDED_HERE = "Only what Amelia witnessed is recorded here."
const UI_PASSENGER = "Passenger"
const UI_WE_SHOULD_LOOK_MORE_CLOSELY = "We should look more closely."
const UI_WAITING_20 = "Waiting · 20×"
const UI_NEW_URLSEARCHPARAMS_LOCATION_SEARCH_HAS_GITHUB_INTEGRATION_TEST_N = "new URLSearchParams(location.search).has('github_integration_test') && new URLSearchParams(location.search).get('github_web_smoke') === 'read'"
const UI_VOYAGE_COMPLETE = "Voyage complete"
const UI_VOYAGE_ENDED = "Voyage ended"
const UI_MISSION_FAILED_MISSED_THE_BOAT = "Mission failed — missed the boat"
const UI_ALL_ABOARD_S_S = "All Aboard · %s\r\n%s"
const UI_THE_SAVED_VOYAGE_COULD_NOT_BE_LOADED_ITS_FILES_HAVE_BEEN_KEPT = "The saved voyage could not be loaded. Its files have been kept."
const UI_DEV_MENU = "Dev Menu"
const UI_MISSION_1_ALL_ABOARD = "Mission 1 — All Aboard"
const UI_MISSION_2 = "Mission 2"
const UI_MISSION_3_LANDING_IN_GREECE = "Mission 3 — Landing in Greece"
const UI_TEST_LEVEL = "Test Level"
const UI_WINDOW_DIARYTITLEREADY_TRUE_WINDOW_DISPATCHEVENT_NEW_EVENT_DIARY = "window.diaryTitleReady = true; window.dispatchEvent(new Event('diary-title-ready'));"
const UI_DIARY = "Diary"
const UI_WAIT = "Wait"
const UI_HIGHLIGHT = "Highlight"
const UI_CANCEL = "Cancel"
const UI_NAVIGATOR_MAXTOUCHPOINTS_0_MATCHMEDIA_POINTER_COARSE_MATCHES = "navigator.maxTouchPoints > 0 && matchMedia('(pointer: coarse)').matches"
const UI_MATCHMEDIA_ORIENTATION_PORTRAIT_MATCHES = "matchMedia('(orientation: portrait)').matches"
const UI_MASTER = "Master"
const UI_DIALOGUE = "Dialogue"
const UI_PREFERENCES_COULD_NOT_BE_SAVED_CHANGES_WORK_FOR_THIS_SESSION_CLOS = "Preferences could not be saved. Changes work for this session; closing Settings retries."
const UI_THE_GAME_COULD_NOT_BE_SAVED_YOU_ARE_STILL_IN_THE_CURRENT_GAME_TRY = "The game could not be saved. You are still in the current game; try again."
const UI_THE_MAIN_MENU_COULD_NOT_BE_OPENED_PLEASE_TRY_AGAIN = "The main menu could not be opened. Please try again."
const UI_SETTINGS = "Settings"
const UI_CLOSE = "Close"
const UI_AUDIO = "Audio"
const UI_MASTER_VOLUME = "Master volume"
const UI_CONTROLS = "Controls"
const UI_MOVEMENT_JOYSTICK_POSITION = "Movement joystick position"
const UI_BUTTONS_APPEAR_ON_THE_OPPOSITE_SIDE = "Buttons appear on the opposite side."
const UI_CLEAR_S_S_BINDING = "Clear %s %s binding"
const UI_RESTORE_S_DEFAULTS = "Restore %s defaults"
const UI_CANCEL_BINDING = "Cancel binding"
const UI_ASSIGN_ANYWAY = "Assign anyway"
const UI_PRIMARY = "Primary"
const UI_ALTERNATE = "Alternate"
const UI_RELEASE_HELD_INPUTS_THEN_PRESS_A_S_INPUT_10_SECONDS = "Release held inputs, then press a %s input (10 seconds)."
const UI_BINDING_CANCELLED_NO_INPUT_RECEIVED = "Binding cancelled: no input received."
const UI_ALREADY_ASSIGNED_TO_S_ASSIGN_ANYWAY = "Already assigned to: %s. Assign anyway?"
const UI_MOVE_LEFT = "Move left"
const UI_MOVE_RIGHT = "Move right"
const UI_MOVE_UP = "Move up"
const UI_MOVE_DOWN = "Move down"
const UI_WAIT_HOLD = "Wait (hold)"
const UI_OPEN_CLOSE_DIARY = "Open/close diary"
const UI_RESET_LOOP = "Reset loop"
const UI_CANCEL_ACTION = "Cancel action"
const UI_INTERACTION_1 = "Interaction 1"
const UI_INTERACTION_2 = "Interaction 2"
const UI_INTERACTION_3 = "Interaction 3"
const UI_INTERACTION_4 = "Interaction 4"
const UI_INTERACTION_5 = "Interaction 5"
const UI_INTERACTION_6 = "Interaction 6"
const UI_INTERACTION_7 = "Interaction 7"
const UI_INTERACTION_8 = "Interaction 8"
const UI_CONFIRM_SELECTED_INTERACTION = "Confirm selected interaction"
const UI_SUBMIT_CODE = "Submit code"
const UI_CLEAR_CODE = "Clear code"
const UI_CONTINUE_AFTER_ENDING = "Continue after ending"
const UI_PREVIOUS_DIARY_PAGE = "Previous diary page"
const UI_NEXT_DIARY_PAGE = "Next diary page"
const UI_THIS_KEY_IS_RESERVED_FOR_PAUSE_EDITOR_CONTROLS = "This key is reserved for pause/editor controls."
const UI_THIS_BUTTON_IS_RESERVED_FOR_SETTINGS_OR_PAUSE_EDITOR_CONTROLS = "This button is reserved for Settings or pause/editor controls."
const UI_D_PAD_UP = "D-pad Up"
const UI_D_PAD_DOWN = "D-pad Down"
const UI_D_PAD_LEFT = "D-pad Left"
const UI_D_PAD_RIGHT = "D-pad Right"
const UI_BUTTON_D = "Button %d"
const UI_SPOKEN_LINE = "{speaker}: {line}"
const UI_LANGUAGE = "Language"
const UI_AUTOMATIC = "Automatic"
const UI_ENGLISH = "English"
const UI_LOADING_PREPARING = "Preparing the diary…"
const UI_LOADING_OPENING = "Opening the diary…"
const UI_LOADING_PROGRESS = "Loading the diary… {percent}%"
const UI_LOADING_FAILED = "The diary could not be opened."
const UI_LOADING_UNKNOWN = "An unknown error occurred."
const UI_LOADING_UNSUPPORTED = "Your browser does not support the features needed to open the diary."
const UI_CARRYING = "Carrying: {item}"
const UI_MISSION_HEADING = "Mission {number}  ·  {room}"
const UI_VOYAGE_HEADING = "All Aboard  ·  {room}"
const UI_CONTINUE = "CONTINUE"
const UI_NEW = "NEW"
const UI_QUIT = "QUIT"
const UI_START_A_NEW_VOYAGE = "Start a new voyage?"
const UI_STARTING_NEW_WILL_PERMANENTLY_CLEAR_THE_CURRENT_MISSION_1_SAVE_AN = "Starting New will permanently clear the current Mission 1 save and its recorded history. Continue?"
const UI_CLEAR_SAVE_AND_START = "Clear save and start"
const UI_VOYAGE_UNAVAILABLE = "Voyage unavailable"
const UI_GET_DRINK = "Get {drink}"
const UI_PREFERS_DRINK = "Prefers {drink}"
const UI_OFFER_DRINK = "Offer {drink}"
const UI_VISITED_ROOM = "I visited {room}."
const UI_ACTOR_ROOM = "{actor} is in {room}."
const UI_ACTION_BINDING = "{binding}  {action}"
const UI_MARKET = "Market"
const UI_LEMONADE = "Lemonade"
const UI_WINE = "Wine"
const UI_CHAMPAGNE = "Champagne"
const UI_BRANDY = "Brandy"
const UI_WHISKY = "Whisky"
const UI_CLEAR = "Clear"
const UI_ENTER = "Enter"
const UI_UNBOUND = "Unbound"
const UI_CONTROLLER = "Controller"
const UI_KEYBOARD = "Keyboard"
const UI_TOUCH = "Touch"
const UI_SFX = "SFX"
const UI_SUMMARY_SURVIVED = "{name}: survived"
const UI_SUMMARY_DIED = "{name}: died"
const UI_SUMMARY_SUCCESS = "EVERYONE SURVIVED · ALL ABOARD COMPLETE\r\n{outcomes}\r\nThe next page reveals a new gift: location rewriting."
const UI_SUMMARY_FAILED = "THE PARTY HAS ENDED\r\n{outcomes}\r\nYour diary records what you witnessed on this voyage. Turn back the pages to try again."
const UI_DIARY_OUTCOME = "5:30 · The unmooring party is over.\r\n\r\n{summary}"
const UI_SETTINGS_UPPER = "SETTINGS"
const UI_CONTROL_LEFT = "Left"
const UI_CONTROL_RIGHT = "Right"
const UI_CONTROL_KEYBOARD = "keyboard"
const UI_CONTROL_CONTROLLER = "controller"
const UI_CONTROL_TOUCH = "touch"
const UI_CONTROL_PRIMARY = "primary"
const UI_CONTROL_ALTERNATE = "alternate"
const UI_CONTROL_ABOARD = "aboard"
const UI_BINDING_SLOT = "{slot}: {binding}"
const UI_BINDING_TOOLTIP = "{action} — {slot}: {binding}"
const UI_GENERAL = "General"
const UI_CONFIRM = "CONFIRM"
const UI_PEOPLE = "PEOPLE"
const UI_MOVE = "Move"
const UI_TEA = "Tea"
const UI_ACCESSIBILITY = "Accessibility"
const UI_HIGH_CONTRAST_TEXT_PANELS = "High-contrast text panels"
const UI_INSTANT_DIALOGUE_TEXT = "Instant dialogue text"
const UI_STEAM_ON = "On"
const UI_STEAM_OFF = "Off"
const UI_STOP_WAITING = "Stop"
const UI_WAIT_TOGGLE = "Wait (toggle)"
const MISSION1_TOGGLE_B_WAIT = "B — Toggle Wait"
const MISSION1_TOGGLE_F_WAIT = "F — Toggle Wait"
const MISSION1_TAP_WAIT = "Tap Wait to start/stop"
const MISSION1_TOGGLE_S_WAIT = "%s — Toggle Wait"
const SOURCES = {
	"MISSION1_BOY": "Boy",
	"MISSION1_MR_FELIX_HARCOURT": "Mr. Felix Harcourt",
	"MISSION1_MISS_EVELYN_VALE": "Miss Evelyn Vale",
	"MISSION1_MRS_MABEL_PRITCHARD": "Mrs. Mabel Pritchard",
	"MISSION1_SAILOR": "Sailor",
	"MISSION1_CAPTAIN": "Captain",
	"MISSION1_PORTER": "Porter",
	"MISSION1_GUEST": "Guest",
	"MISSION1_UNSUPPORTED_MISSION_1_CONTENT_SCHEMA": "Unsupported Mission 1 content schema",
	"MISSION1_S_MUST_BE_AN_OBJECT": "%s must be an object",
	"MISSION1_S_MUST_BE_A_LIST": "%s must be a list",
	"MISSION1_THE_PLAYER_ENTITY_AMELIA_IS_REQUIRED": "The player entity amelia is required",
	"MISSION1_MISSION_1_OPERATIONS_STILL_REFERENCE_CHARACTER": "Mission 1 operations still reference character ",
	"MISSION1_ROOM_S_NEEDS_DIMENSIONS_AND_COLLISION_CELLS": "Room %s needs dimensions and collision cells",
	"MISSION1_ROOM_S_DIMENSIONS_MUST_BE_1_10000": "Room %s dimensions must be 1–10000",
	"MISSION1_ROOM_S_COLLISION_CELLS_MUST_USE_INTEGER_X_Y_KEYS_AND_TRUE_VALUES": "Room %s collision cells must use integer x,y keys and true values",
	"MISSION1_ROOM_S_BACKGROUND_ASSET_IS_MISSING": "Room %s background asset is missing",
	"MISSION1_TEMPLATE_S_HAS_AN_INVALID_ENTITY_KIND": "Template %s has an invalid entity kind",
	"MISSION1_TEMPLATE_S_HAS_INVALID_STATE_RULES": "Template %s has invalid state rules",
	"MISSION1_TEMPLATE_S_STATES_MUST_BE_OBJECTS": "Template %s states must be objects",
	"MISSION1_TEMPLATE_S_HAS_AN_INVALID_TRANSITION": "Template %s has an invalid transition",
	"MISSION1_ENTITY_S_NEEDS_A_POSITION_AND_OVERRIDES": "Entity %s needs a position and overrides",
	"MISSION1_ENTITY_S_TEMPLATE_IS_MISSING": "Entity %s template is missing",
	"MISSION1_ENTITY_S_ROOM_IS_MISSING": "Entity %s room is missing",
	"MISSION1_ENTITY_S_HAS_AN_UNKNOWN_APPEARANCE": "Entity %s has an unknown appearance",
	"MISSION1_ENTITY_S_STATE_OVERRIDES_ARE_INVALID": "Entity %s state overrides are invalid",
	"MISSION1_ENTITY_S_TRANSITION_TARGET_IS_MISSING": "Entity %s transition target is missing",
	"MISSION1_ENTITY_S_INTERACTIONS_MUST_BE_A_LIST": "Entity %s interactions must be a list",
	"MISSION1_ENTITY_S_HAS_AN_INVALID_INTERACTION_POSITION": "Entity %s has an invalid interaction position",
	"MISSION1_INTERACTION_DURATION_MUST_BE_POSITIVE": "Interaction duration must be positive",
	"MISSION1_ENTITY_S_INTERACTION_IS_BLOCKED_BY_AUTHORED_COLLISION": "Entity %s interaction is blocked by authored collision",
	"MISSION1_A_ROOM_CONNECTION_HAS_MISSING_ENDPOINTS": "A room connection has missing endpoints",
	"MISSION1_CONNECTION_ENDPOINT_IN_S_IS_BLOCKED": "Connection endpoint in %s is blocked",
	"MISSION1_SCHEDULE_S_ACTOR_IS_MISSING": "Schedule %s actor is missing",
	"MISSION1_SCHEDULE_S_NEEDS_COMMITMENTS": "Schedule %s needs commitments",
	"MISSION1_SCHEDULE_S_HAS_AN_INVALID_COMMITMENT": "Schedule %s has an invalid commitment",
	"MISSION1_SCHEDULE_S_NEEDS_AN_ORIGIN_AND_STAGES": "Schedule %s needs an origin and stages",
	"MISSION1_SCHEDULE_S_HAS_AN_INVALID_STAGE": "Schedule %s has an invalid stage",
	"MISSION1_STORYLET_NEEDS_AN_ID_CONDITIONS_AND_EFFECTS": "Storylet needs an ID, conditions and effects",
	"MISSION1_STORYLET_S_HAS_INVALID_TIMING_OR_PARTICIPANTS": "Storylet %s has invalid timing or participants",
	"MISSION1_STORYLET_S_SCENE_IS_MISSING": "Storylet %s scene is missing",
	"MISSION1_STORYLET_S_ACTOR_S_IS_MISSING": "Storylet %s actor %s is missing",
	"MISSION1_STORYLET_S_HAS_AN_UNSUPPORTED_COMMAND": "Storylet %s has an unsupported command",
	"MISSION1_UNSUPPORTED_MISSION_1_OPERATION": "Unsupported Mission 1 operation",
	"MISSION1_FLAG_COMMAND_NEEDS_A_KEY": "Flag command needs a key",
	"MISSION1_PROP_COMMAND_NEEDS_AN_ENTITY_AND_STATE": "Prop command needs an entity and state",
	"MISSION1_SAY_COMMAND_NEEDS_AN_ACTOR_AND_TEXT": "Say command needs an actor and text",
	"MISSION1_NOTE_COMMAND_NEEDS_A_KEY_AND_TEXT": "Note command needs a key and text",
	"MISSION1_STORYLET_CONDITIONS_MUST_BE_OBJECTS": "Storylet conditions must be objects",
	"MISSION1_TIMING_S_MUST_BE_WITHIN_THE_LEG": "Timing %s must be within the leg",
	"MISSION1_ASSET_S_S": "Asset %s: %s",
	"MISSION1_SCENE_S_MUST_BE_SOURCE_TEXT": "Scene %s must be source text",
	"MISSION1_ENTITY_S_INTERACTION_HAS_NO_ROUTE_FROM_THE_PLAYER_START": "Entity %s interaction has no route from the player start",
	"MISSION1_SCHEDULE_S_DESTINATION_HAS_NO_CONNECTED_ROUTE": "Schedule %s destination has no connected route",
	"MISSION1_CONDITIONS_MUST_BE_A_LIST": "Conditions must be a list",
	"MISSION1_CONDITION_MUST_BE_AN_OBJECT": "Condition must be an object",
	"MISSION1_UNKNOWN_CONDITION_USE_FLAG_HAS_FLAG_ACTOR_PROP_SAFE_DEAD_OR_DISTA": "Unknown condition; use flag, has_flag, actor, prop, safe, dead or distance",
	"MISSION1_CONDITION_REFERENCES_MISSING_ENTITY": "Condition references missing entity ",
	"MISSION1_DISTANCE_CONDITION_NEEDS_TWO_ENTITIES_AND_A_MAXIMUM_DISTANCE": "Distance condition needs two entities and a maximum distance",
	"MISSION1_EFFECTS_MUST_BE_A_LIST": "Effects must be a list",
	"MISSION1_EFFECT_MUST_BE_AN_OBJECT": "Effect must be an object",
	"MISSION1_FLAG_EFFECT_NEEDS_A_KEY": "Flag effect needs a key",
	"MISSION1_PROP_EFFECT_NEEDS_AN_ENTITY_AND_STATE": "Prop effect needs an entity and state",
	"MISSION1_PROP_EFFECT_REFERENCES_AN_UNKNOWN_STATE": "Prop effect references an unknown state",
	"MISSION1_SAY_EFFECT_NEEDS_AN_ACTOR_AND_TEXT": "Say effect needs an actor and text",
	"MISSION1_NOTE_EFFECT_NEEDS_A_KEY_AND_TEXT": "Note effect needs a key and text",
	"MISSION1_UNKNOWN_MISSION_1_OPERATION": "Unknown Mission 1 operation",
	"MISSION1_UNKNOWN_EFFECT_COMMAND": "Unknown effect command",
	"MISSION1_MY_SUITCASE_AT_LAST_THANK_YOU": "My suitcase! At last. Thank you.",
	"MISSION1_MY_SUIT_DO_WATCH_WHERE_YOU_ARE_GOING": "My suit! Do watch where you are going!",
	"MISSION1_I_WANTED_TO_APOLOGISE_ABOUT_YOUR_DRINK_SIR": "I wanted to apologise about your drink, sir.",
	"MISSION1_YOU_RUINED_MY_SUIT_I_HAVE_NO_INTEREST_IN_YOUR_EXCUSES_NOW_LEAVE_M": "You ruined my suit. I have no interest in your excuses. Now leave me alone.",
	"MISSION1_HOW_DARE_YOU_WHAT_DO_YOU_THINK_YOU_ARE_DOING": "How dare you! What do you think you are doing?",
	"MISSION1_BEFORE_YOU_GO_YOU_MUST_HEAR_ABOUT_MY_NEPHEW": "Before you go, you must hear about my nephew.",
	"MISSION1_COULD_IT_WAIT_THEY_ARE_SERVING_DRINKS": "Could it wait? They are serving drinks.",
	"MISSION1_HE_BOUGHT_A_MOTORCAR_WITHOUT_ASKING_HIS_MOTHER": "He bought a motorcar. Without asking his mother!",
	"MISSION1_HOW_VERY_RASH": "How very rash.",
	"MISSION1_THAT_IS_EXACTLY_WHAT_I_SAID_NOW_LISTEN": "That is exactly what I said. Now, listen…",
	"MISSION1_HELP_THE_STEAM_HAS_CUT_OFF_THE_PASSAGE": "Help! The steam has cut off the passage!",
	"MISSION1_WHERE_ARE_MY_BAGS_I_WILL_NOT_BOARD_WITHOUT_THEM": "Where are my bags? I will not board without them!",
	"MISSION1_I_LL_SEARCH_THE_LUGGAGE_SIR": "I'll search the luggage, sir.",
	"MISSION1_BROWN_LEATHER_WITH_MY_INITIALS": "Brown leather. With my initials.",
	"MISSION1_STAY_HERE_I_LL_BRING_THEM_OVER": "Stay here. I'll bring them over.",
	"MISSION1_MY_BROWN_SUITCASE_IS_STILL_MISSING_I_M_WAITING_HERE": "My brown suitcase is still missing. I'm waiting here.",
	"MISSION1_BOY_REPORT_FOR_DUTY": "Boy! Report for duty.",
	"MISSION1_YES_CAPTAIN": "Yes, Captain.",
	"MISSION1_EXPLORE_THE_SHIP_AND_MAKE_SURE_OUR_GUESTS_ARE_COMFORTABLE_HELP_WI": "Explore the ship and make sure our guests are comfortable. Help with their luggage, bring refreshments, and show them to their cabins.",
	"MISSION1_VERY_GOOD_CAPTAIN": "Very good, Captain.",
	"MISSION1_PASSENGERS_ARE_COMING_ABOARD_GET_TO_IT": "Passengers are coming aboard. Get to it.",
	"MISSION1_WHICH_WAY_TO_THE_SALON": "Which way to the Salon?",
	"MISSION1_UP_THE_CENTRE_STAIR_MADAM": "Up the centre stair, madam.",
	"MISSION1_A_LOVELY_EVENING_FOR_A_DEPARTURE": "A lovely evening for a departure.",
	"MISSION1_PROVIDED_THE_SEA_REMEMBERS_ITS_MANNERS": "Provided the sea remembers its manners.",
	"MISSION1_ARE_YOU_SETTLING_INTO_YOUR_CABIN": "Are you settling into your cabin?",
	"MISSION1_AT_LAST_I_THOUGHT_MY_LUGGAGE_HAD_TAKEN_ITS_OWN_HOLIDAY": "At last. I thought my luggage had taken its own holiday.",
	"MISSION1_A_NEW_POSTING_AN_UNMOORING_PARTY_WHAT_COULD_POSSIBLY_GO_WRONG": "A new posting. An unmooring party. What could possibly go wrong?",
	"MISSION1_REPORT_FOR_DUTY": "Report for duty",
	"MISSION1_INSPECT_LUGGAGE": "Inspect luggage",
	"MISSION1_ACTION_INTERRUPTED_UNFINISHED_PROGRESS_LOST": "Action interrupted. Unfinished progress lost.",
	"MISSION1_THE_UNMOORING_PARTY_HAS_ENDED": "The unmooring party has ended.",
	"MISSION1_I_OPENED_THE_CABIN_DOOR": "I opened the cabin door.",
	"MISSION1_I_CLOSED_THE_CABIN_DOOR": "I closed the cabin door.",
	"MISSION1_THE_SAME_MONOGRAM_HE_STILL_REFUSES_TO_BOARD_WITHOUT_THIS_BAG": "The same monogram. He still refuses to board without this bag.",
	"MISSION1_A_MONOGRAMMED_SUITCASE_TUCKED_AMONG_THE_TRUNKS": "A monogrammed suitcase tucked among the trunks.",
	"MISSION1_I_TUCKED_THE_SUITCASE_BEHIND_THE_BAGGAGE_SCREEN": "I tucked the suitcase behind the baggage screen.",
	"MISSION1_I_BROUGHT_THE_SUITCASE_BACK_TO_ITS_OWNER": "I brought the suitcase back to its owner.",
	"MISSION1_PORTER_THE_CENTRE_STAIR_IS_ONLY_LATCHED_RELEASE_THE_BRASS_CATCH_A": "Porter: The centre stair is only latched. Release the brass catch at its foot.",
	"MISSION1_I_RELEASED_THE_LATCH_THE_CENTRE_STAIR_LEADS_STRAIGHT_TO_THE_SALON": "I released the latch. The centre stair leads straight to the salon.",
	"MISSION1_STEAM_BLOCKS_THE_FAR_ROOM_S_NORMAL_EXIT_THE_TALKATIVE_PASSENGER_I": "Steam blocks the far room's normal exit. The talkative passenger is trapped.",
	"MISSION1_THE_PASSENGER_COLLAPSED_BEHIND_THE_STEAM": "The passenger collapsed behind the steam.",
	"MISSION1_CREW_A_PASSENGER_NEEDS_HELP_IN_THE_STEAM_PASSAGE": "Crew: A passenger needs help in the steam passage!",
	"MISSION1_THE_CHANDELIER_CREAKS_AND_TREMBLES_ABOVE_THE_GUEST": "The chandelier creaks and trembles above the guest.",
	"MISSION1_THE_CHANDELIER_FELL_ON_THE_GUEST": "The chandelier fell on the guest.",
	"MISSION1_THE_CHANDELIER_CRASHED_ONTO_THE_PLACE_WHERE_THE_GUEST_HAD_BEEN_ST": "The chandelier crashed onto the place where the guest had been standing.",
	"MISSION1_THE_DIARY_SHIVERS": "The diary shivers.",
	"MISSION1_YOU_FOUND_THE_BAG_THANK_YOU_BOY_SAVED_ME_A_SEARCH": "You found the bag! Thank you, Boy. Saved me a search.",
	"MISSION1_THE_STAIR_S_BRASS_CATCH_IS_STILL_HERE": "The stair's brass catch is still here.",
	"MISSION1_I_DO_WISH_THEY_WOULD_GET_ON_WITH_IT_SUCH_A_WAIT": "I do wish they would get on with it. Such a wait!",
	"MISSION1_BUMP_INTO_GUEST": "Bump into guest",
	"MISSION1_INSPECT_GLASS": "Inspect glass",
	"MISSION1_INSPECT_WRECKAGE": "Inspect wreckage",
	"MISSION1_MY_ELBOW_CAUGHT_THE_GLASS_HIS_DRINK_SOAKED_HIS_SUIT": "My elbow caught the glass. His drink soaked his suit.",
	"MISSION1_A_SHARP_CHEMICAL_RESIDUE_IN_THE_GLASS_THE_DRINK_WAS_POISONED_NOTH": "A sharp chemical residue in the glass. The drink was poisoned; nothing here identifies who did it.",
	"MISSION1_I_SHOVED_THE_GUEST_OUT_FROM_BENEATH_THE_CHANDELIER": "I shoved the guest out from beneath the chandelier.",
	"MISSION1_SHE_IS_DEAD_BENEATH_THE_CHANDELIER_BROKEN_GLASS_EVERYWHERE_AND_A": "She is dead, beneath the chandelier. Broken glass everywhere, and a snapped suspension pin.",
	"MISSION1_BROKEN_GLASS_AND_A_SNAPPED_SUSPENSION_PIN_THANK_GOODNESS_I_GOT_HE": "Broken glass and a snapped suspension pin. Thank goodness I got her out of the way.",
	"MISSION1_THE_LUGGAGE_OWNER_IS_WAITING_AT_THE_BAR": "The luggage owner is waiting at the bar.",
	"MISSION1_THE_LUGGAGE_OWNER_HAS_COLLAPSED_BESIDE_HIS_GLASS": "The luggage owner has collapsed beside his glass.",
	"MISSION1_THE_PASSENGER_LIES_MOTIONLESS_BEYOND_THE_STEAM_LEAK": "The passenger lies motionless beyond the steam leak.",
	"MISSION1_THE_GUEST_LIES_DEAD_BENEATH_THE_FALLEN_CHANDELIER": "The guest lies dead beneath the fallen chandelier.",
	"MISSION1_THE_FALLEN_CHANDELIER_LIES_IN_PIECES_THE_GUEST_IS_SAFE": "The fallen chandelier lies in pieces. The guest is safe.",
	"MISSION1_THE_PASSENGER_LEAVES_THROUGH_THE_CLEARED_STEAM_PASSAGE": "The passenger leaves through the cleared steam passage.",
	"MISSION1_THE_PASSENGER_EMERGES_FROM_THE_STEAM_ROOM": "The passenger emerges from the steam room.",
	"MISSION1_AN_OBSCURED_HAND_TIPS_SOMETHING_INTO_THE_GUEST_S_GLASS": "An obscured hand tips something into the guest's glass.",
	"MISSION1_THE_GUEST_DRANK_THEN_COLLAPSED_BESIDE_THE_POISONED_GLASS": "The guest drank, then collapsed beside the poisoned glass.",
	"MISSION1_PRESSURE_MUST_BE_RUNNING_FOR_THE_CONTROLS_TO_RESPOND": "Pressure must be running for the controls to respond.",
	"MISSION1_ENTER_THREE_DIGITS_THEN_PRESS_COMMIT_CLEAR_STARTS_YOUR_ENTRY_AGAI": "Enter three digits, then press Commit. Clear starts your entry again.",
	"MISSION1_TODAY_S_SHUTOFF_CODE_IS_S": "Today's shutoff code is %s.",
	"MISSION1_CODE_REJECTED_CLEAR_AND_TRY_AGAIN": "Code rejected. Clear and try again.",
	"MISSION1_I_STOPPED_THE_STEAM": "I stopped the steam.",
	"MISSION1_FOUND_IT_BROWN_LEATHER_JUST_AS_YOU_SAID": "Found it! Brown leather, just as you said.",
	"MISSION1_LOOP_D_HOUR": "Loop %d · Hour ",
	"MISSION1_THE_PASSAGE_IS_CLEAR_THE_PASSENGER_STARTS_TOWARDS_THE_EXIT": "The passage is clear. The passenger starts towards the exit.",
	"MISSION1_CONTENT_APPLIED": "Content applied",
	"MISSION1_SPARKLING_WATER": "Sparkling water",
	"MISSION1_LEMONADE_PLEASE_BOY": "Lemonade, please, Boy.",
	"MISSION1_EXCELLENT_LEMONADE_BOY_THANK_YOU": "Excellent lemonade, Boy. Thank you.",
	"MISSION1_I_ASKED_FOR_LEMONADE_BOY_DO_TRY_TO_REMEMBER": "I asked for lemonade, Boy. Do try to remember.",
	"MISSION1_SPARKLING_WATER_PLEASE_BOY": "Sparkling water, please, Boy.",
	"MISSION1_JUST_WHAT_I_WANTED_THANK_YOU_BOY": "Just what I wanted. Thank you, Boy.",
	"MISSION1_THAT_ISN_T_SPARKLING_WATER_PERHAPS_SOMEONE_ELSE_ORDERED_IT": "That isn't sparkling water. Perhaps someone else ordered it?",
	"MISSION1_A_PROPER_CUP_OF_TEA_PLEASE_BOY": "A proper cup of tea, please, Boy.",
	"MISSION1_LOVELY_A_PROPER_CUP_OF_TEA_THANK_YOU_BOY": "Lovely. A proper cup of tea. Thank you, Boy.",
	"MISSION1_TEA_BOY_A_PROPER_CUP_OF_TEA": "Tea, Boy. A proper cup of tea.",
	"MISSION1_INSPECT_NAMEPLATE": "Inspect nameplate",
	"MISSION1_ASK_ABOUT_DRINKS": "Ask about drinks",
	"MISSION1_GIVE_CABIN_DIRECTIONS": "Give cabin directions",
	"MISSION1_CABIN_D_S": "Cabin %d — %s",
	"MISSION1_CABIN_D_THANK_YOU_BOY": "Cabin %d. Thank you, Boy.",
	"MISSION1_CABIN_D_YOU_SAY_VERY_WELL_BOY": "Cabin %d, you say? Very well, Boy.",
	"MISSION1_THIS_IS_S_S_CABIN_YOU_SENT_ME_TO_THE_WRONG_DOOR_BOY": "This is %s's cabin! You sent me to the wrong door, Boy.",
	"MISSION1_S_HOW_CURIOUS_BOY_I_SEEM_TO_HAVE_BECOME_SOMEBODY_ELSE": "%s? How curious, Boy. I seem to have become somebody else.",
	"MISSION1_THE_PLATE_SAYS_S_READ_THE_NAMES_PROPERLY_NEXT_TIME_BOY": "The plate says %s! Read the names properly next time, Boy.",
	"MISSION1_OH_HOW_DREADFUL_THAT_POOR_WOMAN": "Oh, how dreadful. That poor woman.",
	"MISSION1_SHE_WAS_STANDING_HERE_A_MOMENT_AGO_SOMEONE_MUST_FETCH_THE_CAPTAIN": "She was standing here a moment ago. Someone must fetch the captain.",
	"MISSION1_HE_S_DEAD_WHAT_A_TERRIBLE_END_TO_THE_PARTY": "He's dead! What a terrible end to the party.",
	"MISSION1_HE_WAS_RATHER_A_BORE_STILL_NOBODY_DESERVES_THIS": "He was rather a bore. Still, nobody deserves this.",
	"MISSION1_SHE_S_DEAD_I_LL_STAY_WITH_HER_UNTIL_HELP_ARRIVES": "She's dead. I'll stay with her until help arrives.",
	"MISSION1_WHY_HAS_THIS_BEEN_SWITCHED_OFF": "Why has this been switched off?",
	"MISSION1_I_WONDER_WHAT_I_SHOULD_DO": "I wonder what I should do?",
	"MISSION1_HURRY_UP_AND_WAIT": "Hurry up and wait…",
	"MISSION1_SOMETHING_HAS_CHANGED_IN_THE_DIARY_I_SHOULD_OPEN_IT": "Something has changed in the diary. I should open it.",
	"MISSION1_WHAT_A_TRAGEDY_HMMM_MY_DIARY_IS_SHAKING_I_FEEL_LIKE_I_SHOULD_TAKE": "What a tragedy. Hmmm, my diary is shaking, I feel like I should take a look.",
	"MISSION1_TAP_HIGHLIGHT": "Tap Highlight",
	"MISSION1_A_HIGHLIGHT": "A — Highlight",
	"MISSION1_HOLD_B_WAIT": "Hold B — Wait",
	"MISSION1_Y_OPEN_DIARY": "Y — Open diary",
	"MISSION1_H_HIGHLIGHT": "H — Highlight",
	"MISSION1_HOLD_F_WAIT": "Hold F — Wait",
	"MISSION1_TAB_OPEN_DIARY": "Tab — Open diary",
	"MISSION1_TIME_WINDOW": "time window",
	"MISSION1_NOT_ALREADY_COMPLETED": "not already completed",
	"MISSION1_PARTICIPANT": "participant ",
	"MISSION1_RESTART_REQUIRED_ACTIVE_ENTITY_S_WAS_REMOVED": "Restart required: active entity %s was removed",
	"MISSION1_RESTART_REQUIRED_S_OCCUPIES_CHANGED_COLLISION_GEOMETRY": "Restart required: %s occupies changed collision geometry",
	"MISSION1_RESTART_REQUIRED_S_STARTING_PLACEMENT_CHANGED": "Restart required: %s starting placement changed",
	"MISSION1_RESTART_REQUIRED_ACTIVE_SCENE_S_CHANGED": "Restart required: active scene %s changed",
	"MISSION1_RESTART_REQUIRED_ACTIVE_PARTICIPANT_S_CHANGED": "Restart required: active participant %s changed",
	"MISSION1_THOUGHT": "Thought",
	"MISSION1_UNKNOWN_MISSION_1_SOUND_CUE_S": "Unknown Mission 1 sound cue: %s",
	"MISSION1_CABIN_D": "Cabin %d",
	"MISSION1_BACK": "Back",
	"MISSION1_GET": "Get ",
	"MISSION1_RETURN_DRINK": "Return drink",
	"MISSION1_PREFERS": "Prefers ",
	"MISSION1_OFFER": "Offer ",
	"MISSION1_VOYAGE_NOTEBOOK": "VOYAGE NOTEBOOK",
	"MISSION1_THE_VOYAGE": "THE VOYAGE",
	"MISSION1_OBSERVATIONS_FROM_THE_CURRENT_VOYAGE_RECORDED_AS_THEY_HAPPEN": "Observations from the current voyage, recorded as they happen.",
	"MISSION1_CLOSE_DIARY_S_S": "Close diary (%s / %s)",
	"MISSION1_TURN_BACK_TO_THE_START_R": "Turn back to the start (R)",
	"MISSION1_TURN_THE_PAGE": "Turn the Page",
	"MISSION1_RETURN_TO_MAIN_MENU": "Return to main menu",
	"MISSION1_PREVIOUS": "‹ Previous",
	"MISSION1_NEXT": "Next ›",
	"MISSION1_ACTION_CANCELLED": "Action cancelled.",
	"MISSION1_MISSION_D": "Mission %d  ·  ",
	"MISSION1_ALL_ABOARD": "All Aboard  ·  ",
	"MISSION1_THE_PAGES_TURN_BACKWARDS_R_TO_SKIP": "The pages turn backwards…  R to skip",
	"MISSION1_NEARBY_ACTIONS_RIGHT_STICK_TO_CHOOSE_X_TO_REPORT_FOR_DUTY": "Nearby actions: right stick to choose, X to report for duty",
	"MISSION1_NEARBY_ACTIONS_APPEAR_HERE_CLICK_THE_ACTION_OR_PRESS_1_REPORT_FOR": "Nearby actions appear here.\nClick the action or press 1: Report for duty",
	"MISSION1_REPORT_TO_THE_CAPTAIN_FOR_DUTY": "Report to the captain for duty.",
	"MISSION1_RIGHT_STICK_X_INTERACT": "Right stick + X: interact",
	"MISSION1_CLICK_AN_ACTION_OR_PRESS_ITS_NUMBER": "Click an action or press its number",
	"MISSION1_CARRYING": "Carrying: ",
	"MISSION1_USE_THE_LEFT_STICK_TO_REACH_THE_CAPTAIN": "Use the left stick to reach the captain.",
	"MISSION1_TAP_AN_ACTION_TO_INTERACT": "Tap an action to interact.",
	"MISSION1_OPEN_DIARY_TO_READ_YOUR_NOTES_OR_TURN_BACK_THE_PAGES": "Open Diary to read your notes or turn back the pages.",
	"MISSION1_RETRY": "Retry",
	"MISSION1_MAIN_MENU": "Main menu",
	"MISSION1_5_30_THE_UNMOORING_PARTY_IS_OVER": "5:30 · The unmooring party is over.\n\n",
	"MISSION1_7_00_SIX_HOURS_S_END_OF_THE_EXPLORATION_SCHEDULE": "7:00 · Six hours %s.\n\nEnd of the exploration schedule.",
	"MISSION1_IN_GREECE": "in Greece",
	"MISSION1_VOYAGE_COMPLETE": "VOYAGE COMPLETE",
	"MISSION1_VOYAGE_ENDED": "VOYAGE ENDED",
	"MISSION1_THE_NEXT_PAGE": "THE NEXT PAGE",
	"MISSION1_EVERYONE_SURVIVED_NOW_I_CAN_TURN_TO_THE_NEXT_PAGE": "Everyone survived. Now I can turn to the next page.",
	"MISSION1_SCHEDULE_COMPLETE": "SCHEDULE COMPLETE",
	"MISSION1_D_D_D_LEFT_RIGHT_LB_RB": "%d–%d / %d    ·    Left / Right · LB / RB",
	"MISSION1_THE_DIARY_HAS_NO_EARLIER_PAGES_TO_TURN_TO_YET": "The diary has no earlier pages to turn to yet.",
	"MISSION1_CLOSE_SHAVE": "Close shave",
	"MISSION1_THE_DOCKS": "The docks",
	"MISSION1_GRAND_FOYER": "Grand foyer",
	"MISSION1_CABIN_CORRIDOR": "Cabin corridor",
	"MISSION1_STEAM_ROOM": "Steam room",
	"MISSION1_SERVICE_CORRIDOR": "Service corridor",
	"MISSION1_SALON": "Salon",
	"MISSION1_WE_RE_AT_SEA_I_DON_T_WANT_TO_GO_OVERBOARD": "We're at sea. I don't want to go overboard.",
	"MISSION1_MUSIC": "Music",
	"MISSION1_COULD_NOT_CLEAR_MISSION_1_SAVE_D": "Could not clear Mission 1 save (%d)",
	"MISSION1_COULD_NOT_WRITE_VOYAGE_JOURNAL": "Could not write voyage journal.",
	"MISSION1_COULD_NOT_FLUSH_VOYAGE_JOURNAL": "Could not flush voyage journal.",
	"MISSION1_COULD_NOT_ROTATE_VOYAGE_BACKUP": "Could not rotate voyage backup.",
	"MISSION1_COULD_NOT_PROTECT_PREVIOUS_VOYAGE": "Could not protect previous voyage.",
	"MISSION1_COULD_NOT_PROMOTE_VOYAGE_JOURNAL": "Could not promote voyage journal.",
	"MISSION1_NO_VALID_MISSION_1_JOURNAL": "No valid Mission 1 journal.",
	"MISSION1_CLOSE_DOOR": "Close door",
	"MISSION1_OPEN_DOOR": "Open door",
	"MISSION1_RETRIEVE_BAG": "Retrieve bag",
	"MISSION1_HIDE_BAG": "Hide bag",
	"MISSION1_WELCOME_TO_GREECE_EXPLORE_THE_DOCK_RESTAURANT_MARKET_AND_SHIP": "Welcome to Greece. Explore the dock, restaurant, market and ship.",
	"MISSION1_A_NEW_DAY_ABOARD_EXPLORE_THE_SHIP": "A new day aboard. Explore the ship.",
	"MISSION1_THE_DOOR_IS_LOCKED": "The door is locked.",
	"MISSION1_SIX_HOURS_IN_GREECE_END_OF_THE_EXPLORATION_SCHEDULE": "Six hours in Greece. End of the exploration schedule.",
	"MISSION1_SIX_HOURS_ABOARD_END_OF_THE_EXPLORATION_SCHEDULE": "Six hours aboard. End of the exploration schedule.",
	"MISSION1_I_VISITED": "I visited ",
	"MISSION1_IS_IN": " is in ",
	"MISSION1_USE_CONTROLS": "Use controls",
	"MISSION1_MISSED_THE_BOAT_MISSION_FAILED_EVERYONE_SURVIVED_BUT_YOU_WERE_STI": "MISSED THE BOAT · MISSION FAILED\nEveryone survived, but you were still on the docks when the ship sailed. Turn back the pages and get aboard before 5:30.",
	"MISSION1_EVERYONE_SURVIVED_ALL_ABOARD_COMPLETE": "EVERYONE SURVIVED · ALL ABOARD COMPLETE\n",
	"MISSION1_THE_NEXT_PAGE_REVEALS_A_NEW_GIFT_LOCATION_REWRITING": "\nThe next page reveals a new gift: location rewriting.",
	"MISSION1_THE_PARTY_HAS_ENDED": "THE PARTY HAS ENDED\n",
	"MISSION1_YOUR_DIARY_RECORDS_WHAT_YOU_WITNESSED_ON_THIS_VOYAGE_TURN_BACK_TH": "\nYour diary records what you witnessed on this voyage. Turn back the pages to try again.",
	"MISSION1_HOUR": "Hour ",
	"MISSION1_HOLD_WAIT": "Hold Wait",
	"MISSION1_TAP_DIARY": "Tap Diary",
	"MISSION1_S_HIGHLIGHT": "%s — Highlight",
	"MISSION1_HOLD_S_WAIT": "Hold %s — Wait",
	"MISSION1_S_OPEN_DIARY": "%s — Open diary",
	"MISSION2_SERVICE_CORRIDOR_CREW_CABINS": "Service corridor · crew cabins",
	"MISSION2_FOREDECK": "Foredeck",
	"MISSION2_CREW_CABIN_DOOR": "Crew cabin door",
	"MISSION3_GREEK_DOCK": "Greek dock",
	"MISSION3_RESTAURANT_DINING_ROOM_AND_KITCHEN": "Restaurant · dining room and kitchen",
	"UI_GUEST_COUNT": "{count} guest",
	"UI_GUEST_COUNT_MANY": "{count} guests",
	"UI_LOADING_THE_VOYAGE_D": "Loading the voyage… %d%%",
	"UI_A_VOYAGE_BETWEEN_THE_PAGES": "A VOYAGE BETWEEN THE PAGES",
	"UI_THE_INCREDIBLE_DIARY": "THE INCREDIBLE DIARY",
	"UI_UNABLE_TO_LOAD_THE_DIARY_PLEASE_RESTART": "Unable to load the diary. Please restart.",
	"UI_LOADING_THE_DIARY_D": "Loading the diary… %d%%",
	"UI_MADE_WITH_GODOT": "MADE WITH GODOT",
	"UI_JSON_STRINGIFY_WINDOW_DIARY_CONTENT_NULL": "JSON.stringify(window.DIARY_CONTENT || null)",
	"UI_RESOURCE_DOWNLOADS_COULD_NOT_START_PLEASE_RELOAD_THE_PAGE": "Resource downloads could not start. Please reload the page.",
	"UI_A_RESOURCE_COULD_NOT_BE_PREPARED_PLEASE_TRY_AGAIN": "A resource could not be prepared. Please try again.",
	"UI_A_RESOURCE_COULD_NOT_BE_OPENED_PLEASE_TRY_AGAIN": "A resource could not be opened. Please try again.",
	"UI_THERE_IS_NOT_ENOUGH_SPACE_TO_OPEN_THIS_RESOURCE_PLEASE_TRY_AGAIN": "There is not enough space to open this resource. Please try again.",
	"UI_A_DOWNLOADED_RESOURCE_COULD_NOT_BE_OPENED_PLEASE_RELOAD_AND_TRY_A": "A downloaded resource could not be opened. Please reload and try again.",
	"UI_INSPECT": "Inspect",
	"UI_TALK": "Talk",
	"UI_HIDE_BAG": "Hide Bag",
	"UI_STEAM_CONTROL": "STEAM CONTROL",
	"UI_A_NEW_ENTRY_HAS_APPEARED_IN_THE_DIARY": "A new entry has appeared in the diary.",
	"UI_OBSERVATIONS_ARE_RECORDED_HERE_AS_YOU_EXPLORE": "Observations are recorded here as you explore.",
	"UI_A_PASSENGER_DEAD_ABOARD_MY_SHIP_I_CAN_T_SAIL_AFTER_THIS_THE_VOYAG": "A passenger dead aboard my ship... I can't sail after this. The voyage will have to be cancelled!",
	"UI_5_30_ALL_ABOARD_CAST_OFF": "5:30 — All aboard. Cast off!",
	"UI_5_30_THE_VOYAGE_IS_CANCELLED": "5:30 — The voyage is cancelled",
	"UI_HOUR_D": "HOUR %d",
	"UI_VOYAGE_SUMMARY": "VOYAGE SUMMARY",
	"UI_THE_SIX_HOURS_HAVE_ENDED": "The six Hours have ended.",
	"UI_ONLY_WHAT_AMELIA_WITNESSED_IS_RECORDED_HERE": "Only what Amelia witnessed is recorded here.",
	"UI_PASSENGER": "Passenger",
	"UI_WE_SHOULD_LOOK_MORE_CLOSELY": "We should look more closely.",
	"UI_WAITING_20": "Waiting · 20×",
	"UI_NEW_URLSEARCHPARAMS_LOCATION_SEARCH_HAS_GITHUB_INTEGRATION_TEST_N": "new URLSearchParams(location.search).has('github_integration_test') && new URLSearchParams(location.search).get('github_web_smoke') === 'read'",
	"UI_VOYAGE_COMPLETE": "Voyage complete",
	"UI_VOYAGE_ENDED": "Voyage ended",
	"UI_MISSION_FAILED_MISSED_THE_BOAT": "Mission failed — missed the boat",
	"UI_ALL_ABOARD_S_S": "All Aboard · %s\r\n%s",
	"UI_THE_SAVED_VOYAGE_COULD_NOT_BE_LOADED_ITS_FILES_HAVE_BEEN_KEPT": "The saved voyage could not be loaded. Its files have been kept.",
	"UI_DEV_MENU": "Dev Menu",
	"UI_MISSION_1_ALL_ABOARD": "Mission 1 — All Aboard",
	"UI_MISSION_2": "Mission 2",
	"UI_MISSION_3_LANDING_IN_GREECE": "Mission 3 — Landing in Greece",
	"UI_TEST_LEVEL": "Test Level",
	"UI_WINDOW_DIARYTITLEREADY_TRUE_WINDOW_DISPATCHEVENT_NEW_EVENT_DIARY": "window.diaryTitleReady = true; window.dispatchEvent(new Event('diary-title-ready'));",
	"UI_DIARY": "Diary",
	"UI_WAIT": "Wait",
	"UI_HIGHLIGHT": "Highlight",
	"UI_CANCEL": "Cancel",
	"UI_NAVIGATOR_MAXTOUCHPOINTS_0_MATCHMEDIA_POINTER_COARSE_MATCHES": "navigator.maxTouchPoints > 0 && matchMedia('(pointer: coarse)').matches",
	"UI_MATCHMEDIA_ORIENTATION_PORTRAIT_MATCHES": "matchMedia('(orientation: portrait)').matches",
	"UI_MASTER": "Master",
	"UI_DIALOGUE": "Dialogue",
	"UI_PREFERENCES_COULD_NOT_BE_SAVED_CHANGES_WORK_FOR_THIS_SESSION_CLOS": "Preferences could not be saved. Changes work for this session; closing Settings retries.",
	"UI_THE_GAME_COULD_NOT_BE_SAVED_YOU_ARE_STILL_IN_THE_CURRENT_GAME_TRY": "The game could not be saved. You are still in the current game; try again.",
	"UI_THE_MAIN_MENU_COULD_NOT_BE_OPENED_PLEASE_TRY_AGAIN": "The main menu could not be opened. Please try again.",
	"UI_SETTINGS": "Settings",
	"UI_CLOSE": "Close",
	"UI_AUDIO": "Audio",
	"UI_MASTER_VOLUME": "Master volume",
	"UI_CONTROLS": "Controls",
	"UI_MOVEMENT_JOYSTICK_POSITION": "Movement joystick position",
	"UI_BUTTONS_APPEAR_ON_THE_OPPOSITE_SIDE": "Buttons appear on the opposite side.",
	"UI_CLEAR_S_S_BINDING": "Clear %s %s binding",
	"UI_RESTORE_S_DEFAULTS": "Restore %s defaults",
	"UI_CANCEL_BINDING": "Cancel binding",
	"UI_ASSIGN_ANYWAY": "Assign anyway",
	"UI_PRIMARY": "Primary",
	"UI_ALTERNATE": "Alternate",
	"UI_RELEASE_HELD_INPUTS_THEN_PRESS_A_S_INPUT_10_SECONDS": "Release held inputs, then press a %s input (10 seconds).",
	"UI_BINDING_CANCELLED_NO_INPUT_RECEIVED": "Binding cancelled: no input received.",
	"UI_ALREADY_ASSIGNED_TO_S_ASSIGN_ANYWAY": "Already assigned to: %s. Assign anyway?",
	"UI_MOVE_LEFT": "Move left",
	"UI_MOVE_RIGHT": "Move right",
	"UI_MOVE_UP": "Move up",
	"UI_MOVE_DOWN": "Move down",
	"UI_WAIT_HOLD": "Wait (hold)",
	"UI_OPEN_CLOSE_DIARY": "Open/close diary",
	"UI_RESET_LOOP": "Reset loop",
	"UI_CANCEL_ACTION": "Cancel action",
	"UI_INTERACTION_1": "Interaction 1",
	"UI_INTERACTION_2": "Interaction 2",
	"UI_INTERACTION_3": "Interaction 3",
	"UI_INTERACTION_4": "Interaction 4",
	"UI_INTERACTION_5": "Interaction 5",
	"UI_INTERACTION_6": "Interaction 6",
	"UI_INTERACTION_7": "Interaction 7",
	"UI_INTERACTION_8": "Interaction 8",
	"UI_CONFIRM_SELECTED_INTERACTION": "Confirm selected interaction",
	"UI_SUBMIT_CODE": "Submit code",
	"UI_CLEAR_CODE": "Clear code",
	"UI_CONTINUE_AFTER_ENDING": "Continue after ending",
	"UI_PREVIOUS_DIARY_PAGE": "Previous diary page",
	"UI_NEXT_DIARY_PAGE": "Next diary page",
	"UI_THIS_KEY_IS_RESERVED_FOR_PAUSE_EDITOR_CONTROLS": "This key is reserved for pause/editor controls.",
	"UI_THIS_BUTTON_IS_RESERVED_FOR_SETTINGS_OR_PAUSE_EDITOR_CONTROLS": "This button is reserved for Settings or pause/editor controls.",
	"UI_D_PAD_UP": "D-pad Up",
	"UI_D_PAD_DOWN": "D-pad Down",
	"UI_D_PAD_LEFT": "D-pad Left",
	"UI_D_PAD_RIGHT": "D-pad Right",
	"UI_BUTTON_D": "Button %d",
	"UI_SPOKEN_LINE": "{speaker}: {line}",
	"UI_LANGUAGE": "Language",
	"UI_AUTOMATIC": "Automatic",
	"UI_ENGLISH": "English",
	"UI_LOADING_PREPARING": "Preparing the diary…",
	"UI_LOADING_OPENING": "Opening the diary…",
	"UI_LOADING_PROGRESS": "Loading the diary… {percent}%",
	"UI_LOADING_FAILED": "The diary could not be opened.",
	"UI_LOADING_UNKNOWN": "An unknown error occurred.",
	"UI_LOADING_UNSUPPORTED": "Your browser does not support the features needed to open the diary.",
	"UI_CARRYING": "Carrying: {item}",
	"UI_MISSION_HEADING": "Mission {number}  ·  {room}",
	"UI_VOYAGE_HEADING": "All Aboard  ·  {room}",
	"UI_CONTINUE": "CONTINUE",
	"UI_NEW": "NEW",
	"UI_QUIT": "QUIT",
	"UI_START_A_NEW_VOYAGE": "Start a new voyage?",
	"UI_STARTING_NEW_WILL_PERMANENTLY_CLEAR_THE_CURRENT_MISSION_1_SAVE_AN": "Starting New will permanently clear the current Mission 1 save and its recorded history. Continue?",
	"UI_CLEAR_SAVE_AND_START": "Clear save and start",
	"UI_VOYAGE_UNAVAILABLE": "Voyage unavailable",
	"UI_GET_DRINK": "Get {drink}",
	"UI_PREFERS_DRINK": "Prefers {drink}",
	"UI_OFFER_DRINK": "Offer {drink}",
	"UI_VISITED_ROOM": "I visited {room}.",
	"UI_ACTOR_ROOM": "{actor} is in {room}.",
	"UI_ACTION_BINDING": "{binding}  {action}",
	"UI_MARKET": "Market",
	"UI_LEMONADE": "Lemonade",
	"UI_WINE": "Wine",
	"UI_CHAMPAGNE": "Champagne",
	"UI_BRANDY": "Brandy",
	"UI_WHISKY": "Whisky",
	"UI_CLEAR": "Clear",
	"UI_ENTER": "Enter",
	"UI_UNBOUND": "Unbound",
	"UI_CONTROLLER": "Controller",
	"UI_KEYBOARD": "Keyboard",
	"UI_TOUCH": "Touch",
	"UI_SFX": "SFX",
	"UI_SUMMARY_SURVIVED": "{name}: survived",
	"UI_SUMMARY_DIED": "{name}: died",
	"UI_SUMMARY_SUCCESS": "EVERYONE SURVIVED · ALL ABOARD COMPLETE\r\n{outcomes}\r\nThe next page reveals a new gift: location rewriting.",
	"UI_SUMMARY_FAILED": "THE PARTY HAS ENDED\r\n{outcomes}\r\nYour diary records what you witnessed on this voyage. Turn back the pages to try again.",
	"UI_DIARY_OUTCOME": "5:30 · The unmooring party is over.\r\n\r\n{summary}",
	"UI_SETTINGS_UPPER": "SETTINGS",
	"UI_CONTROL_LEFT": "Left",
	"UI_CONTROL_RIGHT": "Right",
	"UI_CONTROL_KEYBOARD": "keyboard",
	"UI_CONTROL_CONTROLLER": "controller",
	"UI_CONTROL_TOUCH": "touch",
	"UI_CONTROL_PRIMARY": "primary",
	"UI_CONTROL_ALTERNATE": "alternate",
	"UI_CONTROL_ABOARD": "aboard",
	"UI_BINDING_SLOT": "{slot}: {binding}",
	"UI_BINDING_TOOLTIP": "{action} — {slot}: {binding}",
	"UI_GENERAL": "General",
	"UI_CONFIRM": "CONFIRM",
	"UI_PEOPLE": "PEOPLE",
	"UI_MOVE": "Move",
	"UI_TEA": "Tea",
	"UI_ACCESSIBILITY": "Accessibility",
	"UI_HIGH_CONTRAST_TEXT_PANELS": "High-contrast text panels",
	"UI_INSTANT_DIALOGUE_TEXT": "Instant dialogue text",
	"UI_STEAM_ON": "On",
	"UI_STEAM_OFF": "Off",
	"UI_STOP_WAITING": "Stop",
	"UI_WAIT_TOGGLE": "Wait (toggle)",
	"MISSION1_TOGGLE_B_WAIT": "B — Toggle Wait",
	"MISSION1_TOGGLE_F_WAIT": "F — Toggle Wait",
	"MISSION1_TAP_WAIT": "Tap Wait to start/stop",
	"MISSION1_TOGGLE_S_WAIT": "%s — Toggle Wait"
}
const ENGLISH = {
	"MISSION1_BOY": "Boy",
	"MISSION1_MR_FELIX_HARCOURT": "Mr. Felix Harcourt",
	"MISSION1_MISS_EVELYN_VALE": "Miss Evelyn Vale",
	"MISSION1_MRS_MABEL_PRITCHARD": "Mrs. Mabel Pritchard",
	"MISSION1_SAILOR": "Sailor",
	"MISSION1_CAPTAIN": "Captain",
	"MISSION1_PORTER": "Porter",
	"MISSION1_GUEST": "Guest",
	"MISSION1_UNSUPPORTED_MISSION_1_CONTENT_SCHEMA": "Unsupported Mission 1 content schema",
	"MISSION1_S_MUST_BE_AN_OBJECT": "{arg1} must be an object",
	"MISSION1_S_MUST_BE_A_LIST": "{arg1} must be a list",
	"MISSION1_THE_PLAYER_ENTITY_AMELIA_IS_REQUIRED": "The player entity amelia is required",
	"MISSION1_MISSION_1_OPERATIONS_STILL_REFERENCE_CHARACTER": "Mission 1 operations still reference character ",
	"MISSION1_ROOM_S_NEEDS_DIMENSIONS_AND_COLLISION_CELLS": "Room {arg1} needs dimensions and collision cells",
	"MISSION1_ROOM_S_DIMENSIONS_MUST_BE_1_10000": "Room {arg1} dimensions must be 1–10000",
	"MISSION1_ROOM_S_COLLISION_CELLS_MUST_USE_INTEGER_X_Y_KEYS_AND_TRUE_VALUES": "Room {arg1} collision cells must use integer x,y keys and true values",
	"MISSION1_ROOM_S_BACKGROUND_ASSET_IS_MISSING": "Room {arg1} background asset is missing",
	"MISSION1_TEMPLATE_S_HAS_AN_INVALID_ENTITY_KIND": "Template {arg1} has an invalid entity kind",
	"MISSION1_TEMPLATE_S_HAS_INVALID_STATE_RULES": "Template {arg1} has invalid state rules",
	"MISSION1_TEMPLATE_S_STATES_MUST_BE_OBJECTS": "Template {arg1} states must be objects",
	"MISSION1_TEMPLATE_S_HAS_AN_INVALID_TRANSITION": "Template {arg1} has an invalid transition",
	"MISSION1_ENTITY_S_NEEDS_A_POSITION_AND_OVERRIDES": "Entity {arg1} needs a position and overrides",
	"MISSION1_ENTITY_S_TEMPLATE_IS_MISSING": "Entity {arg1} template is missing",
	"MISSION1_ENTITY_S_ROOM_IS_MISSING": "Entity {arg1} room is missing",
	"MISSION1_ENTITY_S_HAS_AN_UNKNOWN_APPEARANCE": "Entity {arg1} has an unknown appearance",
	"MISSION1_ENTITY_S_STATE_OVERRIDES_ARE_INVALID": "Entity {arg1} state overrides are invalid",
	"MISSION1_ENTITY_S_TRANSITION_TARGET_IS_MISSING": "Entity {arg1} transition target is missing",
	"MISSION1_ENTITY_S_INTERACTIONS_MUST_BE_A_LIST": "Entity {arg1} interactions must be a list",
	"MISSION1_ENTITY_S_HAS_AN_INVALID_INTERACTION_POSITION": "Entity {arg1} has an invalid interaction position",
	"MISSION1_INTERACTION_DURATION_MUST_BE_POSITIVE": "Interaction duration must be positive",
	"MISSION1_ENTITY_S_INTERACTION_IS_BLOCKED_BY_AUTHORED_COLLISION": "Entity {arg1} interaction is blocked by authored collision",
	"MISSION1_A_ROOM_CONNECTION_HAS_MISSING_ENDPOINTS": "A room connection has missing endpoints",
	"MISSION1_CONNECTION_ENDPOINT_IN_S_IS_BLOCKED": "Connection endpoint in {arg1} is blocked",
	"MISSION1_SCHEDULE_S_ACTOR_IS_MISSING": "Schedule {arg1} actor is missing",
	"MISSION1_SCHEDULE_S_NEEDS_COMMITMENTS": "Schedule {arg1} needs commitments",
	"MISSION1_SCHEDULE_S_HAS_AN_INVALID_COMMITMENT": "Schedule {arg1} has an invalid commitment",
	"MISSION1_SCHEDULE_S_NEEDS_AN_ORIGIN_AND_STAGES": "Schedule {arg1} needs an origin and stages",
	"MISSION1_SCHEDULE_S_HAS_AN_INVALID_STAGE": "Schedule {arg1} has an invalid stage",
	"MISSION1_STORYLET_NEEDS_AN_ID_CONDITIONS_AND_EFFECTS": "Storylet needs an ID, conditions and effects",
	"MISSION1_STORYLET_S_HAS_INVALID_TIMING_OR_PARTICIPANTS": "Storylet {arg1} has invalid timing or participants",
	"MISSION1_STORYLET_S_SCENE_IS_MISSING": "Storylet {arg1} scene is missing",
	"MISSION1_STORYLET_S_ACTOR_S_IS_MISSING": "Storylet {arg1} actor {arg2} is missing",
	"MISSION1_STORYLET_S_HAS_AN_UNSUPPORTED_COMMAND": "Storylet {arg1} has an unsupported command",
	"MISSION1_UNSUPPORTED_MISSION_1_OPERATION": "Unsupported Mission 1 operation",
	"MISSION1_FLAG_COMMAND_NEEDS_A_KEY": "Flag command needs a key",
	"MISSION1_PROP_COMMAND_NEEDS_AN_ENTITY_AND_STATE": "Prop command needs an entity and state",
	"MISSION1_SAY_COMMAND_NEEDS_AN_ACTOR_AND_TEXT": "Say command needs an actor and text",
	"MISSION1_NOTE_COMMAND_NEEDS_A_KEY_AND_TEXT": "Note command needs a key and text",
	"MISSION1_STORYLET_CONDITIONS_MUST_BE_OBJECTS": "Storylet conditions must be objects",
	"MISSION1_TIMING_S_MUST_BE_WITHIN_THE_LEG": "Timing {arg1} must be within the leg",
	"MISSION1_ASSET_S_S": "Asset {arg1}: {arg2}",
	"MISSION1_SCENE_S_MUST_BE_SOURCE_TEXT": "Scene {arg1} must be source text",
	"MISSION1_ENTITY_S_INTERACTION_HAS_NO_ROUTE_FROM_THE_PLAYER_START": "Entity {arg1} interaction has no route from the player start",
	"MISSION1_SCHEDULE_S_DESTINATION_HAS_NO_CONNECTED_ROUTE": "Schedule {arg1} destination has no connected route",
	"MISSION1_CONDITIONS_MUST_BE_A_LIST": "Conditions must be a list",
	"MISSION1_CONDITION_MUST_BE_AN_OBJECT": "Condition must be an object",
	"MISSION1_UNKNOWN_CONDITION_USE_FLAG_HAS_FLAG_ACTOR_PROP_SAFE_DEAD_OR_DISTA": "Unknown condition; use flag, has_flag, actor, prop, safe, dead or distance",
	"MISSION1_CONDITION_REFERENCES_MISSING_ENTITY": "Condition references missing entity ",
	"MISSION1_DISTANCE_CONDITION_NEEDS_TWO_ENTITIES_AND_A_MAXIMUM_DISTANCE": "Distance condition needs two entities and a maximum distance",
	"MISSION1_EFFECTS_MUST_BE_A_LIST": "Effects must be a list",
	"MISSION1_EFFECT_MUST_BE_AN_OBJECT": "Effect must be an object",
	"MISSION1_FLAG_EFFECT_NEEDS_A_KEY": "Flag effect needs a key",
	"MISSION1_PROP_EFFECT_NEEDS_AN_ENTITY_AND_STATE": "Prop effect needs an entity and state",
	"MISSION1_PROP_EFFECT_REFERENCES_AN_UNKNOWN_STATE": "Prop effect references an unknown state",
	"MISSION1_SAY_EFFECT_NEEDS_AN_ACTOR_AND_TEXT": "Say effect needs an actor and text",
	"MISSION1_NOTE_EFFECT_NEEDS_A_KEY_AND_TEXT": "Note effect needs a key and text",
	"MISSION1_UNKNOWN_MISSION_1_OPERATION": "Unknown Mission 1 operation",
	"MISSION1_UNKNOWN_EFFECT_COMMAND": "Unknown effect command",
	"MISSION1_MY_SUITCASE_AT_LAST_THANK_YOU": "My suitcase! At last. Thank you.",
	"MISSION1_MY_SUIT_DO_WATCH_WHERE_YOU_ARE_GOING": "My suit! Do watch where you are going!",
	"MISSION1_I_WANTED_TO_APOLOGISE_ABOUT_YOUR_DRINK_SIR": "I wanted to apologise about your drink, sir.",
	"MISSION1_YOU_RUINED_MY_SUIT_I_HAVE_NO_INTEREST_IN_YOUR_EXCUSES_NOW_LEAVE_M": "You ruined my suit. I have no interest in your excuses. Now leave me alone.",
	"MISSION1_HOW_DARE_YOU_WHAT_DO_YOU_THINK_YOU_ARE_DOING": "How dare you! What do you think you are doing?",
	"MISSION1_BEFORE_YOU_GO_YOU_MUST_HEAR_ABOUT_MY_NEPHEW": "Before you go, you must hear about my nephew.",
	"MISSION1_COULD_IT_WAIT_THEY_ARE_SERVING_DRINKS": "Could it wait? They are serving drinks.",
	"MISSION1_HE_BOUGHT_A_MOTORCAR_WITHOUT_ASKING_HIS_MOTHER": "He bought a motorcar. Without asking his mother!",
	"MISSION1_HOW_VERY_RASH": "How very rash.",
	"MISSION1_THAT_IS_EXACTLY_WHAT_I_SAID_NOW_LISTEN": "That is exactly what I said. Now, listen…",
	"MISSION1_HELP_THE_STEAM_HAS_CUT_OFF_THE_PASSAGE": "Help! The steam has cut off the passage!",
	"MISSION1_WHERE_ARE_MY_BAGS_I_WILL_NOT_BOARD_WITHOUT_THEM": "Where are my bags? I will not board without them!",
	"MISSION1_I_LL_SEARCH_THE_LUGGAGE_SIR": "I'll search the luggage, sir.",
	"MISSION1_BROWN_LEATHER_WITH_MY_INITIALS": "Brown leather. With my initials.",
	"MISSION1_STAY_HERE_I_LL_BRING_THEM_OVER": "Stay here. I'll bring them over.",
	"MISSION1_MY_BROWN_SUITCASE_IS_STILL_MISSING_I_M_WAITING_HERE": "My brown suitcase is still missing. I'm waiting here.",
	"MISSION1_BOY_REPORT_FOR_DUTY": "Boy! Report for duty.",
	"MISSION1_YES_CAPTAIN": "Yes, Captain.",
	"MISSION1_EXPLORE_THE_SHIP_AND_MAKE_SURE_OUR_GUESTS_ARE_COMFORTABLE_HELP_WI": "Explore the ship and make sure our guests are comfortable. Help with their luggage, bring refreshments, and show them to their cabins.",
	"MISSION1_VERY_GOOD_CAPTAIN": "Very good, Captain.",
	"MISSION1_PASSENGERS_ARE_COMING_ABOARD_GET_TO_IT": "Passengers are coming aboard. Get to it.",
	"MISSION1_WHICH_WAY_TO_THE_SALON": "Which way to the Salon?",
	"MISSION1_UP_THE_CENTRE_STAIR_MADAM": "Up the centre stair, madam.",
	"MISSION1_A_LOVELY_EVENING_FOR_A_DEPARTURE": "A lovely evening for a departure.",
	"MISSION1_PROVIDED_THE_SEA_REMEMBERS_ITS_MANNERS": "Provided the sea remembers its manners.",
	"MISSION1_ARE_YOU_SETTLING_INTO_YOUR_CABIN": "Are you settling into your cabin?",
	"MISSION1_AT_LAST_I_THOUGHT_MY_LUGGAGE_HAD_TAKEN_ITS_OWN_HOLIDAY": "At last. I thought my luggage had taken its own holiday.",
	"MISSION1_A_NEW_POSTING_AN_UNMOORING_PARTY_WHAT_COULD_POSSIBLY_GO_WRONG": "A new posting. An unmooring party. What could possibly go wrong?",
	"MISSION1_REPORT_FOR_DUTY": "Report for duty",
	"MISSION1_INSPECT_LUGGAGE": "Inspect luggage",
	"MISSION1_ACTION_INTERRUPTED_UNFINISHED_PROGRESS_LOST": "Action interrupted. Unfinished progress lost.",
	"MISSION1_THE_UNMOORING_PARTY_HAS_ENDED": "The unmooring party has ended.",
	"MISSION1_I_OPENED_THE_CABIN_DOOR": "I opened the cabin door.",
	"MISSION1_I_CLOSED_THE_CABIN_DOOR": "I closed the cabin door.",
	"MISSION1_THE_SAME_MONOGRAM_HE_STILL_REFUSES_TO_BOARD_WITHOUT_THIS_BAG": "The same monogram. He still refuses to board without this bag.",
	"MISSION1_A_MONOGRAMMED_SUITCASE_TUCKED_AMONG_THE_TRUNKS": "A monogrammed suitcase tucked among the trunks.",
	"MISSION1_I_TUCKED_THE_SUITCASE_BEHIND_THE_BAGGAGE_SCREEN": "I tucked the suitcase behind the baggage screen.",
	"MISSION1_I_BROUGHT_THE_SUITCASE_BACK_TO_ITS_OWNER": "I brought the suitcase back to its owner.",
	"MISSION1_PORTER_THE_CENTRE_STAIR_IS_ONLY_LATCHED_RELEASE_THE_BRASS_CATCH_A": "Porter: The centre stair is only latched. Release the brass catch at its foot.",
	"MISSION1_I_RELEASED_THE_LATCH_THE_CENTRE_STAIR_LEADS_STRAIGHT_TO_THE_SALON": "I released the latch. The centre stair leads straight to the salon.",
	"MISSION1_STEAM_BLOCKS_THE_FAR_ROOM_S_NORMAL_EXIT_THE_TALKATIVE_PASSENGER_I": "Steam blocks the far room's normal exit. The talkative passenger is trapped.",
	"MISSION1_THE_PASSENGER_COLLAPSED_BEHIND_THE_STEAM": "The passenger collapsed behind the steam.",
	"MISSION1_CREW_A_PASSENGER_NEEDS_HELP_IN_THE_STEAM_PASSAGE": "Crew: A passenger needs help in the steam passage!",
	"MISSION1_THE_CHANDELIER_CREAKS_AND_TREMBLES_ABOVE_THE_GUEST": "The chandelier creaks and trembles above the guest.",
	"MISSION1_THE_CHANDELIER_FELL_ON_THE_GUEST": "The chandelier fell on the guest.",
	"MISSION1_THE_CHANDELIER_CRASHED_ONTO_THE_PLACE_WHERE_THE_GUEST_HAD_BEEN_ST": "The chandelier crashed onto the place where the guest had been standing.",
	"MISSION1_THE_DIARY_SHIVERS": "The diary shivers.",
	"MISSION1_YOU_FOUND_THE_BAG_THANK_YOU_BOY_SAVED_ME_A_SEARCH": "You found the bag! Thank you, Boy. Saved me a search.",
	"MISSION1_THE_STAIR_S_BRASS_CATCH_IS_STILL_HERE": "The stair's brass catch is still here.",
	"MISSION1_I_DO_WISH_THEY_WOULD_GET_ON_WITH_IT_SUCH_A_WAIT": "I do wish they would get on with it. Such a wait!",
	"MISSION1_BUMP_INTO_GUEST": "Bump into guest",
	"MISSION1_INSPECT_GLASS": "Inspect glass",
	"MISSION1_INSPECT_WRECKAGE": "Inspect wreckage",
	"MISSION1_MY_ELBOW_CAUGHT_THE_GLASS_HIS_DRINK_SOAKED_HIS_SUIT": "My elbow caught the glass. His drink soaked his suit.",
	"MISSION1_A_SHARP_CHEMICAL_RESIDUE_IN_THE_GLASS_THE_DRINK_WAS_POISONED_NOTH": "A sharp chemical residue in the glass. The drink was poisoned; nothing here identifies who did it.",
	"MISSION1_I_SHOVED_THE_GUEST_OUT_FROM_BENEATH_THE_CHANDELIER": "I shoved the guest out from beneath the chandelier.",
	"MISSION1_SHE_IS_DEAD_BENEATH_THE_CHANDELIER_BROKEN_GLASS_EVERYWHERE_AND_A": "She is dead, beneath the chandelier. Broken glass everywhere, and a snapped suspension pin.",
	"MISSION1_BROKEN_GLASS_AND_A_SNAPPED_SUSPENSION_PIN_THANK_GOODNESS_I_GOT_HE": "Broken glass and a snapped suspension pin. Thank goodness I got her out of the way.",
	"MISSION1_THE_LUGGAGE_OWNER_IS_WAITING_AT_THE_BAR": "The luggage owner is waiting at the bar.",
	"MISSION1_THE_LUGGAGE_OWNER_HAS_COLLAPSED_BESIDE_HIS_GLASS": "The luggage owner has collapsed beside his glass.",
	"MISSION1_THE_PASSENGER_LIES_MOTIONLESS_BEYOND_THE_STEAM_LEAK": "The passenger lies motionless beyond the steam leak.",
	"MISSION1_THE_GUEST_LIES_DEAD_BENEATH_THE_FALLEN_CHANDELIER": "The guest lies dead beneath the fallen chandelier.",
	"MISSION1_THE_FALLEN_CHANDELIER_LIES_IN_PIECES_THE_GUEST_IS_SAFE": "The fallen chandelier lies in pieces. The guest is safe.",
	"MISSION1_THE_PASSENGER_LEAVES_THROUGH_THE_CLEARED_STEAM_PASSAGE": "The passenger leaves through the cleared steam passage.",
	"MISSION1_THE_PASSENGER_EMERGES_FROM_THE_STEAM_ROOM": "The passenger emerges from the steam room.",
	"MISSION1_AN_OBSCURED_HAND_TIPS_SOMETHING_INTO_THE_GUEST_S_GLASS": "An obscured hand tips something into the guest's glass.",
	"MISSION1_THE_GUEST_DRANK_THEN_COLLAPSED_BESIDE_THE_POISONED_GLASS": "The guest drank, then collapsed beside the poisoned glass.",
	"MISSION1_PRESSURE_MUST_BE_RUNNING_FOR_THE_CONTROLS_TO_RESPOND": "Pressure must be running for the controls to respond.",
	"MISSION1_ENTER_THREE_DIGITS_THEN_PRESS_COMMIT_CLEAR_STARTS_YOUR_ENTRY_AGAI": "Enter three digits, then press Commit. Clear starts your entry again.",
	"MISSION1_TODAY_S_SHUTOFF_CODE_IS_S": "Today's shutoff code is {arg1}.",
	"MISSION1_CODE_REJECTED_CLEAR_AND_TRY_AGAIN": "Code rejected. Clear and try again.",
	"MISSION1_I_STOPPED_THE_STEAM": "I stopped the steam.",
	"MISSION1_FOUND_IT_BROWN_LEATHER_JUST_AS_YOU_SAID": "Found it! Brown leather, just as you said.",
	"MISSION1_LOOP_D_HOUR": "Loop {arg1} · Hour ",
	"MISSION1_THE_PASSAGE_IS_CLEAR_THE_PASSENGER_STARTS_TOWARDS_THE_EXIT": "The passage is clear. The passenger starts towards the exit.",
	"MISSION1_CONTENT_APPLIED": "Content applied",
	"MISSION1_SPARKLING_WATER": "Sparkling water",
	"MISSION1_LEMONADE_PLEASE_BOY": "Lemonade, please, Boy.",
	"MISSION1_EXCELLENT_LEMONADE_BOY_THANK_YOU": "Excellent lemonade, Boy. Thank you.",
	"MISSION1_I_ASKED_FOR_LEMONADE_BOY_DO_TRY_TO_REMEMBER": "I asked for lemonade, Boy. Do try to remember.",
	"MISSION1_SPARKLING_WATER_PLEASE_BOY": "Sparkling water, please, Boy.",
	"MISSION1_JUST_WHAT_I_WANTED_THANK_YOU_BOY": "Just what I wanted. Thank you, Boy.",
	"MISSION1_THAT_ISN_T_SPARKLING_WATER_PERHAPS_SOMEONE_ELSE_ORDERED_IT": "That isn't sparkling water. Perhaps someone else ordered it?",
	"MISSION1_A_PROPER_CUP_OF_TEA_PLEASE_BOY": "A proper cup of tea, please, Boy.",
	"MISSION1_LOVELY_A_PROPER_CUP_OF_TEA_THANK_YOU_BOY": "Lovely. A proper cup of tea. Thank you, Boy.",
	"MISSION1_TEA_BOY_A_PROPER_CUP_OF_TEA": "Tea, Boy. A proper cup of tea.",
	"MISSION1_INSPECT_NAMEPLATE": "Inspect nameplate",
	"MISSION1_ASK_ABOUT_DRINKS": "Ask about drinks",
	"MISSION1_GIVE_CABIN_DIRECTIONS": "Give cabin directions",
	"MISSION1_CABIN_D_S": "Cabin {arg1} — {arg2}",
	"MISSION1_CABIN_D_THANK_YOU_BOY": "Cabin {arg1}. Thank you, Boy.",
	"MISSION1_CABIN_D_YOU_SAY_VERY_WELL_BOY": "Cabin {arg1}, you say? Very well, Boy.",
	"MISSION1_THIS_IS_S_S_CABIN_YOU_SENT_ME_TO_THE_WRONG_DOOR_BOY": "This is {arg1}'s cabin! You sent me to the wrong door, Boy.",
	"MISSION1_S_HOW_CURIOUS_BOY_I_SEEM_TO_HAVE_BECOME_SOMEBODY_ELSE": "{arg1}? How curious, Boy. I seem to have become somebody else.",
	"MISSION1_THE_PLATE_SAYS_S_READ_THE_NAMES_PROPERLY_NEXT_TIME_BOY": "The plate says {arg1}! Read the names properly next time, Boy.",
	"MISSION1_OH_HOW_DREADFUL_THAT_POOR_WOMAN": "Oh, how dreadful. That poor woman.",
	"MISSION1_SHE_WAS_STANDING_HERE_A_MOMENT_AGO_SOMEONE_MUST_FETCH_THE_CAPTAIN": "She was standing here a moment ago. Someone must fetch the captain.",
	"MISSION1_HE_S_DEAD_WHAT_A_TERRIBLE_END_TO_THE_PARTY": "He's dead! What a terrible end to the party.",
	"MISSION1_HE_WAS_RATHER_A_BORE_STILL_NOBODY_DESERVES_THIS": "He was rather a bore. Still, nobody deserves this.",
	"MISSION1_SHE_S_DEAD_I_LL_STAY_WITH_HER_UNTIL_HELP_ARRIVES": "She's dead. I'll stay with her until help arrives.",
	"MISSION1_WHY_HAS_THIS_BEEN_SWITCHED_OFF": "Why has this been switched off?",
	"MISSION1_I_WONDER_WHAT_I_SHOULD_DO": "I wonder what I should do?",
	"MISSION1_HURRY_UP_AND_WAIT": "Hurry up and wait…",
	"MISSION1_SOMETHING_HAS_CHANGED_IN_THE_DIARY_I_SHOULD_OPEN_IT": "Something has changed in the diary. I should open it.",
	"MISSION1_WHAT_A_TRAGEDY_HMMM_MY_DIARY_IS_SHAKING_I_FEEL_LIKE_I_SHOULD_TAKE": "What a tragedy. Hmmm, my diary is shaking, I feel like I should take a look.",
	"MISSION1_TAP_HIGHLIGHT": "Tap Highlight",
	"MISSION1_A_HIGHLIGHT": "A — Highlight",
	"MISSION1_HOLD_B_WAIT": "Hold B — Wait",
	"MISSION1_Y_OPEN_DIARY": "Y — Open diary",
	"MISSION1_H_HIGHLIGHT": "H — Highlight",
	"MISSION1_HOLD_F_WAIT": "Hold F — Wait",
	"MISSION1_TAB_OPEN_DIARY": "Tab — Open diary",
	"MISSION1_TIME_WINDOW": "time window",
	"MISSION1_NOT_ALREADY_COMPLETED": "not already completed",
	"MISSION1_PARTICIPANT": "participant ",
	"MISSION1_RESTART_REQUIRED_ACTIVE_ENTITY_S_WAS_REMOVED": "Restart required: active entity {arg1} was removed",
	"MISSION1_RESTART_REQUIRED_S_OCCUPIES_CHANGED_COLLISION_GEOMETRY": "Restart required: {arg1} occupies changed collision geometry",
	"MISSION1_RESTART_REQUIRED_S_STARTING_PLACEMENT_CHANGED": "Restart required: {arg1} starting placement changed",
	"MISSION1_RESTART_REQUIRED_ACTIVE_SCENE_S_CHANGED": "Restart required: active scene {arg1} changed",
	"MISSION1_RESTART_REQUIRED_ACTIVE_PARTICIPANT_S_CHANGED": "Restart required: active participant {arg1} changed",
	"MISSION1_THOUGHT": "Thought",
	"MISSION1_UNKNOWN_MISSION_1_SOUND_CUE_S": "Unknown Mission 1 sound cue: {arg1}",
	"MISSION1_CABIN_D": "Cabin {arg1}",
	"MISSION1_BACK": "Back",
	"MISSION1_GET": "Get ",
	"MISSION1_RETURN_DRINK": "Return drink",
	"MISSION1_PREFERS": "Prefers ",
	"MISSION1_OFFER": "Offer ",
	"MISSION1_VOYAGE_NOTEBOOK": "VOYAGE NOTEBOOK",
	"MISSION1_THE_VOYAGE": "THE VOYAGE",
	"MISSION1_OBSERVATIONS_FROM_THE_CURRENT_VOYAGE_RECORDED_AS_THEY_HAPPEN": "Observations from the current voyage, recorded as they happen.",
	"MISSION1_CLOSE_DIARY_S_S": "Close diary ({arg1} / {arg2})",
	"MISSION1_TURN_BACK_TO_THE_START_R": "Turn back to the start (R)",
	"MISSION1_TURN_THE_PAGE": "Turn the Page",
	"MISSION1_RETURN_TO_MAIN_MENU": "Return to main menu",
	"MISSION1_PREVIOUS": "‹ Previous",
	"MISSION1_NEXT": "Next ›",
	"MISSION1_ACTION_CANCELLED": "Action cancelled.",
	"MISSION1_MISSION_D": "Mission {arg1}  ·  ",
	"MISSION1_ALL_ABOARD": "All Aboard  ·  ",
	"MISSION1_THE_PAGES_TURN_BACKWARDS_R_TO_SKIP": "The pages turn backwards…  R to skip",
	"MISSION1_NEARBY_ACTIONS_RIGHT_STICK_TO_CHOOSE_X_TO_REPORT_FOR_DUTY": "Nearby actions: right stick to choose, X to report for duty",
	"MISSION1_NEARBY_ACTIONS_APPEAR_HERE_CLICK_THE_ACTION_OR_PRESS_1_REPORT_FOR": "Nearby actions appear here.\nClick the action or press 1: Report for duty",
	"MISSION1_REPORT_TO_THE_CAPTAIN_FOR_DUTY": "Report to the captain for duty.",
	"MISSION1_RIGHT_STICK_X_INTERACT": "Right stick + X: interact",
	"MISSION1_CLICK_AN_ACTION_OR_PRESS_ITS_NUMBER": "Click an action or press its number",
	"MISSION1_CARRYING": "Carrying: ",
	"MISSION1_USE_THE_LEFT_STICK_TO_REACH_THE_CAPTAIN": "Use the left stick to reach the captain.",
	"MISSION1_TAP_AN_ACTION_TO_INTERACT": "Tap an action to interact.",
	"MISSION1_OPEN_DIARY_TO_READ_YOUR_NOTES_OR_TURN_BACK_THE_PAGES": "Open Diary to read your notes or turn back the pages.",
	"MISSION1_RETRY": "Retry",
	"MISSION1_MAIN_MENU": "Main menu",
	"MISSION1_5_30_THE_UNMOORING_PARTY_IS_OVER": "5:30 · The unmooring party is over.\n\n",
	"MISSION1_7_00_SIX_HOURS_S_END_OF_THE_EXPLORATION_SCHEDULE": "7:00 · Six hours {arg1}.\n\nEnd of the exploration schedule.",
	"MISSION1_IN_GREECE": "in Greece",
	"MISSION1_VOYAGE_COMPLETE": "VOYAGE COMPLETE",
	"MISSION1_VOYAGE_ENDED": "VOYAGE ENDED",
	"MISSION1_THE_NEXT_PAGE": "THE NEXT PAGE",
	"MISSION1_EVERYONE_SURVIVED_NOW_I_CAN_TURN_TO_THE_NEXT_PAGE": "Everyone survived. Now I can turn to the next page.",
	"MISSION1_SCHEDULE_COMPLETE": "SCHEDULE COMPLETE",
	"MISSION1_D_D_D_LEFT_RIGHT_LB_RB": "{arg1}–{arg2} / {arg3}    ·    Left / Right · LB / RB",
	"MISSION1_THE_DIARY_HAS_NO_EARLIER_PAGES_TO_TURN_TO_YET": "The diary has no earlier pages to turn to yet.",
	"MISSION1_CLOSE_SHAVE": "Close shave",
	"MISSION1_THE_DOCKS": "The docks",
	"MISSION1_GRAND_FOYER": "Grand foyer",
	"MISSION1_CABIN_CORRIDOR": "Cabin corridor",
	"MISSION1_STEAM_ROOM": "Steam room",
	"MISSION1_SERVICE_CORRIDOR": "Service corridor",
	"MISSION1_SALON": "Salon",
	"MISSION1_WE_RE_AT_SEA_I_DON_T_WANT_TO_GO_OVERBOARD": "We're at sea. I don't want to go overboard.",
	"MISSION1_MUSIC": "Music",
	"MISSION1_COULD_NOT_CLEAR_MISSION_1_SAVE_D": "Could not clear Mission 1 save ({arg1})",
	"MISSION1_COULD_NOT_WRITE_VOYAGE_JOURNAL": "Could not write voyage journal.",
	"MISSION1_COULD_NOT_FLUSH_VOYAGE_JOURNAL": "Could not flush voyage journal.",
	"MISSION1_COULD_NOT_ROTATE_VOYAGE_BACKUP": "Could not rotate voyage backup.",
	"MISSION1_COULD_NOT_PROTECT_PREVIOUS_VOYAGE": "Could not protect previous voyage.",
	"MISSION1_COULD_NOT_PROMOTE_VOYAGE_JOURNAL": "Could not promote voyage journal.",
	"MISSION1_NO_VALID_MISSION_1_JOURNAL": "No valid Mission 1 journal.",
	"MISSION1_CLOSE_DOOR": "Close door",
	"MISSION1_OPEN_DOOR": "Open door",
	"MISSION1_RETRIEVE_BAG": "Retrieve bag",
	"MISSION1_HIDE_BAG": "Hide bag",
	"MISSION1_WELCOME_TO_GREECE_EXPLORE_THE_DOCK_RESTAURANT_MARKET_AND_SHIP": "Welcome to Greece. Explore the dock, restaurant, market and ship.",
	"MISSION1_A_NEW_DAY_ABOARD_EXPLORE_THE_SHIP": "A new day aboard. Explore the ship.",
	"MISSION1_THE_DOOR_IS_LOCKED": "The door is locked.",
	"MISSION1_SIX_HOURS_IN_GREECE_END_OF_THE_EXPLORATION_SCHEDULE": "Six hours in Greece. End of the exploration schedule.",
	"MISSION1_SIX_HOURS_ABOARD_END_OF_THE_EXPLORATION_SCHEDULE": "Six hours aboard. End of the exploration schedule.",
	"MISSION1_I_VISITED": "I visited ",
	"MISSION1_IS_IN": " is in ",
	"MISSION1_USE_CONTROLS": "Use controls",
	"MISSION1_MISSED_THE_BOAT_MISSION_FAILED_EVERYONE_SURVIVED_BUT_YOU_WERE_STI": "MISSED THE BOAT · MISSION FAILED\nEveryone survived, but you were still on the docks when the ship sailed. Turn back the pages and get aboard before 5:30.",
	"MISSION1_EVERYONE_SURVIVED_ALL_ABOARD_COMPLETE": "EVERYONE SURVIVED · ALL ABOARD COMPLETE\n",
	"MISSION1_THE_NEXT_PAGE_REVEALS_A_NEW_GIFT_LOCATION_REWRITING": "\nThe next page reveals a new gift: location rewriting.",
	"MISSION1_THE_PARTY_HAS_ENDED": "THE PARTY HAS ENDED\n",
	"MISSION1_YOUR_DIARY_RECORDS_WHAT_YOU_WITNESSED_ON_THIS_VOYAGE_TURN_BACK_TH": "\nYour diary records what you witnessed on this voyage. Turn back the pages to try again.",
	"MISSION1_HOUR": "Hour ",
	"MISSION1_HOLD_WAIT": "Hold Wait",
	"MISSION1_TAP_DIARY": "Tap Diary",
	"MISSION1_S_HIGHLIGHT": "{arg1} — Highlight",
	"MISSION1_HOLD_S_WAIT": "Hold {arg1} — Wait",
	"MISSION1_S_OPEN_DIARY": "{arg1} — Open diary",
	"MISSION2_SERVICE_CORRIDOR_CREW_CABINS": "Service corridor · crew cabins",
	"MISSION2_FOREDECK": "Foredeck",
	"MISSION2_CREW_CABIN_DOOR": "Crew cabin door",
	"MISSION3_GREEK_DOCK": "Greek dock",
	"MISSION3_RESTAURANT_DINING_ROOM_AND_KITCHEN": "Restaurant · dining room and kitchen",
	"UI_GUEST_COUNT": "{count} guest",
	"UI_GUEST_COUNT_MANY": "{count} guests",
	"UI_LOADING_THE_VOYAGE_D": "Loading the voyage… {arg1}%",
	"UI_A_VOYAGE_BETWEEN_THE_PAGES": "A VOYAGE BETWEEN THE PAGES",
	"UI_THE_INCREDIBLE_DIARY": "THE INCREDIBLE DIARY",
	"UI_UNABLE_TO_LOAD_THE_DIARY_PLEASE_RESTART": "Unable to load the diary. Please restart.",
	"UI_LOADING_THE_DIARY_D": "Loading the diary… {arg1}%",
	"UI_MADE_WITH_GODOT": "MADE WITH GODOT",
	"UI_JSON_STRINGIFY_WINDOW_DIARY_CONTENT_NULL": "JSON.stringify(window.DIARY_CONTENT || null)",
	"UI_RESOURCE_DOWNLOADS_COULD_NOT_START_PLEASE_RELOAD_THE_PAGE": "Resource downloads could not start. Please reload the page.",
	"UI_A_RESOURCE_COULD_NOT_BE_PREPARED_PLEASE_TRY_AGAIN": "A resource could not be prepared. Please try again.",
	"UI_A_RESOURCE_COULD_NOT_BE_OPENED_PLEASE_TRY_AGAIN": "A resource could not be opened. Please try again.",
	"UI_THERE_IS_NOT_ENOUGH_SPACE_TO_OPEN_THIS_RESOURCE_PLEASE_TRY_AGAIN": "There is not enough space to open this resource. Please try again.",
	"UI_A_DOWNLOADED_RESOURCE_COULD_NOT_BE_OPENED_PLEASE_RELOAD_AND_TRY_A": "A downloaded resource could not be opened. Please reload and try again.",
	"UI_INSPECT": "Inspect",
	"UI_TALK": "Talk",
	"UI_HIDE_BAG": "Hide Bag",
	"UI_STEAM_CONTROL": "STEAM CONTROL",
	"UI_A_NEW_ENTRY_HAS_APPEARED_IN_THE_DIARY": "A new entry has appeared in the diary.",
	"UI_OBSERVATIONS_ARE_RECORDED_HERE_AS_YOU_EXPLORE": "Observations are recorded here as you explore.",
	"UI_A_PASSENGER_DEAD_ABOARD_MY_SHIP_I_CAN_T_SAIL_AFTER_THIS_THE_VOYAG": "A passenger dead aboard my ship... I can't sail after this. The voyage will have to be cancelled!",
	"UI_5_30_ALL_ABOARD_CAST_OFF": "5:30 — All aboard. Cast off!",
	"UI_5_30_THE_VOYAGE_IS_CANCELLED": "5:30 — The voyage is cancelled",
	"UI_HOUR_D": "HOUR {arg1}",
	"UI_VOYAGE_SUMMARY": "VOYAGE SUMMARY",
	"UI_THE_SIX_HOURS_HAVE_ENDED": "The six Hours have ended.",
	"UI_ONLY_WHAT_AMELIA_WITNESSED_IS_RECORDED_HERE": "Only what Amelia witnessed is recorded here.",
	"UI_PASSENGER": "Passenger",
	"UI_WE_SHOULD_LOOK_MORE_CLOSELY": "We should look more closely.",
	"UI_WAITING_20": "Waiting · 20×",
	"UI_NEW_URLSEARCHPARAMS_LOCATION_SEARCH_HAS_GITHUB_INTEGRATION_TEST_N": "new URLSearchParams(location.search).has('github_integration_test') && new URLSearchParams(location.search).get('github_web_smoke') === 'read'",
	"UI_VOYAGE_COMPLETE": "Voyage complete",
	"UI_VOYAGE_ENDED": "Voyage ended",
	"UI_MISSION_FAILED_MISSED_THE_BOAT": "Mission failed — missed the boat",
	"UI_ALL_ABOARD_S_S": "All Aboard · {arg1}\r\n{arg2}",
	"UI_THE_SAVED_VOYAGE_COULD_NOT_BE_LOADED_ITS_FILES_HAVE_BEEN_KEPT": "The saved voyage could not be loaded. Its files have been kept.",
	"UI_DEV_MENU": "Dev Menu",
	"UI_MISSION_1_ALL_ABOARD": "Mission 1 — All Aboard",
	"UI_MISSION_2": "Mission 2",
	"UI_MISSION_3_LANDING_IN_GREECE": "Mission 3 — Landing in Greece",
	"UI_TEST_LEVEL": "Test Level",
	"UI_WINDOW_DIARYTITLEREADY_TRUE_WINDOW_DISPATCHEVENT_NEW_EVENT_DIARY": "window.diaryTitleReady = true; window.dispatchEvent(new Event('diary-title-ready'));",
	"UI_DIARY": "Diary",
	"UI_WAIT": "Wait",
	"UI_HIGHLIGHT": "Highlight",
	"UI_CANCEL": "Cancel",
	"UI_NAVIGATOR_MAXTOUCHPOINTS_0_MATCHMEDIA_POINTER_COARSE_MATCHES": "navigator.maxTouchPoints > 0 && matchMedia('(pointer: coarse)').matches",
	"UI_MATCHMEDIA_ORIENTATION_PORTRAIT_MATCHES": "matchMedia('(orientation: portrait)').matches",
	"UI_MASTER": "Master",
	"UI_DIALOGUE": "Dialogue",
	"UI_PREFERENCES_COULD_NOT_BE_SAVED_CHANGES_WORK_FOR_THIS_SESSION_CLOS": "Preferences could not be saved. Changes work for this session; closing Settings retries.",
	"UI_THE_GAME_COULD_NOT_BE_SAVED_YOU_ARE_STILL_IN_THE_CURRENT_GAME_TRY": "The game could not be saved. You are still in the current game; try again.",
	"UI_THE_MAIN_MENU_COULD_NOT_BE_OPENED_PLEASE_TRY_AGAIN": "The main menu could not be opened. Please try again.",
	"UI_SETTINGS": "Settings",
	"UI_CLOSE": "Close",
	"UI_AUDIO": "Audio",
	"UI_MASTER_VOLUME": "Master volume",
	"UI_CONTROLS": "Controls",
	"UI_MOVEMENT_JOYSTICK_POSITION": "Movement joystick position",
	"UI_BUTTONS_APPEAR_ON_THE_OPPOSITE_SIDE": "Buttons appear on the opposite side.",
	"UI_CLEAR_S_S_BINDING": "Clear {arg1} {arg2} binding",
	"UI_RESTORE_S_DEFAULTS": "Restore {arg1} defaults",
	"UI_CANCEL_BINDING": "Cancel binding",
	"UI_ASSIGN_ANYWAY": "Assign anyway",
	"UI_PRIMARY": "Primary",
	"UI_ALTERNATE": "Alternate",
	"UI_RELEASE_HELD_INPUTS_THEN_PRESS_A_S_INPUT_10_SECONDS": "Release held inputs, then press a {arg1} input (10 seconds).",
	"UI_BINDING_CANCELLED_NO_INPUT_RECEIVED": "Binding cancelled: no input received.",
	"UI_ALREADY_ASSIGNED_TO_S_ASSIGN_ANYWAY": "Already assigned to: {arg1}. Assign anyway?",
	"UI_MOVE_LEFT": "Move left",
	"UI_MOVE_RIGHT": "Move right",
	"UI_MOVE_UP": "Move up",
	"UI_MOVE_DOWN": "Move down",
	"UI_WAIT_HOLD": "Wait (hold)",
	"UI_OPEN_CLOSE_DIARY": "Open/close diary",
	"UI_RESET_LOOP": "Reset loop",
	"UI_CANCEL_ACTION": "Cancel action",
	"UI_INTERACTION_1": "Interaction 1",
	"UI_INTERACTION_2": "Interaction 2",
	"UI_INTERACTION_3": "Interaction 3",
	"UI_INTERACTION_4": "Interaction 4",
	"UI_INTERACTION_5": "Interaction 5",
	"UI_INTERACTION_6": "Interaction 6",
	"UI_INTERACTION_7": "Interaction 7",
	"UI_INTERACTION_8": "Interaction 8",
	"UI_CONFIRM_SELECTED_INTERACTION": "Confirm selected interaction",
	"UI_SUBMIT_CODE": "Submit code",
	"UI_CLEAR_CODE": "Clear code",
	"UI_CONTINUE_AFTER_ENDING": "Continue after ending",
	"UI_PREVIOUS_DIARY_PAGE": "Previous diary page",
	"UI_NEXT_DIARY_PAGE": "Next diary page",
	"UI_THIS_KEY_IS_RESERVED_FOR_PAUSE_EDITOR_CONTROLS": "This key is reserved for pause/editor controls.",
	"UI_THIS_BUTTON_IS_RESERVED_FOR_SETTINGS_OR_PAUSE_EDITOR_CONTROLS": "This button is reserved for Settings or pause/editor controls.",
	"UI_D_PAD_UP": "D-pad Up",
	"UI_D_PAD_DOWN": "D-pad Down",
	"UI_D_PAD_LEFT": "D-pad Left",
	"UI_D_PAD_RIGHT": "D-pad Right",
	"UI_BUTTON_D": "Button {arg1}",
	"UI_SPOKEN_LINE": "{speaker}: {line}",
	"UI_LANGUAGE": "Language",
	"UI_AUTOMATIC": "Automatic",
	"UI_ENGLISH": "English",
	"UI_LOADING_PREPARING": "Preparing the diary…",
	"UI_LOADING_OPENING": "Opening the diary…",
	"UI_LOADING_PROGRESS": "Loading the diary… {percent}%",
	"UI_LOADING_FAILED": "The diary could not be opened.",
	"UI_LOADING_UNKNOWN": "An unknown error occurred.",
	"UI_LOADING_UNSUPPORTED": "Your browser does not support the features needed to open the diary.",
	"UI_CARRYING": "Carrying: {item}",
	"UI_MISSION_HEADING": "Mission {number}  ·  {room}",
	"UI_VOYAGE_HEADING": "All Aboard  ·  {room}",
	"UI_CONTINUE": "CONTINUE",
	"UI_NEW": "NEW",
	"UI_QUIT": "QUIT",
	"UI_START_A_NEW_VOYAGE": "Start a new voyage?",
	"UI_STARTING_NEW_WILL_PERMANENTLY_CLEAR_THE_CURRENT_MISSION_1_SAVE_AN": "Starting New will permanently clear the current Mission 1 save and its recorded history. Continue?",
	"UI_CLEAR_SAVE_AND_START": "Clear save and start",
	"UI_VOYAGE_UNAVAILABLE": "Voyage unavailable",
	"UI_GET_DRINK": "Get {drink}",
	"UI_PREFERS_DRINK": "Prefers {drink}",
	"UI_OFFER_DRINK": "Offer {drink}",
	"UI_VISITED_ROOM": "I visited {room}.",
	"UI_ACTOR_ROOM": "{actor} is in {room}.",
	"UI_ACTION_BINDING": "{binding}  {action}",
	"UI_MARKET": "Market",
	"UI_LEMONADE": "Lemonade",
	"UI_WINE": "Wine",
	"UI_CHAMPAGNE": "Champagne",
	"UI_BRANDY": "Brandy",
	"UI_WHISKY": "Whisky",
	"UI_CLEAR": "Clear",
	"UI_ENTER": "Enter",
	"UI_UNBOUND": "Unbound",
	"UI_CONTROLLER": "Controller",
	"UI_KEYBOARD": "Keyboard",
	"UI_TOUCH": "Touch",
	"UI_SFX": "SFX",
	"UI_SUMMARY_SURVIVED": "{name}: survived",
	"UI_SUMMARY_DIED": "{name}: died",
	"UI_SUMMARY_SUCCESS": "EVERYONE SURVIVED · ALL ABOARD COMPLETE\r\n{outcomes}\r\nThe next page reveals a new gift: location rewriting.",
	"UI_SUMMARY_FAILED": "THE PARTY HAS ENDED\r\n{outcomes}\r\nYour diary records what you witnessed on this voyage. Turn back the pages to try again.",
	"UI_DIARY_OUTCOME": "5:30 · The unmooring party is over.\r\n\r\n{summary}",
	"UI_SETTINGS_UPPER": "SETTINGS",
	"UI_CONTROL_LEFT": "Left",
	"UI_CONTROL_RIGHT": "Right",
	"UI_CONTROL_KEYBOARD": "keyboard",
	"UI_CONTROL_CONTROLLER": "controller",
	"UI_CONTROL_TOUCH": "touch",
	"UI_CONTROL_PRIMARY": "primary",
	"UI_CONTROL_ALTERNATE": "alternate",
	"UI_CONTROL_ABOARD": "aboard",
	"UI_BINDING_SLOT": "{slot}: {binding}",
	"UI_BINDING_TOOLTIP": "{action} — {slot}: {binding}",
	"UI_GENERAL": "General",
	"UI_CONFIRM": "CONFIRM",
	"UI_PEOPLE": "PEOPLE",
	"UI_MOVE": "Move",
	"UI_TEA": "Tea",
	"UI_ACCESSIBILITY": "Accessibility",
	"UI_HIGH_CONTRAST_TEXT_PANELS": "High-contrast text panels",
	"UI_INSTANT_DIALOGUE_TEXT": "Instant dialogue text",
	"UI_STEAM_ON": "On",
	"UI_STEAM_OFF": "Off",
	"UI_STOP_WAITING": "Stop",
	"UI_WAIT_TOGGLE": "Wait (toggle)",
	"MISSION1_TOGGLE_B_WAIT": "B — Toggle Wait",
	"MISSION1_TOGGLE_F_WAIT": "F — Toggle Wait",
	"MISSION1_TAP_WAIT": "Tap Wait to start/stop",
	"MISSION1_TOGGLE_S_WAIT": "{arg1} — Toggle Wait"
}
