"""Validate CSV catalogues; --generate refreshes deterministic source constants."""
import argparse
import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKEN = re.compile(r"\{([A-Za-z][A-Za-z0-9_]*)\}")


def catalogues():
    messages = {}
    for path in sorted((ROOT / 'localisation').glob('*.csv')):
        with path.open(encoding='utf-8', newline='') as stream:
            previous = None
            for row in csv.DictReader(stream):
                key = row['keys']
                if key.startswith('?'):
                    continue
                if not key:
                    if previous is None:
                        raise ValueError(f'Orphan plural form: {path.name}')
                    placeholders = set(TOKEN.findall(previous['en']))
                    for locale, value in row.items():
                        if locale == 'keys' or locale.startswith(('_', '?')) or not value:
                            continue
                        if set(TOKEN.findall(value)) != placeholders:
                            raise ValueError(f'Plural placeholder mismatch: {previous["keys"]}/{locale}')
                    continue
                if key in messages:
                    raise ValueError(f'Duplicate message ID: {key}')
                if not row.get('en'):
                    raise ValueError(f'Missing English: {key}')
                if not re.fullmatch(r'[A-Z][A-Z0-9_]+', key):
                    raise ValueError(f'Invalid stable message ID: {key}')
                placeholders = set(TOKEN.findall(row['en']))
                for locale, value in row.items():
                    if locale in ('keys', 'en') or locale.startswith(('_', '?')) or not value:
                        continue
                    if set(TOKEN.findall(value)) != placeholders:
                        raise ValueError(f'Placeholder mismatch: {key}/{locale}')
                messages[key] = row
                previous = row
    return messages


def generated(messages):
    quote = lambda value: json.dumps(value, ensure_ascii=False)
    lines = ['extends RefCounted', '## Generated by tools/localisation.py --generate. Edit the CSV catalogues.']
    for key, row in messages.items():
        lines.append(f'const {key} = {quote(row.get("_source") or row["en"])}')
    for name, values in [
        ('SOURCES', {k: v.get('_source') or v['en'] for k, v in messages.items()}),
        ('ENGLISH', {k: v['en'] for k, v in messages.items()}),
    ]:
        lines.append('const '+name+' = '+json.dumps(values, ensure_ascii=False, indent='\t'))
    return '\n'.join(lines)+'\n'


def validate_references(messages):
    for folder in ['assets', 'foundation', 'mission1', 'mission2', 'mission3']:
        for path in (ROOT / folder).rglob('*.gd'):
            source = path.read_text(encoding='utf-8-sig')
            for key in re.findall(r'\bText\.([A-Z][A-Z0-9_]+)|\[ID:([A-Z][A-Z0-9_]+)\]', source):
                value = key[0] or key[1]
                if value not in messages and value not in ('SOURCES', 'ENGLISH'):
                    raise ValueError(f'{path.relative_to(ROOT)}: unknown message {value}')
            for value in re.findall(r'Messages\.(?:make_ref|source|plural)\("([A-Z0-9_]+)"', source):
                if value not in messages:
                    raise ValueError(f'{path.relative_to(ROOT)}: unknown message {value}')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--generate', action='store_true')
    args = parser.parse_args()
    messages = catalogues()
    validate_references(messages)
    target = ROOT / 'localisation/source_text.gd'
    expected = generated(messages)
    if args.generate:
        target.write_text(expected, encoding='utf-8')
        from build_loading_screen import main as build_shell
        build_shell()
    elif not target.exists() or target.read_text(encoding='utf-8') != expected:
        raise ValueError('Source constants are stale; run tools/localisation.py --generate')
    print(f'LOCALISATION PASS: {len(messages)} messages')


if __name__ == '__main__':
    main()
